local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-teamRoomSelectView_Layer1_teamFight_Game",
			UUID = "d9959ed0_8521_4a72_808b_12498779ab1c",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
					UUID = "8f707cff_2246_47ed_a9fc_c6bf11ba61a9",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "80",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
							UUID = "fcfb911f_9dff_494c_bfc4_161a95ee7adf",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#00FFFFFF;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "510",
							ignoreSize = "False",
							name = "Panel_setting_pad",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 320,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1015",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_big_bg_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "8bfad8f0_62e6_48d3_ba2d_cc9220de5069",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "518",
									ignoreSize = "False",
									name = "Image_big_bg",
									sizepercentx = "7",
									sizepercenty = "12",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/pop_ui/pop_bg_01.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "1030",
									ZOrder = "1",
								},
								{
									controlID = "Image_big_bg2_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "51b41b0c_6d82_4576_b66d_7b97843c882a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "394",
									ignoreSize = "False",
									name = "Image_big_bg2",
									sizepercentx = "7",
									sizepercenty = "12",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/pop_ui/pop_bg_02.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 9,
									},
									width = "1007",
									ZOrder = "1",
								},
								{
									controlID = "Button_close_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "de6a34e2_5d8d_4e6b_9492_49b20f9237bc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "60",
									ignoreSize = "True",
									name = "Button_close",
									normal = "ui/common/pop_ui/pop_btn_02.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 470,
										PositionY = 228,
									},
									UItype = "Button",
									width = "60",
									ZOrder = "1",
								},
								{
									controlID = "Label_pad_title_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "a4a96694_4369_4e45_81b5_2a5c7ad793ad",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF30354A",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "Label_pad_title",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Team-Raum",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -495,
										PositionY = 225,
									},
									width = "113",
									ZOrder = "1",
								},
								{
									controlID = "Image_sign_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "90c4db66_ea99_4595_86b5_cbd2320d2157",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "32",
									ignoreSize = "True",
									name = "Image_sign",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/setting/uires/003.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -374,
										PositionY = 225,
									},
									width = "4",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_teamRoomView_1_Image_sign_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
											UUID = "c5ad22e6_e287_41eb_ba1d_2160cc86ea3b",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF49557F",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_teamRoomView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Rooms",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 10,
											},
											width = "61",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "fe6a3339_29a9_47f7_a87e_1d4e93a960e4",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "390",
									ignoreSize = "False",
									name = "Panel_level",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -501,
										PositionY = -184,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "1000",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
											UUID = "2c1ca398_066a_43f6_ba0b_58c5612c07fb",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "400",
											ignoreSize = "False",
											name = "Pane_lvl_btns",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 34,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "400",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Button_1_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
													UUID = "7338118d_7e44_41c5_974c_8a4d29d3736e",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "102",
													ignoreSize = "True",
													name = "Button_1",
													normal = "ui/common/mini_pop/037.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 107,
														PositionY = 206,
														LeftPositon = 440,
														TopPosition = 214,
														relativeToName = "Panel",
													},
													UItype = "Button",
													width = "102",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_select_Button_1_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "09a12506_88cc_4c10_abcb_9196fb354cd8",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "102",
															ignoreSize = "True",
															name = "Image_select",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/mini_pop/039.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = -1,
															},
															width = "102",
															ZOrder = "1",
														},
														{
															controlID = "Image_icon_Button_1_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "d4bf40d9_7065_44c7_81ed_67b201a5bc81",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "58",
															ignoreSize = "False",
															name = "Image_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/teampve/huntingInvitation/D.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "58",
															ZOrder = "1",
														},
														{
															controlID = "Label_times_Button_1_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "9ddeb80e_f1b4_42ef_ad9e_7cb309d746a7",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_times",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "TextLable",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -70,
															},
															width = "63",
															ZOrder = "1",
														},
														{
															controlID = "Image_sign_Button_1_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "f7f8e4b8_da0d_4d37_a5ec_5619eea81dc0",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "54",
															ignoreSize = "True",
															name = "Image_sign",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/selected.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 31,
																PositionY = -34,
															},
															width = "54",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Button_2_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
													UUID = "a9317aa2_1fa2_4437_8cc4_b21870a8bb9a",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "102",
													ignoreSize = "True",
													name = "Button_2",
													normal = "ui/common/mini_pop/037.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 267,
														PositionY = 206,
														LeftPositon = 440,
														TopPosition = 214,
														relativeToName = "Panel",
													},
													UItype = "Button",
													width = "102",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_select_Button_2_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "d738c283_d19b_4c5d_9a70_0db587996857",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "102",
															ignoreSize = "True",
															name = "Image_select",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/mini_pop/039.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = -1,
															},
															width = "102",
															ZOrder = "1",
														},
														{
															controlID = "Image_icon_Button_2_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "a3cd97db_488f_4bed_a247_7fcca84377b9",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "58",
															ignoreSize = "False",
															name = "Image_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/teampve/huntingInvitation/D.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "58",
															ZOrder = "1",
														},
														{
															controlID = "Label_times_Button_2_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "287a5254_13e9_4735_99fa_b277ec13f8b6",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_times",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "TextLable",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -70,
															},
															width = "63",
															ZOrder = "1",
														},
														{
															controlID = "Image_sign_Button_2_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "60ef346c_099e_4f6b_8c25_5827415e1aa6",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "54",
															ignoreSize = "True",
															name = "Image_sign",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/selected.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 33,
																PositionY = -34,
															},
															width = "54",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Button_3_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
													UUID = "c390fbba_d055_4e3f_b9ed_5e335a82327c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "102",
													ignoreSize = "True",
													name = "Button_3",
													normal = "ui/common/mini_pop/037.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 427,
														PositionY = 206,
														LeftPositon = 440,
														TopPosition = 214,
														relativeToName = "Panel",
													},
													UItype = "Button",
													width = "102",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_select_Button_3_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "be7a2cdc_2ca5_4478_9c4f_9446e7491287",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "102",
															ignoreSize = "True",
															name = "Image_select",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/mini_pop/039.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = -1,
															},
															width = "102",
															ZOrder = "1",
														},
														{
															controlID = "Image_icon_Button_3_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "e21b81e2_95a9_4354_a990_d780fdbb3afa",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "58",
															ignoreSize = "False",
															name = "Image_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/teampve/huntingInvitation/D.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "58",
															ZOrder = "1",
														},
														{
															controlID = "Label_times_Button_3_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "d9e075c6_305e_49c2_abe6_79f9943cd3c5",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_times",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "TextLable",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -70,
															},
															width = "63",
															ZOrder = "1",
														},
														{
															controlID = "Image_sign_Button_3_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "48981816_55b1_4c07_8ad5_bf2f2fdd9579",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "54",
															ignoreSize = "True",
															name = "Image_sign",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/selected.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 33,
																PositionY = -34,
															},
															width = "54",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Button_4_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
													UUID = "b12a2f92_371e_4abf_9802_8d72a404d1b2",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "102",
													ignoreSize = "True",
													name = "Button_4",
													normal = "ui/common/mini_pop/037.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 587,
														PositionY = 206,
														LeftPositon = 440,
														TopPosition = 214,
														relativeToName = "Panel",
													},
													UItype = "Button",
													width = "102",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_select_Button_4_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "3d3a896d_3be2_4b93_bdf1_fa5593380e68",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "102",
															ignoreSize = "True",
															name = "Image_select",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/mini_pop/039.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = -1,
															},
															width = "102",
															ZOrder = "1",
														},
														{
															controlID = "Image_icon_Button_4_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "b9da38a2_a0a1_4007_bf7c_9ccf2c65e243",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "58",
															ignoreSize = "False",
															name = "Image_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/teampve/huntingInvitation/D.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "58",
															ZOrder = "1",
														},
														{
															controlID = "Label_times_Button_4_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "245fb77a_eb3d_498d_85a0_d4a8872f2520",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_times",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "TextLable",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -70,
															},
															width = "63",
															ZOrder = "1",
														},
														{
															controlID = "Image_sign_Button_4_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "d75f5542_c84e_428d_8c28_3a7896b28d0f",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "54",
															ignoreSize = "True",
															name = "Image_sign",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/selected.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 33,
																PositionY = -34,
															},
															width = "54",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Button_5_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
													UUID = "e2b6a7b5_6fbd_4c4d_b5d4_a94c8011e28f",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "102",
													ignoreSize = "True",
													name = "Button_5",
													normal = "ui/common/mini_pop/037.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 747,
														PositionY = 206,
														LeftPositon = 440,
														TopPosition = 214,
														relativeToName = "Panel",
													},
													UItype = "Button",
													width = "102",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_select_Button_5_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "9be99182_c92e_461e_b957_aa44f1010c2f",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "102",
															ignoreSize = "True",
															name = "Image_select",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/mini_pop/039.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = -1,
															},
															width = "102",
															ZOrder = "1",
														},
														{
															controlID = "Image_icon_Button_5_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "dc937dd0_87a6_4d12_9ba9_bb3bce41360f",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "58",
															ignoreSize = "False",
															name = "Image_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/teampve/huntingInvitation/D.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "58",
															ZOrder = "1",
														},
														{
															controlID = "Label_times_Button_5_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "90ab2975_c641_4899_b357_920860f978a2",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_times",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "TextLable",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -70,
															},
															width = "63",
															ZOrder = "1",
														},
														{
															controlID = "Image_sign_Button_5_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "b76f3a6e_01a2_40e7_958f_2990823fe134",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "54",
															ignoreSize = "True",
															name = "Image_sign",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/selected.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 33,
																PositionY = -34,
															},
															width = "54",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Button_6_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
													UUID = "febbd9ec_bd03_4eb5_97c1_0323ae51e008",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "102",
													ignoreSize = "True",
													name = "Button_6",
													normal = "ui/common/mini_pop/037.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = 907,
														PositionY = 206,
														LeftPositon = 440,
														TopPosition = 214,
														relativeToName = "Panel",
													},
													UItype = "Button",
													width = "102",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_select_Button_6_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "ae75ad00_a61c_49b2_99bd_7a3ff4641d02",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "102",
															ignoreSize = "True",
															name = "Image_select",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/mini_pop/039.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = -1,
															},
															width = "102",
															ZOrder = "1",
														},
														{
															controlID = "Image_icon_Button_6_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "a0ba051f_6435_4edc_8e8d_04b6f60fbda6",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "58",
															ignoreSize = "False",
															name = "Image_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/teampve/huntingInvitation/D.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "58",
															ZOrder = "1",
														},
														{
															controlID = "Label_times_Button_6_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "7b0deca4_5b65_40d4_90a0_ace85bda3285",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "18",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "21",
															ignoreSize = "True",
															name = "Label_times",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "TextLable",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -70,
															},
															width = "63",
															ZOrder = "1",
														},
														{
															controlID = "Image_sign_Button_6_Pane_lvl_btns_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
															UUID = "24f55bcd_4457_497c_80c8_8838b79c419b",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "54",
															ignoreSize = "True",
															name = "Image_sign",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/common/selected.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 33,
																PositionY = -34,
															},
															width = "54",
															ZOrder = "1",
														},
													},
												},
											},
										},
										{
											controlID = "TextButton_single_match_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
											UUID = "46cefdd7_4ddf_4ab2_b88d_fbe4bbc466eb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "METextButton",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "58",
											ignoreSize = "True",
											name = "TextButton_single_match",
											normal = "ui/common/button_big_n.png",
											outlineColor = "#FF921E3F",
											outlineSize = "2",
											shadowColor = "#FF000000",
											shadowHeight = "0",
											shadowWidth = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											titlefontName = "font/fangzheng_zhunyuan.ttf",
											titlefontSize = "26",
											titletext = "Solo-Paarung",
											titletextColor = "#FFFFFFFF",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 931,
												PositionY = -35,
											},
											useOutline = "False",
											useShadow = "False",
											width = "134",
											ZOrder = "1",
										},
										{
											controlID = "TextButton_stop_match_Panel_level_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
											UUID = "5304ce80_0def_4c62_b544_d176b688782b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "METextButton",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "58",
											ignoreSize = "True",
											name = "TextButton_stop_match",
											normal = "ui/common/button_big_n.png",
											outlineColor = "#FF921E3F",
											outlineSize = "2",
											shadowColor = "#FF000000",
											shadowHeight = "0",
											shadowWidth = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											titlefontName = "font/fangzheng_zhunyuan.ttf",
											titlefontSize = "26",
											titletext = "Paarung stoppen",
											titletextColor = "#FFFFFFFF",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 931,
												PositionY = -35,
											},
											useOutline = "False",
											useShadow = "False",
											width = "134",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_timer_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "34cab6b9_35a8_4d2a_8683_0d7cb4bccedc",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "20",
									ignoreSize = "False",
									name = "Panel_timer",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -568,
										PositionY = -320,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "20",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_touch_shield_Panel_timer_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
											UUID = "78598c60_bdb8_4f55_98c5_5d2c8b90737d",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "395",
											ignoreSize = "False",
											name = "Panel_touch_shield",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 68,
												PositionY = 130,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "1000",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_des_Panel_setting_pad_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
									UUID = "ccfb0c7a_33f2_4895_ab83_d7d237767d78",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_des",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Bitte wähle das Runensteinlevel aus, das schnell hinzugefügt werden muss",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = 154,
									},
									width = "339",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Label_desc_Panel_root_Panel-teamRoomSelectView_Layer1_teamFight_Game",
							UUID = "c80eca03_34de_4ef6_ae1f_7b5792bfa1d0",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "27",
							ignoreSize = "True",
							name = "Label_desc",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Beschreibung",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 580,
								PositionY = 221,
							},
							width = "51",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/common/pop_ui/pop_bg_01.png",
			"ui/common/pop_ui/pop_bg_02.png",
			"ui/common/pop_ui/pop_btn_02.png",
			"ui/setting/uires/003.png",
			"ui/common/mini_pop/037.png",
			"ui/common/mini_pop/039.png",
			"ui/teampve/huntingInvitation/D.png",
			"ui/common/selected.png",
			"ui/common/button_big_n.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

