local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-taskTrainingBuyLevelView_Layer1_task_Game",
			UUID = "616a232c_537a_444e_87d1_383abadd03ed",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
					UUID = "5e289460_dc67_4971_8037_81ebb5e3c685",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_base",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_back_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "667dc977_1267_4c98_8a69_031a4e2e7909",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_back",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1136",
							ZOrder = "1",
						},
						{
							controlID = "background_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "4963c986_193d_48a4_b16f_1464efb8e4d5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "429",
							ignoreSize = "False",
							name = "background",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/common/pop_ui/pop_bg_01.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 320,
								IsPercent = true,
								PercentX = 50,
								PercentY = 50,
							},
							width = "742",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg1_background_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
									UUID = "aaabe54c_b7b1_4aa6_a9c5_fa3c3c61f5ad",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "303",
									ignoreSize = "False",
									name = "Image_bg1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/pop_ui/pop_bg_02.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 12,
									},
									width = "717",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Label_title_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "f8a5e6b3_56cb_4723_9a25_ac6a3464a1db",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							ColorMixing = "#FFC0C8D0",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF30354A",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "28",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "32",
							ignoreSize = "True",
							name = "Label_title",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Kauflevel",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 212,
								PositionY = 502,
							},
							width = "127",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "34b9b888_bd74_4e96_907f_5c087d90080a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "26",
							ignoreSize = "True",
							name = "Image_line",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/common/pop_ui/pop_ui_02.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 334,
								PositionY = 502,
							},
							visible = "False",
							width = "2",
							ZOrder = "1",
						},
						{
							controlID = "Label_title_en_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "f5635d65_5988_44b7_9af3_c7b99d96393f",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF30354A",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "16",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "18",
							ignoreSize = "True",
							name = "Label_title_en",
							nTextAlign = "2",
							nTextHAlign = "0",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Information Creator",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 338,
								PositionY = 496,
							},
							visible = "False",
							width = "134",
							ZOrder = "1",
						},
						{
							controlID = "Label_num_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "caedafe5_7031_4712_b5da_fb72378083f2",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF46487B",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "26",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "30",
							ignoreSize = "True",
							name = "Label_num",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Kaufe XX Level",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 274,
								PositionY = 149,
							},
							width = "164",
							ZOrder = "1",
						},
						{
							controlID = "Button_down_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "678d6ca0_6977_4a52_b3ef_e185b9597b0c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "44",
							ignoreSize = "True",
							name = "Button_down",
							normal = "ui/task/training/ui_001.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 361,
								PositionY = 150,
							},
							UItype = "Button",
							width = "44",
							ZOrder = "1",
						},
						{
							controlID = "Button_up_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "0512021c_4a0a_476e_825c_003d33585562",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "44",
							ignoreSize = "True",
							name = "Button_up",
							normal = "ui/task/training/ui_002.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 623,
								PositionY = 150,
							},
							UItype = "Button",
							width = "44",
							ZOrder = "1",
						},
						{
							controlID = "Slider_level_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "2014a71d_4f0c_4c00_8c7b_ded800a4021e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MESlider",
							dstBlendFunc = "771",
							height = "11",
							ignoreSize = "False",
							name = "Slider_level",
							percent = "100",
							progressbartexture = "ui/task/training/ui_008.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texture = "ui/task/training/ui_008.png",
							texturenormal = "ui/task/training/ui_020.png",
							texturepressed = "ui/task/training/ui_020.png",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 492,
								PositionY = 150,
							},
							width = "190",
							ZOrder = "1",
						},
						{
							controlID = "Button_close_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "3d454278_6093_4f38_8b1a_9ea799f4291c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "60",
							ignoreSize = "True",
							name = "Button_close",
							normal = "ui/common/pop_ui/pop_btn_02.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 908,
								PositionY = 504,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
						},
						{
							controlID = "Button_ok_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "7fe56908_68e1_461c_8fea_e35961958779",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "56",
							ignoreSize = "False",
							name = "Button_ok",
							normal = "ui/common/button09.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 863,
								PositionY = 148,
							},
							UItype = "Button",
							width = "120",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_buy_Button_ok_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
									UUID = "fac0ef2f_641b_4ddc_9c21_f2e13d1a645f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_buy",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Kaufen",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = -1,
									},
									width = "86",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "ScrollView_items_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "3f67e2e2_c5f3_43e8_ae3b_9d7dcbee6c32",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "1",
							dstBlendFunc = "771",
							height = "209",
							ignoreSize = "False",
							innerHeight = "209",
							innerWidth = "682",
							name = "ScrollView_items",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 225,
								PositionY = 230,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "682",
							ZOrder = "1",
						},
						{
							controlID = "Label_tips_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "9e2800a6_cd52_4f28_89a0_acae796ba638",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFE0E4EF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "0",
							ignoreSize = "False",
							name = "Label_tips",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Textbeschreibung Textbeschreibung Textbeschreibung Textbeschreibung Textbeschreibung Textbeschreibung",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 200,
							},
							width = "700",
							ZOrder = "1",
						},
						{
							controlID = "Label_desc_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "a0c9d6e8_4aa3_43b8_ac87_b183f7425195",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "25",
							ignoreSize = "True",
							name = "Label_desc",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Upgrade auf Level XX, um die folgenden XX Belohnungen zu erhalten",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 460,
							},
							width = "643",
							ZOrder = "1",
						},
						{
							controlID = "Image_cost_bg_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "d9074cc4_3752_42a2_b210_96e48436d147",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "60",
							ignoreSize = "False",
							name = "Image_cost_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/Equipment/new_ui/new_38.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 725,
								PositionY = 150,
							},
							width = "130",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_res_icon_Image_cost_bg_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
									UUID = "8b8c7b2a_7156_4942_96f9_5320c39feea1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_res_icon",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/system/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -36,
										PositionY = -3,
									},
									width = "100",
									ZOrder = "1",
								},
								{
									controlID = "Label_res_num_Image_cost_bg_Panel_base_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
									UUID = "4d4826fb_d579_4f05_871e_6781ddc3f0c2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_res_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "30000",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 20,
										PositionY = -3,
									},
									width = "63",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_goodsItem_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
					UUID = "7b6821c9_57b8_4e8e_b1ac_23bbd05591d2",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "123",
					ignoreSize = "False",
					name = "Panel_goodsItem",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = -104,
						PositionY = -91,
						LeftPositon = -154,
						TopPosition = 670,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "100",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_frame_Panel_goodsItem_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "c630dde3_9084_4549_bea0_418209110dd4",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "90",
							ignoreSize = "False",
							name = "Image_frame",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/common/frame_normal.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "90",
							ZOrder = "1",
						},
						{
							controlID = "Image_icon_Panel_goodsItem_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "25d6618b_1734_4a14_9e21_2ef3d7c2e833",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "90",
							ignoreSize = "False",
							name = "Image_icon",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "icon/item/goods/510201.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "90",
							ZOrder = "1",
						},
						{
							controlID = "Label_count_Panel_goodsItem_Panel-taskTrainingBuyLevelView_Layer1_task_Game",
							UUID = "9fef3628_cab4_47f3_b611_c02f884968af",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF000000",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "16",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FFFFFFFF",
								StrokeSize = 1,
							},
							height = "20",
							ignoreSize = "True",
							name = "Label_count",
							nTextAlign = "1",
							nTextHAlign = "2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "x1000",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 41,
								PositionY = 29,
							},
							width = "44",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/common/pop_ui/pop_bg_01.png",
			"ui/common/pop_ui/pop_bg_02.png",
			"ui/common/pop_ui/pop_ui_02.png",
			"ui/task/training/ui_001.png",
			"ui/task/training/ui_002.png",
			"ui/task/training/ui_008.png",
			"ui/task/training/ui_020.png",
			"ui/common/pop_ui/pop_btn_02.png",
			"ui/common/button09.png",
			"ui/Equipment/new_ui/new_38.png",
			"icon/system/005.png",
			"ui/common/frame_normal.png",
			"icon/item/goods/510201.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

