local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-JoinLeagueLayer_Layer1_league_Game",
			UUID = "54ab22cc_c9bd_45e3_a160_054cfe658ee8",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
					UUID = "2bfcb211_173a_4992_a2df_eda911c1e188",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						IsPercent = true,
						PercentX = 50,
						PercentY = 50,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_01_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "b6e4418d_cd21_4cb6_ac9a_9a98fe971219",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg_01",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/common/bg_01.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel_back",
								nGravity = 6,
								nAlign = 5
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Image_JoinLeagueLayer_1_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "7e92310e_d01b_473c_9aa1_06312bc5bf75",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_JoinLeagueLayer_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui/league/加入社团P2 拷贝.jpg",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "ScrollView_league_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "278c4255_f354_45bd_9eff_5ac0ddc14e41",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "True",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "1",
							dstBlendFunc = "771",
							height = "420",
							ignoreSize = "False",
							innerHeight = "420",
							innerWidth = "800",
							name = "ScrollView_league",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -45,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "800",
							ZOrder = "1",
						},
						{
							controlID = "CheckBox_join_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "1e7a66ef_3280_45f0_8d2e_f7d30af1140a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							backGroundTexture = "ui/league/ui_58.png",
							classname = "MECheckBox",
							clickType = "0",
							dstBlendFunc = "771",
							frontCrossTexture = "ui/league/ui_57.png",
							height = "40",
							ignoreSize = "False",
							name = "CheckBox_join",
							selectedState = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							tableAttribute = "False",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -382,
								PositionY = 192,
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Label_limit_tips_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "ddfca1a8_7545_408f_b7cf_5658a9a67aa3",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "25",
							ignoreSize = "True",
							name = "Label_limit_tips",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "只显示可加入的社团",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -349,
								PositionY = 192,
							},
							width = "200",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_tips_line_Label_limit_tips_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "d78a5a89_e29b_41e9_b64c_aa3ba938fddf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									flipX = "True",
									height = "32",
									ignoreSize = "False",
									name = "Image_tips_line",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/Equipment/new_ui/new_09.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -5,
									},
									width = "4",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_fast_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "eaade12a_c951_4ca7_8e75_19a6cb1148a2",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "48",
							ignoreSize = "False",
							name = "Button_fast",
							normal = "ui/common/button09.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -340,
								PositionY = -290,
								relativeToName = "Panel_root",
							},
							UItype = "Button",
							width = "120",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_fast_Button_fast_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "d0de7893_fa1a_471f_9c69_a070a85cdc41",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_fast",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "快速加入",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_refresh_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "5046a71b_2488_4db7_8624_587532acea47",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "48",
							ignoreSize = "False",
							name = "Button_refresh",
							normal = "ui/common/button09.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 340,
								PositionY = -290,
								relativeToName = "Panel_root",
							},
							UItype = "Button",
							width = "120",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_refresh_Button_refresh_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "24c547d5_47ee_4990_bc47_72d1da5fbe1f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_refresh",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "刷新列表",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_placeholder_bg_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "4acc7a46_835d_4c15_bca0_e6aa3094bb78",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "50",
							ignoreSize = "False",
							name = "Image_placeholder_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/league/ui_55.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 189,
								PositionY = 200,
							},
							width = "170",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_JoinLeagueLayer_1(2)_Image_placeholder_bg_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "d0a330b7_3b9c_434c_8a4e_6555cfd77e48",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "35",
									ignoreSize = "False",
									name = "Image_JoinLeagueLayer_1(2)",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/league/ui_59.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
									},
									width = "150",
									ZOrder = "1",
								},
								{
									controlID = "TextField_league_id_Image_placeholder_bg_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "de3f07ad_6455_4a63_8fa1_7f5a88ebac70",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "METextField",
									CursorEnabled = "False",
									dstBlendFunc = "771",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontSize = "22",
									hAlignment = "1",
									height = "45",
									ignoreSize = "False",
									KeyBoradType = "0",
									maxLengthEnable = "True;maxLength:16",
									name = "TextField_league_id",
									outlineColor = "#FF000000",
									outlineSize = "1",
									passwordEnable = "False",
									placeHolder = "输入社团ID",
									shadowColor = "#FF000000",
									shadowHeight = "0",
									shadowWidth = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 1,
									},
									useOutline = "False",
									useShadow = "False",
									vAlignment = "0",
									visible = "False",
									width = "160",
									ZOrder = "1",
								},
								{
									controlID = "Label_league_id_Image_placeholder_bg_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "e251c1d7_80fd_4eb6_90da_968cb6549338",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									HitType = 
									{
										nHitType = 1,
										nXpos = -78,
										nYpos = -20,
										nHitWidth = 161,
										nHitHeight = 39
									},
									ignoreSize = "True",
									name = "Label_league_id",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "输入社团ID",
									touchAble = "True",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -3,
									},
									width = "109",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_search_join_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "4d970dcd_fe62_4572_8f6a_2e327f1cfb19",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "48",
							ignoreSize = "False",
							name = "Button_search_join",
							normal = "ui/common/button09.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 339,
								PositionY = 200,
								LeftPositon = 1416,
								TopPosition = -224,
								relativeToName = "Panel_root",
							},
							UItype = "Button",
							width = "120",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_search_join_Button_search_join_Panel_root_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "bcdac528_ecb7_4c90_bc58_46c8d1e144a1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_search_join",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "查找加入",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
					UUID = "2973eeea_0ec8_4514_bc7f_96ae9e8a2cdc",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFDDA0DD;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "726",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -32,
						PositionY = -805,
						LeftPositon = -32,
						TopPosition = 805,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1036",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
							UUID = "f87cdf3f_97a8_4e05_bdf0_61d6e3d6be6b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "120",
							ignoreSize = "False",
							name = "Panel_league_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 504,
								PositionY = 200,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "800",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "d6da3511_1008_4825_8568_e66e5ff66248",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:110;capInsetsY:40;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "False",
									name = "Image_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/mail/mail_12.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "800",
									ZOrder = "1",
								},
								{
									controlID = "Image_league_flag_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "b08707bb_53ae_46a4_adae_6f0a710ea2f3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "49",
									ignoreSize = "True",
									name = "Image_league_flag",
									scaleX = "0.7",
									scaleY = "0.7",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/chat/118.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -346,
										PositionY = -11,
									},
									width = "49",
									ZOrder = "1",
								},
								{
									controlID = "Label_league_name_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "16a4a5e7_9e59_4f94_b420_b1fc4fbd1d5f",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3E4474",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_league_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "社团名称八个字",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -278,
										PositionY = 10,
									},
									width = "157",
									ZOrder = "1",
								},
								{
									controlID = "Label_league_level_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "9a8bb86b_d44a_4d27_9092_26b4b1d14e84",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3E4474",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_league_level",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Lv 99",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -276,
										PositionY = -35,
									},
									width = "50",
									ZOrder = "1",
								},
								{
									controlID = "Label_members_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "6a12fc0d_f567_43e3_a3a6_3974b3de6bb2",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_members",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "社团人数：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 240,
										PositionY = 45,
									},
									width = "90",
									ZOrder = "1",
								},
								{
									controlID = "Label_active_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "b6880bf4_62e7_4dc3_9ccf_a7384c97f879",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3E4474",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_active",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "社团活跃度：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -50,
										PositionY = 10,
									},
									width = "110",
									ZOrder = "1",
								},
								{
									controlID = "Label_limit_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "ef72c142_1b31_4363_88ba_a2bf771aea2b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3E4474",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_limit",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "加入要求：",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -50,
										PositionY = -35,
									},
									width = "90",
									ZOrder = "1",
								},
								{
									controlID = "Label_members_num_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "1100fd69_73ea_40ef_9f19_0e6675940392",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_members_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "60 90",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 336,
										PositionY = 45,
									},
									width = "52",
									ZOrder = "1",
								},
								{
									controlID = "Label_active_num_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "4c1d7079_a27e_4d5f_8c31_f6a3237ef49c",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3E4474",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_active_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "100%",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 60,
										PositionY = 10,
									},
									width = "46",
									ZOrder = "1",
								},
								{
									controlID = "Label_limit_desc_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "85e4a747_c3e4_440b_8a72_020efa34f4fa",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3E4474",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_limit_desc",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "战斗力 > 9999999",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 50,
										PositionY = -35,
									},
									width = "161",
									ZOrder = "1",
								},
								{
									controlID = "Button_aply_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "02f1dacc_6835_47a9_96a0_345b5a52eda9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "44",
									ignoreSize = "True",
									name = "Button_aply",
									normal = "ui/common/button_small_blue_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 320,
										PositionY = -10,
									},
									UItype = "Button",
									width = "108",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_aply_Button_aply_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
											UUID = "087656ff_c698_4f21_b8c2_d9422b4a9479",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_aply",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "申请加入",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "91",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_aplied_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "13495502_bcd8_4682_9efb_f61292a2fc0a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_aplied",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "已申请",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 320,
										PositionY = -10,
									},
									width = "70",
									ZOrder = "1",
								},
								{
									controlID = "Button_join_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "bd2d8f2f_3f08_4304_8ff9_58b7e5c99b63",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "44",
									ignoreSize = "True",
									name = "Button_join",
									normal = "ui/common/button_small_blue_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 320,
										PositionY = -10,
									},
									UItype = "Button",
									width = "108",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_aply_Button_join_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
											UUID = "70511423_2770_4725_bae8_31633c6fd31c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_aply",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "加入",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "47",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_leagueHallView_1_Panel_league_item_Panel_prefab_Panel-JoinLeagueLayer_Layer1_league_Game",
									UUID = "ba3db916_d1ac_42ac_8d56_912dd881134e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "1",
									ignoreSize = "False",
									name = "Image_leagueHallView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/new_equip/015.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -33,
										PositionY = -14,
									},
									width = "476",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/common/bg_01.png",
			"ui/league/加入社团P2 拷贝.jpg",
			"ui/league/ui_58.png",
			"ui/Equipment/new_ui/new_09.png",
			"ui/common/button09.png",
			"ui/league/ui_55.png",
			"ui/league/ui_59.png",
			"ui/mail/mail_12.png",
			"ui/chat/118.png",
			"ui/common/button_small_blue_n.png",
			"ui/new_equip/015.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

