local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
			UUID = "d3954dd5_5b7d_448b_b346_3b94327278c2",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "ScrollView_map_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
					UUID = "bb92d1f2_4a5b_44f5_932e_f47188625885",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "True",
					bounceEnable = "False",
					classname = "MEScrollView",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					direction = "3",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					innerHeight = "640",
					innerWidth = "1386",
					name = "ScrollView_map",
					showScrollbar = "False",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = -213,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1386",
					ZOrder = "1",
				},
				{
					controlID = "Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
					UUID = "eece7dc8_e712_43db_8fd0_22d253c7060c",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_base",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -88,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_5_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
							UUID = "c97d5ca8_cdaa_4a90_8762_f4f4c644ec9d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/mainLayer/015.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 320,
								LeftPositon = 428,
								TopPosition = 608,
								relativeToName = "Panel",
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
							UUID = "3e80587c_c8d7_4948_95ca_2410d1f8a6ba",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "400",
							ignoreSize = "False",
							name = "Panel_ui",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "400",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_progress_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "61a833e0_126e_47b1_a329_bf321dcba510",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "68",
									ignoreSize = "True",
									name = "Button_progress",
									normal = "ui/activity/activity_2020wsj/mainLayer/010.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 73,
										PositionY = 245,
									},
									UItype = "Button",
									width = "118",
									ZOrder = "1",
								},
								{
									controlID = "Button_rank_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "a9f8da27_0e9c_4576_bdd3_8d22948c8a39",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "70",
									ignoreSize = "True",
									name = "Button_rank",
									normal = "ui/activity/activity_2020wsj/mainLayer/011.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 73,
										PositionY = 145,
									},
									UItype = "Button",
									width = "116",
									ZOrder = "1",
								},
								{
									controlID = "Button_shop_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "8e5919ee_cc9e_4f74_a27d_bbd615f1c161",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "67",
									ignoreSize = "True",
									name = "Button_shop",
									normal = "ui/activity/activity_2020wsj/mainLayer/012.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 73,
										PositionY = 49,
									},
									UItype = "Button",
									width = "117",
									ZOrder = "1",
								},
								{
									controlID = "Image_1_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "ff0712cc_51f3_4d17_b43d_4be9f4029890",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "52",
									ignoreSize = "True",
									name = "Image_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/activity_2020wsj/mainLayer/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 251,
										PositionY = 536,
									},
									width = "473",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_time_tip_Image_1_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "3e1784ea_19e2_4f01_9cfb_d8c5a1bf4d6f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFD4EDFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_time_tip",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "活动结束：",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -167,
											},
											width = "107",
											ZOrder = "1",
										},
										{
											controlID = "Label_time_Image_1_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "56e383ce_b9af_4f7c_b255_39dbb814b6df",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFE3993C",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_time",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "01时00分",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -100,
											},
											width = "98",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "397d5c76_776c_4515_8efd_73962f64ad7a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "289",
									ignoreSize = "True",
									name = "Image_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/activity_2020wsj/mainLayer/002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 988,
										PositionY = 289,
									},
									width = "279",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_show_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "4eec2af2_c772_48d6_906a_dcbc0f2ce202",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "400",
											ignoreSize = "False",
											name = "Panel_show",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "400",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Button_hide_Panel_show_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
													UUID = "4e530b4d_d94d_4c2f_88d5_d160355d62d6",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "60",
													ignoreSize = "True",
													name = "Button_hide",
													normal = "ui/activity/activity_2020wsj/mainLayer/008.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionY = 107,
													},
													UItype = "Button",
													width = "260",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Label_title_Button_hide_Panel_show_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
															UUID = "7b9e4dad_625d_451c_86e1_58b2dec936c0",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFE4EDFF",
															fontName = "font/MFLiHei_Noncommercial.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "28",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "35",
															ignoreSize = "True",
															name = "Label_title",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "异闻探索",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionX = -61,
																PositionY = -2,
															},
															width = "116",
															ZOrder = "1",
														},
														{
															controlID = "Image_arrow_Button_hide_Panel_show_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
															UUID = "47f7de7c_3db9_4f8d_887b_73436463d98f",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															flipY = "True",
															height = "23",
															ignoreSize = "True",
															name = "Image_arrow",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/activity/activity_2020wsj/mainLayer/004.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 100,
																PositionY = -1,
															},
															width = "34",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "ScrollView_buff_Panel_show_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
													UUID = "6dfc7b66_fcfc_4bc1_87bb_cfa576acecd8",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "True",
													bounceEnable = "False",
													classname = "MEScrollView",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													direction = "1",
													dstBlendFunc = "771",
													height = "177",
													ignoreSize = "False",
													innerHeight = "177",
													innerWidth = "264",
													name = "ScrollView_buff",
													showScrollbar = "False",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = -134,
														PositionY = -105,
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "264",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_hide_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "61f1723f_a78d_4b7e_b1f4_648d20177381",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "400",
											ignoreSize = "False",
											name = "Panel_hide",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											visible = "False",
											width = "400",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Button_show_Panel_hide_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
													UUID = "66f8704c_c314_4b2b_a079_153fcbf30a45",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEButton",
													ClickHighLightEnabled = "True",
													dstBlendFunc = "771",
													flipX = "False",
													flipY = "False",
													height = "60",
													ignoreSize = "True",
													name = "Button_show",
													normal = "ui/activity/activity_2020wsj/mainLayer/009.png",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionY = 107,
													},
													UItype = "Button",
													width = "260",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Label_title_Button_show_Panel_hide_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
															UUID = "2cff06bc_ed2f_49d8_b20a_153a870eca00",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FF2B214E",
															fontName = "font/MFLiHei_Noncommercial.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "28",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "35",
															ignoreSize = "True",
															name = "Label_title",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "异闻探索",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionX = -61,
																PositionY = -2,
															},
															width = "116",
															ZOrder = "1",
														},
														{
															controlID = "Image_arrow_Button_show_Panel_hide_Image_2_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
															UUID = "427a81a4_93b5_431a_aa02_39caecde18e5",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "23",
															ignoreSize = "True",
															name = "Image_arrow",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/activity/activity_2020wsj/mainLayer/004.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																PositionX = 100,
																PositionY = -1,
															},
															width = "34",
															ZOrder = "1",
														},
													},
												},
											},
										},
									},
								},
								{
									controlID = "Image_3_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "cb5c5ff1_dcfc_45a4_9393_900a86107e1b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "56",
									ignoreSize = "True",
									name = "Image_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/activity_2020wsj/figthReady/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 982,
										PositionY = 533,
									},
									width = "261",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_2_Image_3_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "cbf86473_90bd_42cb_8d10_af3fedde628e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFD4EDFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "挑战用时：",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -29,
												PositionY = -1,
											},
											width = "99",
											ZOrder = "1",
										},
										{
											controlID = "Label_record_time_Image_3_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "d49cbab4_64cb_4aa1_a2de_558035ac321f",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFE3993C",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_record_time",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "01时00分",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 33,
												PositionY = -1,
											},
											width = "91",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_4_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "91e86d95_62e6_4ad9_9981_d026d58788c0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "56",
									ignoreSize = "True",
									name = "Image_4",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/activity_2020wsj/figthReady/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 981,
										PositionY = 472,
									},
									width = "261",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_3_Image_4_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "990f83fd_a6bb_4660_845c_bcf154fb33f9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFD4EDFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_3",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "当前排名：",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -29,
												PositionY = -1,
											},
											width = "99",
											ZOrder = "1",
										},
										{
											controlID = "Label_rank_Image_4_Panel_ui_Panel_base_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "0ea9565e_b21f_4920_9808_7574510661f5",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFE3993C",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_rank",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "01时00分",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 33,
												PositionY = -1,
											},
											width = "91",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
					UUID = "5d5366aa_c50e_4e93_b052_82a66dbed9f7",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = -640,
						BottomPosition = -640,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
							UUID = "acddb51f_b9b7_4484_9527_a01b69d333ae",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "57",
							ignoreSize = "False",
							name = "Panel_buff_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 588,
								PositionY = 100,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "252",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_finish_Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "3a64a55e_f04d_406b_8e1e_86d642036d23",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "10",
									ignoreSize = "False",
									name = "Panel_finish",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "10",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_bg_Panel_finish_Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "d1f935a4_14b8_4adb_8bda_b7c60d27bbdf",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "50",
											ignoreSize = "True",
											name = "Image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/activity_2020wsj/mainLayer/006.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "252",
											ZOrder = "1",
										},
										{
											controlID = "Label_content_Panel_finish_Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "35944d95_0f63_4dc0_902a_f76a001aaa46",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF441B0D",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_content",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "TextLable",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -114,
											},
											width = "225",
											ZOrder = "1",
										},
										{
											controlID = "Image_flag_Panel_finish_Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "6a8b4611_7cbc_4991_affd_9e8bd010e0cc",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "34",
											ignoreSize = "True",
											name = "Image_flag",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/activity_2020wsj/mainLayer/007.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 99,
											},
											width = "47",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_progress_Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
									UUID = "df26f5a7_036d_49d7_9474_b04e43a43939",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "10",
									ignoreSize = "False",
									name = "Panel_progress",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									visible = "False",
									width = "10",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_bg_Panel_progress_Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "0b228596_9464_4889_bcb4_79dbe0612874",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "50",
											ignoreSize = "True",
											name = "Image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/activity_2020wsj/mainLayer/005.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "252",
											ZOrder = "1",
										},
										{
											controlID = "Label_content_Panel_progress_Panel_buff_item_Panel_prefab_Panel-wsjMainLayer_activity_2020_wsj_activity_Game",
											UUID = "100946c7_b0d5_4390_b447_ec7ca923730f",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFD4EDFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_content",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "TextLable",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -114,
											},
											width = "225",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/activity_2020wsj/mainLayer/015.png",
			"ui/activity/activity_2020wsj/mainLayer/010.png",
			"ui/activity/activity_2020wsj/mainLayer/011.png",
			"ui/activity/activity_2020wsj/mainLayer/012.png",
			"ui/activity/activity_2020wsj/mainLayer/001.png",
			"ui/activity/activity_2020wsj/mainLayer/002.png",
			"ui/activity/activity_2020wsj/mainLayer/008.png",
			"ui/activity/activity_2020wsj/mainLayer/004.png",
			"ui/activity/activity_2020wsj/mainLayer/009.png",
			"ui/activity/activity_2020wsj/figthReady/001.png",
			"ui/activity/activity_2020wsj/mainLayer/006.png",
			"ui/activity/activity_2020wsj/mainLayer/007.png",
			"ui/activity/activity_2020wsj/mainLayer/005.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

