---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/7/14 0014 11:59
---

local DatingStarSettlementView = class("DatingStarSettlementView",BaseLayer)

function DatingStarSettlementView:initData(...)
    self.sMsg = DatingDataMgr:getDatingSettlementMsg()
    self.curScript = clone(DatingDataMgr:getCurDatingScript())
    self.roleId = DatingDataMgr:getDatingRuleRoleId(self.curScript.datingRuleCid) or RoleDataMgr:getCurId()
    self.modelId = DatingDataMgr:getSettlementModel(self.curScript.datingRuleCid) or RoleDataMgr:getModel(self.roleId)

    print("StarSettlementView:initData self.roleId",self.roleId)
    print("StarSettlementView:initData self.modelId",self.modelId)
end

function DatingStarSettlementView:ctor(...)
    self.super.ctor(self)

    self:initData(...)

    self:init("lua.uiconfig.dating.datingStarSettlementView")
end

function DatingStarSettlementView:initUI(ui)
    self.super.initUI(self,ui)

    self.ui = ui

    self:initRole()
    self:initPanelStar()
end

function DatingStarSettlementView:initRole()
    self.Image_npc = TFDirector:getChildByPath(self.ui,"Image_npc")
    self.elvesNpc = ElvesNpcTable:createLive2dNpcID(self.modelId).live2d
    self.elvesNpc:setScale(self.elvesNpc.defaultScale)
    self.Image_npc:getParent():addChild(self.elvesNpc)
    self.elvesNpc:setZOrder(self.Image_npc:getZOrder())
    local pos = self.Image_npc:getPosition() - ccp(0+20,self.Image_npc:getSize().height/2-40)
    self.elvesNpc:setPosition(pos)
    self.Image_npc:setVisible(false)
end

function DatingStarSettlementView:initPanelStar()
    local Panel_star = TFDirector:getChildByPath(self.ui,"Panel_star")
    local starList = self.sMsg.starList or {}
    for i = 1, 3 do
        local Image_star = TFDirector:getChildByPath(Panel_star,"Image_star" .. i)
        local Image_starFinish = TFDirector:getChildByPath(Image_star, "Image_starFinish")
        Image_starFinish:setVisible(starList[i])
        local Label_text = TFDirector:getChildByPath(Image_star, "Label_text")
        local textDesId = DatingDataMgr:getDatingRuleDungeonDateDes(self.curScript.datingRuleCid)[i]
        if textDesId then
            Label_text:setTextById(textDesId)
        else
            Image_star:hide()
        end
    end
end

return DatingStarSettlementView