---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/7/10 0010 18:22
---

local RoleAreaView = class("RoleAreaView", BaseLayer)

function RoleAreaView:initData(callback)
    self.clickAreaList ={}
    self.callback_ = callback
end

function RoleAreaView:ctor(RoleAreaUIName,callback)
    self.super.ctor(self)

    self:initData(callback)
    print("RoleAreaUIName ", RoleAreaUIName)
    local uiPath = string.format("lua.uiconfig.dating.%s",RoleAreaUIName)
    self:init(uiPath)
end

function RoleAreaView:initUI(ui)
    self.super.initUI(self,ui)

    self.ui = ui

    self:initAllClickArea()
end

function RoleAreaView:initAllClickArea()
    local idx = 1
    while(true)do
        local uiName = string.format("Panel_ClickArea%s",idx)
        local Panel_ClickArea = TFDirector:getChildByPath(self.ui, uiName)
        if not Panel_ClickArea then
            break
        end
        table.insert(self.clickAreaList, Panel_ClickArea)
        idx = idx + 1
    end

end

function RoleAreaView:onClick(clickArea)
    local jumpId = clickArea.UIEditorData.jumpId
    self.callback_(jumpId)
end

function RoleAreaView:registerEvents()
    for i, v in ipairs(self.clickAreaList) do
        v:Touchable(true)
        v:onClick(function()
            self:onClick(v)
        end)
    end
end

return RoleAreaView