---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/7/25 0025 15:49
---

local RoleShowView = class("RoleShowView",BaseLayer)


function RoleShowView:initData()

end

function RoleShowView:ctor(data)
    self.super.ctor(self)

    self:initData(data)
    self:init("lua.uiconfig.role.roleShowView")
end

function RoleShowView:initUI(ui)
    self.super.initUI(self,ui)

    self.ui = ui

    self.Panel_base = TFDirector:getChildByPath(self.ui, "Panel_base")

    self:initBtns()
end

function RoleShowView:updateRole()
    self.roleId = RoleDataMgr:getUseId()
    local modelId = RoleDataMgr:getModel(self.roleId)
    if self.elvesNpc then
        self.elvesNpc:removeFromParent()
    end
    self.elvesNpc = ElvesNpcTable:createLive2dNpcID(modelId,false,false).live2d

    self.Panel_base:addChild(self.elvesNpc,100)

    self.elvesNpc:setScale(0.7)
    local pos = ccp(self.Panel_base:Size().width/2,-100)
    self.elvesNpc:Pos(pos)

    self.elvesNpc:show()
    self.elvesNpc:setZOrder(-1)
    self.ui:timeOut(function()
        self.elvesNpc:playIn(0.3)
        self.elvesNpc:setZOrder(1)
    end,0)
end

function RoleShowView:initBtns()
    self.Button_change = TFDirector:getChildByPath(self.ui, "Button_change")
    self.Button_dress = TFDirector:getChildByPath(self.ui, "Button_dress")
end

function RoleShowView:showDressView(dressIds)
    Utils:openView("dating.DressView")
end

function RoleShowView:showKanBanView(dressIds)
    Utils:openView("role.RoleListView")
    
    ----好感度升级测试代码
    --local data = {}
    --data.lastLevel = 1
    --data.newLevel = 2
    --local favorUpgradeLayer = require("lua.logic.dating.FavorUpgradeLayer"):new(data)
    --AlertManager:addLayer(favorUpgradeLayer,AlertManager.BLOCK,AlertManager.TWEEN_NONE)
    --AlertManager:show()

    self:hideUI()
end

function RoleShowView:hideUI()
    self.Button_change:hide()
    self.Button_dress:hide()
end

function RoleShowView:showUI()
    self.Button_change:show()
    self.Button_dress:show()
end


function RoleShowView:registerEvents()

    --EventMgr:addEventListener(self,EV_SHOW_KANBAN,handler(self.showRoleList, self))
    --EventMgr:addEventListener(self,EV_HIDE_KANBAN,handler(self.hideRoleList, self))
    --EventMgr:addEventListener(self,EV_KANBAN_CHANGE_SHOW_ONE,handler(self.changeShowOne, self))
    --EventMgr:addEventListener(self,EV_KANBAN_SWITCH_SHOW_ONE,handler(self.switchShowOne, self))

    self.Button_change:onClick(function()
        self:showKanBanView()
    end)

    self.Button_dress:onClick(function()
        self:showDressView()
    end)
end

function RoleShowView:onShow()
    --self.super.onShow(self)
    self.super.onShow(self)
    self:updateRole()
    self:showUI()
end

function RoleShowView:onHide()
    self.super.onHide(self)

    if self.elvesNpc then
        self.elvesNpc:removeFromParent();
        self.elvesNpc = nil;
    end
end

return RoleShowView
