local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
			UUID = "92c57ec0_479e_4abf_a3f6_3de4a86fb6f2",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
					UUID = "b77ea98d_22f4_4b90_9c2b_e89656eafd98",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "35",
					sizepercenty = "62",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_content_Panel_root_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
							UUID = "8bd81775_084b_4af5_9f02_151b0c648758",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "336",
							ignoreSize = "True",
							name = "Image_content",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/hwx/pop/016.png",
							touchAble = "True",
							UILayoutViewModel = 
							{
								
							},
							width = "552",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_title_Image_content_Panel_root_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "4b3dc5e5_8ebe_4531_bf97_10fd0df0d963",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3C5AB7",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "Label_title",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "弹窗小型",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -253,
										PositionY = 128,
									},
									width = "114",
									ZOrder = "1",
								},
								{
									controlID = "Label_title_en_Image_content_Panel_root_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "52d175d4_c108_4966_800d_b5a46ebd5577",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3C5AB7",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "15",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "17",
									ignoreSize = "True",
									name = "Label_title_en",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Infomation Create",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -77,
										PositionY = 121,
									},
									width = "115",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_content_Image_content_Panel_root_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "48f2c60c_ade3_48fc_949c_d3f2b47c9da8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "True",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "250",
									ignoreSize = "False",
									innerHeight = "250",
									innerWidth = "515",
									name = "ScrollView_content",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -21,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "515",
									ZOrder = "1",
								},
								{
									controlID = "Button_close_Image_content_Panel_root_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "acdff176_0c10_4ca4_82df_4d9af5beac30",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "50",
									ignoreSize = "True",
									name = "Button_close",
									normal = "ui/hwx/pop/008.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 237,
										PositionY = 132,
									},
									UItype = "Button",
									width = "50",
									ZOrder = "1",
								},
								{
									controlID = "Label_title_line_Image_content_Panel_root_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "80b4a308_3e0b_48b1_9305_1e31f4835902",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3C5AB7",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "30",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "37",
									ignoreSize = "True",
									name = "Label_title_line",
									nTextAlign = "1",
									nTextHAlign = "1",
									scaleX = "0.2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "|",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -137,
										PositionY = 127,
									},
									width = "11",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
					UUID = "8195da1a_675e_4571_933c_d4505022a27c",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "35",
					sizepercenty = "62",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 587,
						PositionY = -418,
						LeftPositon = 19,
						TopPosition = 738,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
							UUID = "6c2fe46d_0ea1_4f2e_92cd_3f24db09d5f5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "85",
							ignoreSize = "False",
							name = "Panel_countItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -48,
								PositionY = 97,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "513",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_unlock_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "d261f917_5632_4e87_ac4a_f256e351c9a4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:200;capInsetsY:28;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "80",
									ignoreSize = "False",
									name = "Button_unlock",
									normal = "ui/hwx/pop/017.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										
									},
									UItype = "Button",
									width = "513",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_icon_Button_unlock_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
											UUID = "68e0e867_917a_423d_b793_2ee92598e0ae",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "60",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/hwx/pop/019.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -210,
											},
											width = "60",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_lock_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "e88ff717_eb7b_48ff_b921_e61aadd76940",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "True",
									name = "Image_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/hwx/pop/018.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "514",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon2_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "fea4897a_0307_45d4_ad49_6c17d3ac7567",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "True",
									name = "Image_icon2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/hwx/pop/020.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -124,
										PositionY = -18,
									},
									width = "90",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "9c08c7b9_9fc4_4bc7_8528_f6b12ad39035",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -210,
									},
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "Label_cost_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "d4866330_67ad_4dd6_8d97_9e6d2adcdc27",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_cost",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "消耗-30",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -171,
										PositionY = 20,
									},
									width = "77",
									ZOrder = "1",
								},
								{
									controlID = "Image_star_1_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "f182e623_4785_45f2_bbd0_18457a25e6ec",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "18",
									ignoreSize = "True",
									name = "Image_star_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/hwx/map/023.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -157,
										PositionY = -17,
									},
									width = "20",
									ZOrder = "1",
								},
								{
									controlID = "Image_star_2_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "8650b276_6ba3_4391_8293_43cff4975dcc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "18",
									ignoreSize = "True",
									name = "Image_star_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/hwx/map/023.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -145,
										PositionY = -17,
									},
									width = "20",
									ZOrder = "1",
								},
								{
									controlID = "Image_star_3_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "ad1d200f_24ed_4c3f_8863_1a2523a27113",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "18",
									ignoreSize = "True",
									name = "Image_star_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/hwx/map/023.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -133,
										PositionY = -17,
									},
									width = "20",
									ZOrder = "1",
								},
								{
									controlID = "Label_unlock_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "0cb6fe63_4f7a_4ebd_bf8f_380939a40b5a",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF39425E",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_unlock",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "解锁",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -124,
										PositionY = -18,
									},
									width = "43",
									ZOrder = "1",
								},
								{
									controlID = "Label_info_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "a3a0e115_bc16_4f4a_9554_9606bf3a683b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_info",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "挑战次数",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -6,
										PositionY = 16,
									},
									width = "83",
									ZOrder = "1",
								},
								{
									controlID = "Label_count_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "e74eaa8e_9294_4ac5_aa14_cc623aeb261a",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_count",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "-1",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 78,
										PositionY = 16,
									},
									width = "26",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "5b85a92f_ac65_4210_b43e_4746289fc2df",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_desc",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "5",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 84,
										PositionY = -17,
									},
									width = "22",
									ZOrder = "1",
								},
								{
									controlID = "Image_split_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "df9592c2_e58c_4bf8_bd51_ce0039bb94d2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "52",
									ignoreSize = "True",
									name = "Image_split",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/hwx/pop/031.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -14,
									},
									width = "2",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc1_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "e16ba859_5aa5_4c48_b511_1e55699d9bc5",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_desc1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "1次性获得",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -7,
										PositionY = -17,
									},
									width = "90",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc2_Panel_countItem_Panel_prefab_Panel-fubenSelectCountView_Layer1_linkageHwx_Game",
									UUID = "632a3669_2af8_48dc_830d_7214fcae987e",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_desc2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "次战斗的奖励",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 109,
										PositionY = -17,
									},
									width = "123",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/hwx/pop/016.png",
			"ui/hwx/pop/008.png",
			"ui/hwx/pop/017.png",
			"ui/hwx/pop/019.png",
			"ui/hwx/pop/018.png",
			"ui/hwx/pop/020.png",
			"ui/hwx/map/023.png",
			"ui/hwx/pop/031.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

