local t = {
		{
			name="celebrationView",
			ui ="celebrationView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="welfareView",
			ui ="welfareView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="addressView",
			ui ="addressView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="celebrationRuleView",
			ui ="celebrationRuleView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="LuckyListView",
			ui ="LuckyListView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="welfareRecordView",
			ui ="welfareRecordView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="welfareScanView",
			ui ="welfareScanView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="addressConfirmView",
			ui ="addressConfirmView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="celebrationLuckyTipView",
			ui ="celebrationLuckyTipView.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
		{
			name="celebrationView1",
			ui ="celebrationView1.lua",
			x=0,
			y=0,
			speed=0,
			layer="oneYear",
			canLoad=true,
			logic="",
		},
}
return t
