local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
			UUID = "0ad8889d_7484_417f_8ec9_e629eb00c315",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
					UUID = "de9adc7a_7ddc_49db_a9d4_7993b673a2dc",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_base",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
							UUID = "2265a369_4b2c_4524_84e0_96ceaa78b9cf",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "503",
							ignoreSize = "False",
							name = "Panel_content",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 299,
								IsPercent = true,
								PercentX = 50,
								PercentY = 46.72,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1008",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg1_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
									UUID = "5c3fbbef_7f59_4710_ac02_8a021ef734c4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "517",
									ignoreSize = "False",
									name = "Image_bg1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/help/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "1020",
									ZOrder = "1",
								},
								{
									controlID = "Image_bg2_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
									UUID = "e2e9b946_9bf8_495e_8d27_7705017b5806",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "166",
									ignoreSize = "True",
									name = "Image_bg2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/help/002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -443,
										PositionY = -147,
									},
									width = "52",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_helpView_1_Image_bg2_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "58f4369c_9cd7_4087_a9d6_20c84e6eb393",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF457278",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_helpView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											rotation = "90",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Ririko",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 4,
												PositionY = -1,
											},
											width = "70",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_close_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
									UUID = "2628a9c9_62c0_4965_96a8_1f98e47bf3ed",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "60",
									ignoreSize = "True",
									name = "Button_close",
									normal = "ui/common/pop_ui/pop_btn_02.png",
									pressed = "ui/common/pop_ui/pop_btn_02.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 479,
										PositionY = 220,
									},
									UItype = "Button",
									width = "60",
									ZOrder = "1",
								},
								{
									controlID = "Panel_info_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
									UUID = "4a19a165_b2cc_47f1_b01b_8009c34553f0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "503",
									ignoreSize = "False",
									name = "Panel_info",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -504,
										PositionY = -252,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "1008",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_tittle_Panel_info_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "c7698d60_df10_40ff_b070_5c532d3b9638",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFCFE6F7",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "90",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_tittle",
											nTextAlign = "2",
											nTextHAlign = "2",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 791,
												PositionY = -10,
											},
											width = "200",
											ZOrder = "1",
										},
										{
											controlID = "Panel_page_Panel_info_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "9c45263c_3c46_43d5_91f4_962b6e36eac6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "25",
											ignoreSize = "False",
											name = "Panel_page",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 504,
												PositionY = 73,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "150",
											ZOrder = "1",
										},
										{
											controlID = "PageView_item_Panel_info_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "d393423f_f507_4d55_a542_07e5efe832a2",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEPageView",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "417",
											ignoreSize = "False",
											name = "PageView_item",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 363,
												PositionY = 24,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "625",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_list_Panel_info_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "c7e45a87_fe8d_4917_8bfa_293cf4eb1934",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "False",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "1",
											dstBlendFunc = "771",
											height = "417",
											ignoreSize = "False",
											innerHeight = "417",
											innerWidth = "625",
											name = "ScrollView_list",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 363,
												PositionY = 24,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "625",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
									UUID = "34c716c8_5fe2_41af_a51f_7abe8ccf4a32",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "455",
									ignoreSize = "False",
									name = "Panel_help_item",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -141,
										PositionY = -264,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "625",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_flag1_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "e40259a3_ef25_4c80_94a9_27637e872c6a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "32",
											ignoreSize = "True",
											name = "Image_flag1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/teampve/help/01.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 30,
												PositionY = 436,
											},
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "title1_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "7af3dac1_d8d9_4384_be29_a5aa497cefc6",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF49557F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "28",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "title1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Vista previa de recompensa",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 60,
												PositionY = 467,
											},
											width = "375",
											ZOrder = "1",
										},
										{
											controlID = "title2_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "210eaf1a_677a_4d6d_a501_d46c17f371df",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF49557F",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "28",
											ignoreSize = "True",
											name = "title2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "(Unirse al desafío como miembro)",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 60,
												PositionY = 437,
											},
											width = "401",
											ZOrder = "1",
										},
										{
											controlID = "target1_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "0291dc5e_9fd0_44e9_8a80_739297cfae4f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "57",
											ignoreSize = "False",
											name = "target1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/teampve/help/11.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 308,
												PositionY = 382,
											},
											visible = "False",
											width = "589",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "image_flag_target1_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "44cbf7a4_8527_456d_9cad_306f14321175",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "18",
													ignoreSize = "True",
													name = "image_flag",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/teampve/help/14.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 286,
														PositionY = 21,
													},
													width = "18",
													ZOrder = "1",
												},
												{
													controlID = "targetContent_target1_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "44256f43_b5a7_4793_a2ad_cb94b0d50957",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "targetContent",
													nTextAlign = "0",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Recompensa de líder del equipo",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -274,
													},
													width = "430",
													ZOrder = "1",
												},
												{
													controlID = "labelCount_target1_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "551b1f1e_d43a_40da_9880_dd48f3547f27",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "28",
													ignoreSize = "True",
													name = "labelCount",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "4 255",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 228,
													},
													width = "62",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "target2_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "8c7b98c9_0df8_4db3_bf38_d7edf1f7e590",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "57",
											ignoreSize = "False",
											name = "target2",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/teampve/help/11.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 308,
												PositionY = 313,
											},
											visible = "False",
											width = "589",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "image_flag_target2_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "d92abb4c_5f22_480e_83ab_f464326e717a",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "18",
													ignoreSize = "True",
													name = "image_flag",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/teampve/help/14.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 286,
														PositionY = 21,
													},
													width = "18",
													ZOrder = "1",
												},
												{
													controlID = "targetContent_target2_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "ab49da85_0f9b_4cfc_a563_1c048454ef83",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "targetContent",
													nTextAlign = "0",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Recompensa de líder del equipo",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -274,
													},
													width = "430",
													ZOrder = "1",
												},
												{
													controlID = "labelCount_target2_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "19c2b44c_d06a_431f_a375_5012cdc4894a",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "28",
													ignoreSize = "True",
													name = "labelCount",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "4 255",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 228,
													},
													width = "62",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "target3_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "2e3927cc_1fd4_4233_aa8a_55f3323581d6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "57",
											ignoreSize = "False",
											name = "target3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/teampve/help/11.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 308,
												PositionY = 242,
											},
											visible = "False",
											width = "589",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "image_flag_target3_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "c146c88a_cac7_4df5_bae1_f40f7defe131",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "18",
													ignoreSize = "True",
													name = "image_flag",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/teampve/help/14.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 286,
														PositionY = 21,
													},
													width = "18",
													ZOrder = "1",
												},
												{
													controlID = "targetContent_target3_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "43bb8a60_23bb_4491_be41_4b6bb0055c9b",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "targetContent",
													nTextAlign = "0",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Recompensa de líder del equipo",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -274,
													},
													width = "430",
													ZOrder = "1",
												},
												{
													controlID = "labelCount_target3_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "81d0bcb4_37a4_41db_a8cf_d2f190e90a52",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "28",
													ignoreSize = "True",
													name = "labelCount",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "4 255",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 228,
													},
													width = "62",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "target4_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "1c78c91d_8c77_4c6f_9603_919ac13aa380",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "57",
											ignoreSize = "False",
											name = "target4",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/teampve/help/11.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 308,
												PositionY = 172,
											},
											visible = "False",
											width = "589",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "image_flag_target4_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "d729ad75_0fbb_4c40_b185_de8e99f845ce",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "18",
													ignoreSize = "True",
													name = "image_flag",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/teampve/help/14.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 286,
														PositionY = 21,
													},
													width = "18",
													ZOrder = "1",
												},
												{
													controlID = "targetContent_target4_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "aa60aa1f_01c8_4235_a624_227f31a4e0ea",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "targetContent",
													nTextAlign = "0",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Recompensa de líder del equipo",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -274,
													},
													width = "430",
													ZOrder = "1",
												},
												{
													controlID = "labelCount_target4_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "da1aa63d_02e8_4ee7_a2ab_db9c4a906303",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "28",
													ignoreSize = "True",
													name = "labelCount",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "4 255",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 228,
													},
													width = "62",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "target5_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
											UUID = "a53fba52_8442_4667_a7c8_0f6f28e13d4c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "57",
											ignoreSize = "False",
											name = "target5",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/teampve/help/11.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 308,
												PositionY = 102,
											},
											visible = "False",
											width = "589",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "image_flag_target5_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "b48b154f_63de_4838_a28f_3ec2aa48fadd",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "18",
													ignoreSize = "True",
													name = "image_flag",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/teampve/help/14.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 286,
														PositionY = 21,
													},
													width = "18",
													ZOrder = "1",
												},
												{
													controlID = "targetContent_target5_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "1cc513fb_c33e_4f27_82a3_a4c9f77b303b",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "targetContent",
													nTextAlign = "0",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Recompensa de líder del equipo",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -274,
													},
													width = "430",
													ZOrder = "1",
												},
												{
													controlID = "labelCount_target5_Panel_help_item_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
													UUID = "9d5fbf7c_7769_440a_9bef_a10101471cd2",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF49557F",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "28",
													ignoreSize = "True",
													name = "labelCount",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "4 255",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 228,
													},
													width = "62",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "ScrollView_help_Panel_content_Panel_base_Panel-HuntingInvitationCountHelpView_entrance_osd_Game",
									UUID = "d9816738_69cd_4f91_a606_46d2c35420ef",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "350",
									ignoreSize = "False",
									innerHeight = "350",
									innerWidth = "589",
									name = "ScrollView_help",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -125,
										PositionY = -200,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "589",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/common/help/001.png",
			"ui/common/help/002.png",
			"ui/common/pop_ui/pop_btn_02.png",
			"ui/teampve/help/01.png",
			"ui/teampve/help/11.png",
			"ui/teampve/help/14.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

