local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-activityMainView6_activityStyleModel_activity_Game",
			UUID = "6e7b095d_d7f4_48ae_9186_a43e57e59df2",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-activityMainView6_activityStyleModel_activity_Game",
					UUID = "b80949bd_4dd2_4bd7_9909_546310673736",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 446,
						PositionY = 354,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-activityMainView6_activityStyleModel_activity_Game",
							UUID = "dbd78ca9_0c22_49ec_8af9_6c5890559fff",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/assist/kuangsan/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								LeftPositon = 536,
								TopPosition = 288,
								relativeToName = "Panel",
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Panel_activity_Panel_root_Panel-activityMainView6_activityStyleModel_activity_Game",
							UUID = "05b739ad_a96a_4c60_8393_32675702f982",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "548",
							ignoreSize = "False",
							name = "Panel_activity",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 102,
								PositionY = -35,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "924",
							ZOrder = "1",
						},
						{
							controlID = "ScrollView_activity_Panel_root_Panel-activityMainView6_activityStyleModel_activity_Game",
							UUID = "5f56cd08_dfd2_4d0e_b02d_2d6a908a4b32",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "True",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "1",
							dstBlendFunc = "771",
							height = "550",
							ignoreSize = "False",
							innerHeight = "550",
							innerWidth = "212",
							name = "ScrollView_activity",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -570,
								PositionY = -42,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "212",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
					UUID = "aa00498e_af64_4004_802a_94a1753bac72",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 561,
						PositionY = -286,
						LeftPositon = -7,
						TopPosition = 675,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 2,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
							UUID = "544f8ea2_fc7f_4294_8fbf_fd05c34cd482",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFFA500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "70",
							ignoreSize = "False",
							name = "Panel_activityItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -680,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "205",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
									UUID = "ec9f5630_5178_4fa7_9bb6_732afc4b8f57",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "78",
									ignoreSize = "True",
									name = "ImageNormal",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/assist/kuangsan/btn_1n.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = -1,
									},
									width = "78",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_item_bg_ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
											UUID = "715b69b4_7b7e_45f1_8481_0525a8e8befa",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "70",
											ignoreSize = "True",
											name = "Image_item_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/assist/kuangsan/041.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 66,
												PositionY = 3,
											},
											width = "200",
											ZOrder = "-1",
										},
										{
											controlID = "activityName_ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
											UUID = "776218db_93a5_48e7_b0ec_f61601b46390",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFA6A7",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "activityName",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "禮包商店",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 142,
											},
											width = "91",
											ZOrder = "1",
										},
										{
											controlID = "Image_new_ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
											UUID = "01346fd7_7ded_41bb_88fd_e32790672f83",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "30",
											ignoreSize = "True",
											name = "Image_new",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/news_small.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 18,
												PositionY = 12,
											},
											width = "30",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
									UUID = "02fb0965_aca9_4650_b2ba_b1d37fafbcdd",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "78",
									ignoreSize = "True",
									name = "ImageSelect",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/assist/kuangsan/btn_1s.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -50,
										PositionY = -2,
									},
									width = "78",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_item_bg_ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
											UUID = "171ebaf9_3272_49cf_a021_30c8ad18c762",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "70",
											ignoreSize = "True",
											name = "Image_item_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/assist/kuangsan/040.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 53,
												PositionY = 2,
											},
											width = "200",
											ZOrder = "-1",
										},
										{
											controlID = "activityName_ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
											UUID = "5e9ac65d_cef1_4c34_bb82_9aa1d6cb30ff",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "activityName",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "禮包商店",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 139,
											},
											width = "91",
											ZOrder = "1",
										},
										{
											controlID = "Image_new_ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
											UUID = "e4f17ff1_a0d0_4948_8154_6b5e88e4a43f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "30",
											ignoreSize = "True",
											name = "Image_new",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/news_small.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 16,
												PositionY = 13,
											},
											width = "30",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_line_Panel_activityItem_Panel_prefab_Panel-activityMainView6_activityStyleModel_activity_Game",
									UUID = "24fc5322_58e7_48e5_a49f_35762613f03b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "2",
									ignoreSize = "True",
									name = "Image_line",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/assist/kuangsan/039.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -35,
									},
									width = "116",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/assist/kuangsan/bg.png",
			"ui/activity/assist/kuangsan/btn_1n.png",
			"ui/activity/assist/kuangsan/041.png",
			"ui/common/news_small.png",
			"ui/activity/assist/kuangsan/btn_1s.png",
			"ui/activity/assist/kuangsan/040.png",
			"ui/activity/assist/kuangsan/039.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

