local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-activityMainView1001_fanshiAssist_activity_Game",
			UUID = "a550d939_7d21_4243_9458_b844cb01b47c",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-activityMainView1001_fanshiAssist_activity_Game",
					UUID = "3b88298c_9925_4ac7_8678_3a0dbae3aec6",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 446,
						PositionY = 354,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-activityMainView1001_fanshiAssist_activity_Game",
							UUID = "791593cc_a106_4e0b_8efb_ca0e811cfacf",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui/activity/fanshiAssist/fanshiMainView/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								LeftPositon = 536,
								TopPosition = 288,
								relativeToName = "Panel",
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Panel_activity_Panel_root_Panel-activityMainView1001_fanshiAssist_activity_Game",
							UUID = "947ab57c_33b8_4d91_be3d_8e56bd82fcf8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "548",
							ignoreSize = "False",
							name = "Panel_activity",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 102,
								PositionY = -35,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "924",
							ZOrder = "1",
						},
						{
							controlID = "ScrollView_activity_Panel_root_Panel-activityMainView1001_fanshiAssist_activity_Game",
							UUID = "3fc2ee96_bcad_4317_afd7_c619c9918bac",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "True",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "1",
							dstBlendFunc = "771",
							height = "550",
							ignoreSize = "False",
							innerHeight = "550",
							innerWidth = "212",
							name = "ScrollView_activity",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -570,
								PositionY = -42,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "212",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
					UUID = "cacb644b_daf7_4777_b929_85687a503c37",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 561,
						PositionY = -286,
						LeftPositon = -7,
						TopPosition = 675,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 2,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
							UUID = "7dc4d6b6_77b9_4bb9_99be_ec29d8251d79",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFFA500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "70",
							ignoreSize = "False",
							name = "Panel_activityItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -680,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "205",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
									UUID = "e14d2f2b_b12b_41cf_82fc_03ac5eb90744",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "ImageNormal",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/fanshiAssist/fanshiMainView/btn_1n.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 37,
										PositionY = 34,
									},
									width = "64",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_item_bg_ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
											UUID = "e7583223_13ed_4ba3_8cc6_ee1a6231771c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "70",
											ignoreSize = "True",
											name = "Image_item_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/fanshiAssist/fanshiMainView/02.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 66,
												PositionY = 3,
											},
											width = "200",
											ZOrder = "-1",
										},
										{
											controlID = "activityName_ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
											UUID = "bb39bec3_9d20_4254_9961_cad80c049ac5",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFADD8E6",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "activityName",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "禮包商店",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 134,
											},
											width = "82",
											ZOrder = "1",
										},
										{
											controlID = "Image_new_ImageNormal_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
											UUID = "0f547f4d_e0ab_46b8_a2b6_613586f0d62a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "30",
											ignoreSize = "True",
											name = "Image_new",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/news_small.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 18,
												PositionY = 12,
											},
											width = "30",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
									UUID = "f80d07dd_6cfe_43a4_8d1e_debc00b6ca4a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "ImageSelect",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/fanshiAssist/fanshiMainView/btn_1s.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 37,
										PositionY = 34,
									},
									width = "64",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_item_bg_ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
											UUID = "9c2aa1eb_01b2_41cc_b45e_1da63741000d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "70",
											ignoreSize = "True",
											name = "Image_item_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/fanshiAssist/fanshiMainView/01.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 53,
												PositionY = 2,
											},
											width = "176",
											ZOrder = "-1",
										},
										{
											controlID = "activityName_ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
											UUID = "f0a02f2b_e3be_4708_900a_c0d8047ff8d4",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "activityName",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "禮包商店",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 131,
											},
											width = "82",
											ZOrder = "1",
										},
										{
											controlID = "Image_new_ImageSelect_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
											UUID = "147f829b_d1aa_4e2e_a062_0e10d15906bd",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "30",
											ignoreSize = "True",
											name = "Image_new",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/news_small.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 16,
												PositionY = 13,
											},
											width = "30",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_line_Panel_activityItem_Panel_prefab_Panel-activityMainView1001_fanshiAssist_activity_Game",
									UUID = "87a49a51_6017_4d7c_a8cf_c297574c0b9a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "1",
									ignoreSize = "True",
									name = "Image_line",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/fanshiAssist/fanshiMainView/03.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 102,
									},
									width = "116",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/fanshiAssist/fanshiMainView/bg.png",
			"ui/activity/fanshiAssist/fanshiMainView/btn_1n.png",
			"ui/activity/fanshiAssist/fanshiMainView/02.png",
			"ui/common/news_small.png",
			"ui/activity/fanshiAssist/fanshiMainView/btn_1s.png",
			"ui/activity/fanshiAssist/fanshiMainView/01.png",
			"ui/activity/fanshiAssist/fanshiMainView/03.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

