local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-MainEntryView_groupPurchase_activity_Game",
			UUID = "19b40972_0df7_4762_9dd8_3bb564e6bd6f",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
					UUID = "40c878cb_28ab_4691_ba1b_28cf48ee7b7b",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "touchmask_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "0b3f35a7_10b2_4f3b_b7ff_fbfed9f8f0c5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "547",
							ignoreSize = "False",
							name = "touchmask",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "891",
							ZOrder = "1",
						},
						{
							controlID = "bg_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "c3615356_0a1d_4193_9e9c_e1ccbb2f644e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "547",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/groupPurchase/main_5.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "891",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Title_bg_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "43be1d82_b71b_452d_ae12_145c157aa7c0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "158",
									ignoreSize = "True",
									name = "Title",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/groupPurchase/main_3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 243,
										PositionY = 192,
									},
									width = "384",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_try_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "e3815dce_4835_402b_b836_c4427102294e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Button_try",
							normal = "ui/activity/groupPurchase/main_1.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 89,
								PositionY = -225,
							},
							UItype = "Button",
							visible = "False",
							width = "214",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "label_Button_try_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "bfa42485_5ca0_4fde_a365_f4401e87e8c0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "label",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "试  穿",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "70",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_purchase_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "cf0e2e4d_632a_4d39_ac33_8659cbcbdd5c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Button_purchase",
							normal = "ui/activity/groupPurchase/main_2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 320,
								PositionY = -225,
							},
							UItype = "Button",
							width = "214",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "label_Button_purchase_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "c42556a9_be5c_46a4_bf97_50295f3621a6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "label",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "采 购",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 59,
									},
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "coin_Button_purchase_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "a22f4f9f_842c_4f16_a488_5785529ec107",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "coin",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -77,
									},
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "price_Button_purchase_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "b5471466_1aef_4193_aa59_3f2f0249b4c0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "price",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "666",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -56,
									},
									width = "65",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "DesBg_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "2be653b2_8a1a_46e5_b75d_7ae798e1d2ba",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "30",
							ignoreSize = "True",
							name = "DesBg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/groupPurchase/main_4.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -251,
								PositionY = -211,
							},
							width = "343",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Descript_DesBg_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "81a5dbf1_94ba_4e9c_acde_baad8c97382d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "18",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF7E3EA6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Descript",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "时装周期间集齐三人即可优惠采购当前新品哦",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -181,
									},
									width = "364",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "ActivityTime_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "af02d851_03f1_48f8_b6ac_f5dedd1a573c",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "18",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF7E3EA6",
								StrokeSize = 1,
							},
							height = "24",
							ignoreSize = "True",
							name = "ActivityTime",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "活动时间:",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -432,
								PositionY = -245,
							},
							width = "80",
							ZOrder = "1",
						},
						{
							controlID = "giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "5fdcac48_20bf_41fb_83d2_f9043aeadb5a",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "False",
							name = "giftNode",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 127,
								PositionY = -5,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "300",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "5924d14c_fc42_41f8_bf98_8ce7052ce366",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "gift1",
									scaleX = "0.9",
									scaleY = "0.9",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 82,
										PositionY = 26,
									},
									width = "64",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "itemPos_gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "635b4092_2ad7_4056_b2b6_b7905bf02986",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "400",
											ignoreSize = "False",
											name = "itemPos",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "400",
											ZOrder = "1",
										},
										{
											controlID = "touchmask_gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "d192fae3_034b_4666_b671_500ba49fb544",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "80",
											ignoreSize = "False",
											name = "touchmask",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -40,
												PositionY = -40,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "80",
											ZOrder = "1",
										},
										{
											controlID = "selected_gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "f547a106_b040_4ab5_9cf8_c482e8307b7a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "132",
											ignoreSize = "True",
											name = "selected",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "132",
											ZOrder = "1",
										},
										{
											controlID = "get_gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "fa5733c8_9b3a_42e7_8d34_63cf82885d37",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "34",
											ignoreSize = "True",
											name = "get",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/groupPurchase/canget.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "107",
											ZOrder = "1",
										},
										{
											controlID = "finish_gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "e9127ac7_6611_4eb0_8174_3105d27d276c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "34",
											ignoreSize = "True",
											name = "finish",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/groupPurchase/hasget.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "107",
											ZOrder = "1",
										},
										{
											controlID = "saleTag_gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "7a1cda50_7527_49b1_9f80_663562637e4b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "65",
											ignoreSize = "True",
											name = "saleTag",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/recharge/tokenPopView/sale.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 19,
												PositionY = 70,
											},
											width = "97",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "discountScale_saleTag_gift1_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
													UUID = "d9cc0db8_4aa4_417c_af0b_60be637690b8",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "discountScale",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "9折",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionY = 13,
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "a0e22e40_3e92_4284_8db8_7e44d74acbbe",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "gift2",
									scaleX = "0.9",
									scaleY = "0.9",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 211,
										PositionY = 26,
									},
									width = "64",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "itemPos_gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "78868954_9156_4180_a2eb_de6a1ab4adb4",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "400",
											ignoreSize = "False",
											name = "itemPos",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "400",
											ZOrder = "1",
										},
										{
											controlID = "touchmask_gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "919f6410_e0b2_457f_ac8d_ae5638504261",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "80",
											ignoreSize = "False",
											name = "touchmask",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -40,
												PositionY = -40,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "80",
											ZOrder = "1",
										},
										{
											controlID = "selected_gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "14c18ebe_8ee6_403c_8e1b_b55c6a77dcdd",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "132",
											ignoreSize = "True",
											name = "selected",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "132",
											ZOrder = "1",
										},
										{
											controlID = "get_gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "58ee3f1c_7500_4d80_b727_e8c0a12ae43c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "34",
											ignoreSize = "True",
											name = "get",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/groupPurchase/canget.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											visible = "False",
											width = "107",
											ZOrder = "1",
										},
										{
											controlID = "finish_gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "ca47a438_4821_4184_9a0b_f8fed16d6413",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "34",
											ignoreSize = "True",
											name = "finish",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/groupPurchase/hasget.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = -1,
											},
											width = "107",
											ZOrder = "1",
										},
										{
											controlID = "saleTag_gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
											UUID = "8582946a_cf20_4c49_9b4e_8483fdf27163",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "65",
											ignoreSize = "True",
											name = "saleTag",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/recharge/tokenPopView/sale.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 26,
												PositionY = 67,
											},
											width = "97",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "discountScale_saleTag_gift2_giftNode_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
													UUID = "083da3a1_4606_491c_b41a_244ccb36ea25",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "discountScale",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "9折",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionY = 13,
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
						{
							controlID = "help_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "60e53419_cbc5_4ccc_bfb5_dfec924bc490",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "46",
							ignoreSize = "True",
							name = "help",
							normal = "ui/activity/activity_score/005.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -407,
								PositionY = 235,
							},
							UItype = "Button",
							width = "46",
							ZOrder = "1",
						},
						{
							controlID = "Button_check_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
							UUID = "374c9ca5_713f_4eb5_ae4f_4afc0b07fd33",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Button_check",
							normal = "ui/activity/groupPurchase/main_1.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 89,
								PositionY = -225,
							},
							UItype = "Button",
							width = "214",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "label_Button_check_Panel_root_Panel-MainEntryView_groupPurchase_activity_Game",
									UUID = "0b320092_99e2_45e3_b344_4d4b62455920",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "label",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "查 看",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "65",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/groupPurchase/main_5.png",
			"ui/activity/groupPurchase/main_3.png",
			"ui/activity/groupPurchase/main_1.png",
			"ui/activity/groupPurchase/main_2.png",
			"ui/activity/groupPurchase/main_4.png",
			"ui/common/select.png",
			"ui/activity/groupPurchase/canget.png",
			"ui/activity/groupPurchase/hasget.png",
			"ui/recharge/tokenPopView/sale.png",
			"ui/activity/activity_score/005.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

