local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
			UUID = "2b22facb_eeee_4957_9fd7_a57d04819045",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
					UUID = "511a70bd_8b53_456a_a198_c510188389b6",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "35",
					sizepercenty = "62",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -88,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
							UUID = "80ecc969_3607_4b80_bfe3_b5d5e31ae679",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "255",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "502",
							ignoreSize = "False",
							name = "Panel_parent",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 642,
								PositionY = 319,
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1004",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title__Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "780f0288_0de0_4307_acf4_680706643ce4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "552",
									ignoreSize = "True",
									name = "Image_title_",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/simulation_trial6/result/hero.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -416,
										PositionY = -8,
									},
									width = "283",
									ZOrder = "1",
								},
								{
									controlID = "Image_big_bg_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "a43ae6d1_23cb_4e0b_8d5c_14132a62f4b7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "440",
									ignoreSize = "True",
									name = "Image_big_bg",
									sizepercentx = "7",
									sizepercenty = "12",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/simulation_trial6/result/bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 6,
										PositionY = 16,
									},
									width = "752",
									ZOrder = "1",
								},
								{
									controlID = "Image_tip_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "02b2e820_7906_4f27_a454_1ad72d050f16",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "69",
									ignoreSize = "True",
									name = "Image_tip",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/simulation_trial6/result/title.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 28,
										PositionY = 142,
									},
									width = "666",
									ZOrder = "1",
								},
								{
									controlID = "Button_close_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "f77a0f67_1acd_4c9a_bad4_4091b4694cf4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "60",
									ignoreSize = "True",
									name = "Button_close",
									normal = "ui/common/pop_ui/pop_btn_02.png",
									pressed = "ui/common/pop_ui/pop_btn_02.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 341,
										PositionY = 203,
									},
									UItype = "Button",
									width = "60",
									ZOrder = "1",
								},
								{
									controlID = "Image_sign_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "812eb7e0_f9d3_4417_a999_b5f602ce5eae",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "26",
									ignoreSize = "True",
									name = "Image_sign",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/simulation_trial4/006.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -227,
										PositionY = 196,
									},
									width = "2",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_title_en_Image_sign_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
											UUID = "17fdaa49_c099_4bff_b2f5_0adcb46872da",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF375DCA",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_title_en",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Hunter bounty",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 5,
												PositionY = -6,
											},
											width = "122",
											ZOrder = "1",
										},
										{
											controlID = "Label_title_Image_sign_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
											UUID = "b6590821_9181_4eb8_ba4f_7f734e79611f",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF375DCA",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_title",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "猎手的赏金",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -2,
												PositionY = -2,
											},
											width = "123",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_btns_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "e5c743cb_e52c_4ba3_a139_014a7baf9066",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "393",
									ignoreSize = "False",
									name = "Panel_btns",
									scaleX = "0.96",
									scaleY = "0.96",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -363,
										PositionY = -190,
										relativeToName = "Panel",
										nGravity = 5,
										nAlign = 4
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "65",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_reward1_Panel_btns_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
											UUID = "4bd985dd_6694_45e7_9e7f_1a787e1aefca",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:73;capInsetsWidth:0;capInsetsHeight:34",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "190",
											HitType = 
											{
												nHitType = 1,
												nXpos = 8,
												nYpos = 6,
												nHitWidth = 48,
												nHitHeight = 180
											},
											ignoreSize = "False",
											name = "Button_reward1",
											normal = "ui/simulation_trial6/result/btn2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 31,
												PositionY = 289,
											},
											UItype = "Button",
											width = "64",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_name_Button_reward1_Panel_btns_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
													UUID = "c18e91c5_a24e_4438_8861_3bebeac86d60",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "120",
													ignoreSize = "False",
													name = "Label_name",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "普通赏金",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														IsPercent = true,
													},
													width = "30",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_reward2_Panel_btns_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
											UUID = "dfce4b36_dd7f_423b_bcfe_b6133085c421",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:73;capInsetsWidth:0;capInsetsHeight:34",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "190",
											HitType = 
											{
												nHitType = 1,
												nXpos = 8,
												nYpos = 6,
												nHitWidth = 48,
												nHitHeight = 180
											},
											ignoreSize = "False",
											name = "Button_reward2",
											normal = "ui/simulation_trial6/result/btn2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 31,
												PositionY = 105,
											},
											UItype = "Button",
											width = "64",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_name_Button_reward2_Panel_btns_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
													UUID = "f3201ad9_28bc_43fa_913d_56be3453736b",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "120",
													ignoreSize = "False",
													name = "Label_name",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "普通赏金",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														IsPercent = true,
													},
													width = "30",
													ZOrder = "1",
												},
												{
													controlID = "Image_lock_Button_reward2_Panel_btns_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
													UUID = "d3e2feb9_c85b_42d9_ba0f_903d0a9e3d83",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "31",
													ignoreSize = "True",
													name = "Image_lock",
													scaleX = "0.8",
													scaleY = "0.8",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/summon/lock.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = -66,
													},
													width = "28",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "ScrollView_reward1_Panel_parent_Panel_root_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "1bd7f6ef_cfc2_4e11_9c1d_50583185c212",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "350",
									ignoreSize = "False",
									innerHeight = "350",
									innerWidth = "662",
									name = "ScrollView_reward1",
									showScrollbar = "False",
									sizepercentx = "100",
									sizepercenty = "100",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -305,
										PositionY = -176,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "662",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
					UUID = "bd9e7d16_3421_4782_a868_b542a493af92",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 32,
						PositionY = -463,
						LeftPositon = 32,
						TopPosition = 703,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_prefab_reward1_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
							UUID = "3e351f40_7d5f_4f90_83bb_bf9932bce96d",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "113",
							ignoreSize = "False",
							name = "Panel_prefab_reward1",
							panelTexturePath = "ui/simulation_trial6/result/bar2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 123,
								PositionY = 257,
								LeftPositon = 52,
								TopPosition = 867,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "662",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_desc_Panel_prefab_reward1_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "ca4fa318_2bd2_44de_adb0_7a8fbc5b7dc0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_desc",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "成功通关【章节】1-1",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 10,
										PositionY = 93,
									},
									width = "188",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_reward_Panel_prefab_reward1_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "bd85f8dc_70b7_43e4_83c3_64acc0598c65",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "2",
									dstBlendFunc = "771",
									height = "70",
									ignoreSize = "False",
									innerHeight = "70",
									innerWidth = "274",
									name = "ScrollView_reward",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 300,
										PositionY = 40,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "274",
									ZOrder = "1",
								},
								{
									controlID = "Label_state_Panel_prefab_reward1_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "b632601e_6f7d_4d19_9306_e973e4a6f892",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_state",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "未达成",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 582,
										PositionY = 56,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "Button_rev_Panel_prefab_reward1_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "46e61026_0b12_447d_bdde_d30d9121910c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "50",
									ignoreSize = "False",
									name = "Button_rev",
									normal = "ui/simulation_trial6/result/btn.png",
									pressed = "ui/simulation_trial6/result/btn.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 590,
										PositionY = 56,
									},
									UItype = "Button",
									width = "120",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_name_Button_rev_Panel_prefab_reward1_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
											UUID = "488a6eeb_e318_43dc_8776_2e8d94653cc8",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFEB5CDE",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "领取奖励",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "91",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_line_Panel_prefab_reward1_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "940aa20f_40a6_431f_86bc_0fdc1d2e7e2b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "88",
									ignoreSize = "True",
									name = "Image_line",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/simulation_trial2/line.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 484,
										PositionY = 56,
									},
									visible = "False",
									width = "14",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_prefab_reward2_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
							UUID = "933aad4c_ce90_47af_ba05_35abe032514f",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "113",
							ignoreSize = "False",
							name = "Panel_prefab_reward2",
							panelTexturePath = "ui/simulation_trial6/result/bar2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 159,
								PositionY = 100,
								LeftPositon = 52,
								TopPosition = 867,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "662",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_desc_Panel_prefab_reward2_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "1ad087c8_6d55_4e19_a5af_4952ec5a3c88",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_desc",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "成功通关【章节】1-1",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 10,
										PositionY = 93,
									},
									width = "188",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_reward_Panel_prefab_reward2_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "6a1341b2_785a_4c8e_b197_f5cf8e921301",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "2",
									dstBlendFunc = "771",
									height = "70",
									ignoreSize = "False",
									innerHeight = "70",
									innerWidth = "274",
									name = "ScrollView_reward",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 301,
										PositionY = 40,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "274",
									ZOrder = "1",
								},
								{
									controlID = "Label_state_Panel_prefab_reward2_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "77c870ed_964c_49e9_afc3_b36b1d5927b0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_state",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "未达成",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 582,
										PositionY = 56,
									},
									width = "69",
									ZOrder = "1",
								},
								{
									controlID = "Button_rev_Panel_prefab_reward2_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "272adced_9b29_44eb_ba6e_4cdacecdaac2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "50",
									ignoreSize = "False",
									name = "Button_rev",
									normal = "ui/simulation_trial6/result/btn.png",
									pressed = "ui/simulation_trial6/result/btn.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 590,
										PositionY = 56,
									},
									UItype = "Button",
									width = "120",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_name_Button_rev_Panel_prefab_reward2_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
											UUID = "3555faa0_6c75_46bd_9153_321fe654d0d0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFEB5CDE",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "领取奖励",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = -1,
											},
											width = "91",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_line_Panel_prefab_reward2_Panel_prefab_Panel-simulationTrialRewradView6_style1_simulationTrial_Game",
									UUID = "64412aa3_ffc1_4614_8811_083a5805bddd",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "88",
									ignoreSize = "True",
									name = "Image_line",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/simulation_trial2/line.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 485,
										PositionY = 56,
									},
									visible = "False",
									width = "14",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/simulation_trial6/result/hero.png",
			"ui/simulation_trial6/result/bg.png",
			"ui/simulation_trial6/result/title.png",
			"ui/common/pop_ui/pop_btn_02.png",
			"ui/simulation_trial4/006.png",
			"ui/simulation_trial6/result/btn2.png",
			"ui/summon/lock.png",
			"ui/simulation_trial6/result/bar2.png",
			"ui/simulation_trial6/result/btn.png",
			"ui/simulation_trial2/line.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

