local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-jointPicture_springFestival_activity_Game",
			UUID = "a23bbed9_eed1_495d_9c4d_21449e71b51e",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "719",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "909",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-jointPicture_springFestival_activity_Game",
					UUID = "31051187_2343_4e79_9bce_57f74213a6fe",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						IsPercent = true,
						PercentX = 50,
						PercentY = 50,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_Panel_root_Panel-jointPicture_springFestival_activity_Game",
							UUID = "36f26eac_52b3_415e_89df_a5ba90d0e4cc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui/activity/lightLantern/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								IsPercent = true,
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "sample_Panel_root_Panel-jointPicture_springFestival_activity_Game",
							UUID = "7ce5477b_8889_40f3_bb10_4206feaafb48",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "174",
							ignoreSize = "True",
							name = "sample",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/jointPicture/x1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -446,
								PositionY = 149,
							},
							width = "194",
							ZOrder = "1",
						},
						{
							controlID = "grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
							UUID = "198d1c66_8c43_4df8_bf76_a3c87dd28b1f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "630",
							ignoreSize = "True",
							name = "grids",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/jointPicture/gridbg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "709",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "grid1_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "6c42e6ca_9f6e_4137_9a6e_878d7ec27c2a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -201,
										PositionY = 179,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid1_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "57c461fc_5a51_4f87_844c_a514a676fe36",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid2_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "e7354183_ce3d_4d43_a364_c6ec5b377342",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = 179,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid2_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "3c57ea56_25d6_48b5_9f4a_330e3da9215c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid3_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "f67b745e_26b7_44ab_8d26_913b1c82e267",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 71,
										PositionY = 179,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid3_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "f41d7e46_14f1_4466_b980_0d875283479c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid4_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "12c649f5_4763_4f16_b120_076502f869d9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid4",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/4.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 206,
										PositionY = 179,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid4_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "07c74102_0dac_4abc_b5ce_78fc1ebae151",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid5_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "8705de93_4fcb_4e08_8fa3_324738f50810",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/5.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -201,
										PositionY = 60,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid5_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "d7909afe_5f13_41bb_bf7a_d81b1105e9d9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid6_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "82ca0654_9200_4c10_9713_426a7793fd18",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid6",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/6.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = 60,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid6_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "fc5f7abc_6510_4edd_afcb_af7414422b8b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid7_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "157656d8_2b5c_44cd_9c2e_c434d870b37e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid7",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/7.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 71,
										PositionY = 60,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid7_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "476b0b4b_4c75_4bc8_8c22_ae0b67ac722d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid8_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "d3281ec4_31eb_41ba_8420_b8a1b6aa1ebe",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid8",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/8.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 207,
										PositionY = 60,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid8_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "3c2406a8_bd99_49da_b590_90d1e56d7d83",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid9_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "d2211e26_2911_48fe_84cd_fe7f8af51c9c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid9",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/9.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -201,
										PositionY = -59,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid9_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "9c6e4279_413d_4f52_bae7_66e91c40fa49",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid10_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "4b1e03c4_b543_4d9d_b1db_ec38f52f64ff",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid10",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/10.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = -59,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid10_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "74723ec1_e63f_4be0_9ae5_914b15fb0d82",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid11_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "7e715eed_dd3d_4eb8_a454_a981b2666d94",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid11",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/11.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 71,
										PositionY = -59,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid11_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "c2588d8b_15e0_4ddf_8953_c95c994653d9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid12_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "1f4c002d_af44_4455_957b_6c0417f1ef7f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid12",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/12.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 207,
										PositionY = -59,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid12_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "04f3c010_b054_49b6_a35b_aaa2c1b890fd",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid13_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "cda8c0d0_d710_4f2d_92b6_66c7beb89ff1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid13",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/13.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -201,
										PositionY = -178,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid13_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "7c57e125_8c08_4eeb_b952_9f7f92dec9fb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid14_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "9fc9ae0a_92fa_4a78_b070_ff320834bf87",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid14",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/14.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = -178,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid14_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "5bd12a15_8620_418d_99b7_17e6a08c36e9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid15_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "963ccde0_aa5a_4b50_b6c8_00da88a6bb0c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid15",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/15.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 71,
										PositionY = -178,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid15_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "30d7aad2_4773_4881_836a_06b665acb6c9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "grid16_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
									UUID = "74ff286e_6c4c_496b_b080_d22620895aa7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "grid16",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/jointPicture/16.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 207,
										PositionY = -178,
									},
									width = "137",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "select_grid16_grids_Panel_root_Panel-jointPicture_springFestival_activity_Game",
											UUID = "0f9f00f1_6413_47ca_a2a3_7ad8c1d1726d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "True",
											name = "select",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/jointPicture/select.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "137",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "btn_close_Panel_root_Panel-jointPicture_springFestival_activity_Game",
							UUID = "896611f5_1d39_4327_b73e_06c1216a0cad",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "54",
							ignoreSize = "True",
							name = "btn_close",
							normal = "ui/activity/activityMain2/btn_normal.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 399,
								PositionY = 187,
							},
							UItype = "Button",
							width = "54",
							ZOrder = "1",
						},
						{
							controlID = "downcount_Panel_root_Panel-jointPicture_springFestival_activity_Game",
							UUID = "2e242672_e417_4cd8_92d6_3c20d0e4077d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "25",
							ignoreSize = "True",
							name = "downcount",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Compte à rebours",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -451,
								PositionY = 31,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "touchShield_Panel_root_Panel-jointPicture_springFestival_activity_Game",
							UUID = "43e6e8e2_4234_4f33_a60d_a1fe7555ebf7",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "550",
							ignoreSize = "False",
							name = "touchShield",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -300,
								PositionY = -279,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "600",
							ZOrder = "1",
						},
						{
							controlID = "mask_Panel_root_Panel-jointPicture_springFestival_activity_Game",
							UUID = "f8c5551d_716c_4b27_9936_9218a9d232a8",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "100",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "mask",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -690,
								PositionY = -321,
								IsPercent = true,
								PercentX = -71.88,
								PercentY = -50.31,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "1386",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/lightLantern/bg.png",
			"ui/activity/jointPicture/x1.png",
			"ui/activity/jointPicture/gridbg.png",
			"ui/activity/jointPicture/1.png",
			"ui/activity/jointPicture/select.png",
			"ui/activity/jointPicture/2.png",
			"ui/activity/jointPicture/3.png",
			"ui/activity/jointPicture/4.png",
			"ui/activity/jointPicture/5.png",
			"ui/activity/jointPicture/6.png",
			"ui/activity/jointPicture/7.png",
			"ui/activity/jointPicture/8.png",
			"ui/activity/jointPicture/9.png",
			"ui/activity/jointPicture/10.png",
			"ui/activity/jointPicture/11.png",
			"ui/activity/jointPicture/12.png",
			"ui/activity/jointPicture/13.png",
			"ui/activity/jointPicture/14.png",
			"ui/activity/jointPicture/15.png",
			"ui/activity/jointPicture/16.png",
			"ui/activity/activityMain2/btn_normal.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

