local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-storeActivityView1_Layer1_activity_Game",
			UUID = "947b831a_38e3_47d6_a824_f00587f99ab0",
			anchorPoint = "False",
			anchorPointX = "0.5",
			anchorPointY = "0.5",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "548",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "888",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
					UUID = "bf7ec27e_3ebd_48dd_bc54_d19658d3cb4c",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_diban_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
							UUID = "2539ecd4_c980_42d6_8efb_b6ec93846625",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "548",
							ignoreSize = "True",
							name = "Image_diban",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/001.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							visible = "False",
							width = "888",
							ZOrder = "1",
						},
						{
							controlID = "Image_ad_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
							UUID = "7a65cb3c_61b1_4703_8baf_89541eb2ae38",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "True",
							name = "Image_ad",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/ad2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 211,
							},
							visible = "False",
							width = "856",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_date_Image_ad_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "55ea8b41_894d_4d50_b62e_a4c89fa85260",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF000000",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_date",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "TextLable",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 361,
										PositionY = -51,
									},
									visible = "False",
									width = "81",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "ScrollView_goods_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
							UUID = "2f4fe2b0_e81c_4747_b38f_28ce9d0fab0a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "True",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "490",
							ignoreSize = "False",
							innerHeight = "490",
							innerWidth = "920",
							name = "ScrollView_goods",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -20,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "920",
							ZOrder = "1",
						},
						{
							controlID = "Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
							UUID = "a41de000_ff6c_4e9a_8b07_7f62b4586a7f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "32",
							ignoreSize = "False",
							name = "Panel_resource",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 251,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "856",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_resource_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "063231cb_a577_4562_9bbc_c8a9bbfbc365",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "47",
									ignoreSize = "True",
									name = "Image_resource",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/activityStyle/storeActivity/styleCur/4.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -298,
									},
									width = "320",
									ZOrder = "1",
								},
								{
									controlID = "Label_tips_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "9b117028_06e1_408f_b843_e61958cba94a",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF49557F",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_tips",
									nTextAlign = "1",
									nTextHAlign = "1",
									opacity = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "当前持有",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -421,
									},
									visible = "False",
									width = "83",
									ZOrder = "1",
								},
								{
									controlID = "Label_timing_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "a556503c_f191_4fcc_9f04_98d6b7518b0c",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFC4C6E5",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_timing",
									nTextAlign = "1",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "48天20时后结束",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -375,
									},
									width = "147",
									ZOrder = "1",
								},
								{
									controlID = "Panel_asset_1_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "0104b67d_4595_40cd_ab42_f45f51ac7f0e",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "100",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "False",
									name = "Panel_asset_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 283,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_di_Panel_asset_1_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "2dfdfb58_ac9c_4df5_8f72_13311e010fe5",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "44",
											ignoreSize = "True",
											name = "Image_di",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/activityStyle/storeActivity/styleCur/5.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 78,
											},
											width = "174",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Panel_asset_1_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "51b998c7_4123_4da2_b1b5_28ca925c67da",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											scaleX = "0.3",
											scaleY = "0.3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/system/004.png",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 15,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_count_Panel_asset_1_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "4db2278b_a593_428a_a16b_86ed224df02b",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFC4C6E5",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_count",
											nTextAlign = "1",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "120000",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 155,
											},
											width = "71",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_asset_2_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "f5a50dfa_b298_4694_8344_da93e6d70768",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "100",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "False",
									name = "Panel_asset_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 96,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_di_Panel_asset_2_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "0dfcd8fc_2901_4122_9876_b8a8cfa6b6eb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "44",
											ignoreSize = "True",
											name = "Image_di",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/activityStyle/storeActivity/styleCur/5.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 78,
											},
											width = "174",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Panel_asset_2_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "2471ca1e_0923_4fe0_8a45_f21a8d463982",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											scaleX = "0.3",
											scaleY = "0.3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/system/004.png",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 15,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_count_Panel_asset_2_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "081357bc_6c81_49df_8074_297bde89fafb",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFC4C6E5",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_count",
											nTextAlign = "1",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "120000",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 155,
											},
											width = "71",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_asset_3_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "84f42944_ea7e_4987_85b7_62866a40c64b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "100",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "False",
									name = "Panel_asset_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -92,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_di_Panel_asset_3_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "ef384898_46da_4fff_a34c_3e6fd2776082",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "44",
											ignoreSize = "True",
											name = "Image_di",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/activityStyle/storeActivity/styleCur/5.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 78,
											},
											width = "174",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Panel_asset_3_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "46fc354b_cec8_472d_8656_eb20c1e6f113",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											scaleX = "0.3",
											scaleY = "0.3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/system/004.png",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 15,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_count_Panel_asset_3_Panel_resource_Panel_root_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "7c7ce7ff_5cc5_42cc_be87_34a60faa0a54",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFC4C6E5",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_count",
											nTextAlign = "1",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "120000",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 155,
											},
											width = "71",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
					UUID = "2beb95e1_534d_4fcc_896a_95233c4f475e",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 705,
						PositionY = -573,
						LeftPositon = 1148,
						TopPosition = 301,
						relativeToName = "Panel",
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
							UUID = "11243ecb_020a_4686_8e3b_4330344c2367",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "479",
							ignoreSize = "False",
							name = "Panel_storeGoodsItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 206,
								PositionY = 351,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "260",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "3adc8519_7093_4d4d_9284_821af755d131",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "490",
									ignoreSize = "True",
									name = "Image_diban",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/activityStyle/storeActivity/styleCur/3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "264",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_Limit_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "00b1a2e0_e4ae_4092_b835_039a7a03d71b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "64",
											ignoreSize = "True",
											name = "Image_Limit",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = -212,
											},
											width = "64",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_countLimit_Image_Limit_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "04766208_d4ab_499d_be6a_39edda738ff7",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "18",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "34",
													ignoreSize = "False",
													name = "Label_countLimit",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "限购20次1",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -1,
														PositionY = -1,
													},
													width = "158",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Label_name_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "e18e1dcc_dd05_4ccc_b5bd_aab00014ceeb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF57ABE5",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "绿色能量",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 196,
											},
											width = "108",
											ZOrder = "1",
										},
										{
											controlID = "Panel_head_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "88b3fd11_f9e1_468a_a336_0bdd61a2fdd0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "90",
											ignoreSize = "False",
											name = "Panel_head",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 116,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "90",
											ZOrder = "1",
										},
										{
											controlID = "Panel_cost_1_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "87124a19_ca5b_4388_a660_667c1977e1db",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FF00FFFF;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "False",
											name = "Panel_cost_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -67,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "115",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_di_Panel_cost_1_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "5cd12d79_7d3a_4f55_8739_0c4b7a02b217",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "42",
													ignoreSize = "True",
													name = "Image_di",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/activity/activityStyle/storeActivity/styleCur/1.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 4,
														PositionY = -1,
														LeftPositon = -50,
														relativeToName = "Panel_cost_1",
													},
													width = "224",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_cost_1_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "176a0fa3_fa7a_4f95_9f2f_cac3f888f15c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "100",
													ignoreSize = "True",
													name = "Image_icon",
													scaleX = "0.4",
													scaleY = "0.4",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/system/002.png",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = -72,
														LeftPositon = -35,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "100",
													ZOrder = "1",
												},
												{
													controlID = "Label_count_Panel_cost_1_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "8ed6a097_2472_4a57_be34_4c42224fe312",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFC4C6E5",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_count",
													nTextAlign = "1",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "2000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 98,
														LeftPositon = 104,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "51",
													ZOrder = "1",
												},
												{
													controlID = "Label_countRed_Panel_cost_1_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "b7b9419c_bb2a_471c_8beb_ac54447908bd",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFD3870",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_countRed",
													nTextAlign = "1",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "2000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 97,
														LeftPositon = 45,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "51",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_cost_2_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "320e2e7c_0184_4505_ac7f_7e4fe06aa29b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "False",
											name = "Panel_cost_2",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -21,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "115",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_di_Panel_cost_2_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "4d1f06c6_03ea_4247_84bf_41f89890258a",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "42",
													ignoreSize = "True",
													name = "Image_di",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/activity/activityStyle/storeActivity/styleCur/1.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 4,
														PositionY = -1,
														LeftPositon = -50,
														relativeToName = "Panel_cost_2",
													},
													width = "224",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_cost_2_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "98c63c18_3249_437b_8586_9a9236d93121",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "100",
													ignoreSize = "True",
													name = "Image_icon",
													scaleX = "0.4",
													scaleY = "0.4",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/system/002.png",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = -72,
														LeftPositon = -35,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "100",
													ZOrder = "1",
												},
												{
													controlID = "Label_count_Panel_cost_2_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "6fb63858_675a_497a_a0e4_4e9374e2b3bb",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFC4C6E5",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_count",
													nTextAlign = "1",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "2000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 97,
														LeftPositon = 104,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "51",
													ZOrder = "1",
												},
												{
													controlID = "Label_countRed_Panel_cost_2_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "58e82f86_0d56_4264_b8a1_11888c4cc4d8",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFD3870",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_countRed",
													nTextAlign = "1",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "2000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 97,
														LeftPositon = 45,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "51",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_cost_3_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "dd5414cf_a664_4380_ab0e_cdcae72f8faa",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "False",
											name = "Panel_cost_3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 25,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "115",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_di_Panel_cost_3_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "415e9a3f_4e88_4f92_8ddd_248e97e06912",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "42",
													ignoreSize = "True",
													name = "Image_di",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/activity/activityStyle/storeActivity/styleCur/1.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 4,
														PositionY = -1,
														LeftPositon = -50,
														relativeToName = "Panel_cost_3",
													},
													width = "224",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_cost_3_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "74584b2f_42e0_4a4e_911c_93441203842b",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "100",
													ignoreSize = "True",
													name = "Image_icon",
													scaleX = "0.4",
													scaleY = "0.4",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/system/002.png",
													touchAble = "True",
													UILayoutViewModel = 
													{
														PositionX = -72,
														LeftPositon = -35,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "100",
													ZOrder = "1",
												},
												{
													controlID = "Label_count_Panel_cost_3_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "bcfb7ba6_00d0_4c45_9f9e_306155b08130",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFC4C6E5",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_count",
													nTextAlign = "1",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "2000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 97,
														LeftPositon = 104,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "51",
													ZOrder = "1",
												},
												{
													controlID = "Label_countRed_Panel_cost_3_Image_diban_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
													UUID = "cb8e5bfa_7eac_4823_9b39_1cd762c65881",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFD3870",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_countRed",
													nTextAlign = "1",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "2000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 97,
														LeftPositon = 45,
														relativeToName = "Panel_cost_1",
														nGravity = 5,
														nAlign = 4
													},
													width = "51",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Button_buy_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "f5dda183_26bc_4c71_a279_dd3b357558da",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "62",
									ignoreSize = "True",
									name = "Button_buy",
									normal = "ui/activity/activityStyle/storeActivity/styleCur/7.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -154,
									},
									UItype = "Button",
									width = "152",
									ZOrder = "1",
								},
								{
									controlID = "Label_buy_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "8a6b7dbf_7388_4856_a29b_f7aa6469ae57",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_buy",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "兑  换",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = -153,
									},
									width = "66",
									ZOrder = "1",
								},
								{
									controlID = "Image_buyTag_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "bfb94a71_89c0_4074_94d1_1d32434ad798",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "102",
									ignoreSize = "True",
									name = "Image_buyTag",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/525.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 93,
										PositionY = -189,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_saleNum_Image_buyTag_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "fc6bf9cd_f701_43d8_ac1a_05323c4d96d1",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_saleNum",
											nTextAlign = "1",
											nTextHAlign = "2",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "80",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -4,
												PositionY = -9,
											},
											width = "31",
											ZOrder = "1",
										},
										{
											controlID = "Label_storeMainView_1_Image_buyTag_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "4de6c664_8f71_4346_826c_76f76ed4da43",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "12",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "14",
											ignoreSize = "True",
											name = "Label_storeMainView_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "%",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 22,
												PositionY = -14,
											},
											width = "12",
											ZOrder = "1",
										},
										{
											controlID = "Label_storeMainView_2_Image_buyTag_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
											UUID = "cd9b949f_98de_403f_a1a6_efb774c078ee",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFAE045",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "10",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "11",
											ignoreSize = "True",
											name = "Label_storeMainView_2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "折扣",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 3,
												PositionY = -29,
											},
											width = "23",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_buy_tip_Panel_storeGoodsItem_Panel_prefab_Panel-storeActivityView1_Layer1_activity_Game",
									UUID = "b858f45d_8ec4_4476_a36f_6890c6bdfdf9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF9B5028",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "50",
									ignoreSize = "False",
									name = "Label_buy_tip",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "已拥有该信物 不可兑换",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = -173,
									},
									visible = "False",
									width = "140",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/001.png",
			"ui/activity/ad2.png",
			"ui/activity/activityStyle/storeActivity/styleCur/4.png",
			"ui/activity/activityStyle/storeActivity/styleCur/5.png",
			"icon/system/004.png",
			"ui/activity/activityStyle/storeActivity/styleCur/3.png",
			"ui/activity/activityStyle/storeActivity/styleCur/1.png",
			"icon/system/002.png",
			"ui/activity/activityStyle/storeActivity/styleCur/7.png",
			"ui/525.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

