return {
    [1] = {
        scriptId = 101,
        name = "琴里",
        order = 1,
        text = "快给我搭把手。",
        id = 1,
    },
    [2] = {
        scriptId = 101,
        name = "琴里",
        order = 2,
        text = "对了，扶住我，就是这样。",
        id = 2,
    },
    [3] = {
        scriptId = 101,
        name = "琴里",
        order = 3,
        text = "这下好了。",
        id = 3,
    },
    [4] = {
        scriptId = 102,
        name = "琴里",
        order = 1,
        text = "你是认真的？",
        id = 4,
    },
    [5] = {
        scriptId = 102,
        name = "琴里",
        order = 2,
        text = "呀——别拉我。",
        id = 5,
    },
    [6] = {
        scriptId = 102,
        name = "琴里",
        order = 3,
        text = "不对，快托我一下啊！",
        id = 6,
    },
    [7] = {
        scriptId = 103,
        name = "琴里",
        order = 1,
        text = "呼，终于稳住些了……",
        id = 7,
    },
    [8] = {
        scriptId = 103,
        name = "琴里",
        order = 2,
        text = "就是这样，吓死我了……",
        id = 8,
    },
    [9] = {
        scriptId = 103,
        name = "琴里",
        order = 3,
        text = "对了，快拉我一把。",
        id = 9,
    },
    [10] = {
        scriptId = 104,
        name = "琴里",
        order = 1,
        text = "你是想让我摔倒吗？",
        id = 10,
    },
    [11] = {
        scriptId = 104,
        name = "琴里",
        order = 2,
        text = "推我干嘛？叫你扶我啦！",
        id = 11,
    },
    [12] = {
        scriptId = 104,
        name = "琴里",
        order = 3,
        text = "不对啦。",
        id = 12,
    },
    [13] = {
        scriptId = 105,
        name = "琴里",
        order = 1,
        text = "你摸哪里啦！色鬼！",
        id = 13,
    },
    [14] = {
        scriptId = 105,
        name = "琴里",
        order = 2,
        text = "不是这里！",
        id = 14,
    },
    [15] = {
        scriptId = 105,
        name = "琴里",
        order = 3,
        text = "混蛋，快拖住我才对啊。",
        id = 15,
    },
    [16] = {
        scriptId = 106,
        name = "琴里",
        order = 1,
        text = "管书干嘛啦！",
        id = 16,
    },
    [17] = {
        scriptId = 106,
        name = "琴里",
        order = 2,
        text = "书比我重要吗？",
        id = 17,
    },
    [18] = {
        scriptId = 106,
        name = "琴里",
        order = 3,
        text = "要摔了，你在干嘛呢！",
        id = 18,
    },
}