return {
    [3303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 3303,
        modelId = 210507,
        talkPos = 1,
        desc = " 并且还搭配了不同的被动方案，快试试看吧！",
    },
    [2303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 2303,
        modelId = 210507,
        talkPos = 1,
        desc = " 并且还搭配了不同的被动方案，快试试看吧！",
    },
    [3201] = {
        nextGuideId = 3202,
        action = "Id_dress",
        id = 3201,
        modelId = 210507,
        talkPos = 1,
        desc = "看来已经装备好反转十香的专属质点了。",
    },
    [2201] = {
        nextGuideId = 2202,
        action = "Id_dress",
        id = 2201,
        modelId = 210507,
        talkPos = 1,
        desc = "看来已经装备好布兰的专属质点了。",
    },
    [4102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 4102,
        modelId = 210507,
        talkPos = 2,
        desc = "赶紧去下一关试试看吧！",
    },
    [1101] = {
        nextGuideId = 1102,
        action = "Id_dress",
        id = 1101,
        modelId = 210507,
        talkPos = 1,
        desc = "精灵基础属性已经有很大提升了！",
    },
    [3501] = {
        nextGuideId = 3502,
        action = "Id_happy",
        id = 3501,
        modelId = 210507,
        talkPos = 1,
        desc = "搭配宝石，会更进一步强化技能的效果。",
    },
    [2501] = {
        nextGuideId = 2502,
        action = "Id_happy",
        id = 2501,
        modelId = 210507,
        talkPos = 1,
        desc = "搭配宝石，会更进一步强化技能的效果。",
    },
    [1302] = {
        nextGuideId = 1303,
        action = "Id_happy",
        id = 1302,
        modelId = 210507,
        talkPos = 2,
        desc = "方案不同，强化的技能方向也有所不同。",
    },
    [2202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 2202,
        modelId = 210507,
        talkPos = 2,
        desc = "对了,仔细看看套装的效果，战斗中可事半功倍哦",
    },
    [3502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 3502,
        modelId = 210507,
        talkPos = 2,
        desc = "好了,技巧本司令都告诉你了,快去试试吧！",
    },
    [2502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 2502,
        modelId = 210507,
        talkPos = 2,
        desc = "好了,技巧本司令都告诉你了,快去试试吧！",
    },
    [1401] = {
        nextGuideId = 1402,
        action = "Id_dress",
        id = 1401,
        modelId = 210507,
        talkPos = 1,
        desc = "信物也是提升战力的一种有效方式。",
    },
    [501] = {
        nextGuideId = 502,
        action = "Id_happy",
        id = 501,
        modelId = 210507,
        talkPos = 1,
        desc = "搭配宝石，会更进一步强化技能的效果。",
    },
    [502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 502,
        modelId = 210507,
        talkPos = 2,
        desc = "好了,技巧本司令都告诉你了,快去试试吧！",
    },
    [2101] = {
        nextGuideId = 2102,
        action = "Id_dress",
        id = 2101,
        modelId = 210507,
        talkPos = 1,
        desc = "精灵基础属性已经有很大提升了！",
    },
    [1102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 1102,
        modelId = 210507,
        talkPos = 2,
        desc = "赶紧去下一关试试看吧！",
    },
    [4502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 4502,
        modelId = 210507,
        talkPos = 2,
        desc = "好了,技巧本司令都告诉你了,快去试试吧！",
    },
    [4501] = {
        nextGuideId = 4502,
        action = "Id_happy",
        id = 4501,
        modelId = 210507,
        talkPos = 1,
        desc = "搭配宝石，会更进一步强化技能的效果。",
    },
    [1303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 1303,
        modelId = 210507,
        talkPos = 1,
        desc = " 并且还搭配了不同的被动方案，快试试看吧！",
    },
    [3401] = {
        nextGuideId = 3402,
        action = "Id_dress",
        id = 3401,
        modelId = 210507,
        talkPos = 1,
        desc = "信物也是提升战力的一种有效方式。",
    },
    [2401] = {
        nextGuideId = 2402,
        action = "Id_dress",
        id = 2401,
        modelId = 210507,
        talkPos = 1,
        desc = "信物也是提升战力的一种有效方式。",
    },
    [3102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 3102,
        modelId = 210507,
        talkPos = 2,
        desc = "赶紧去下一关试试看吧！",
    },
    [2102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 2102,
        modelId = 210507,
        talkPos = 2,
        desc = "赶紧去下一关试试看吧！",
    },
    [4402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 4402,
        modelId = 210507,
        talkPos = 2,
        desc = "准备好的信物，拥有特殊的羁绊效果哦。",
    },
    [1201] = {
        nextGuideId = 1202,
        action = "Id_dress",
        id = 1201,
        modelId = 210507,
        talkPos = 1,
        desc = "看来已经装备好涅普迪努的专属质点了。",
    },
    [4401] = {
        nextGuideId = 4402,
        action = "Id_dress",
        id = 4401,
        modelId = 210507,
        talkPos = 1,
        desc = "信物也是提升战力的一种有效方式。",
    },
    [3202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 3202,
        modelId = 210507,
        talkPos = 2,
        desc = "对了,仔细看看套装的效果，战斗中可事半功倍哦",
    },
    [1402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 1402,
        modelId = 210507,
        talkPos = 2,
        desc = "涅普迪努的专属信物，拥有特殊的羁绊效果哦。",
    },
    [2402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 2402,
        modelId = 210507,
        talkPos = 2,
        desc = "布兰的专属信物，拥有特殊的羁绊效果哦。",
    },
    [4302] = {
        nextGuideId = 4303,
        action = "Id_happy",
        id = 4302,
        modelId = 210507,
        talkPos = 2,
        desc = "方案不同，强化的技能方向也有所不同。",
    },
    [4301] = {
        nextGuideId = 4302,
        action = "Id_happy",
        id = 4301,
        modelId = 210507,
        talkPos = 1,
        desc = "不错,看来你已经解锁了三个不同的天使树方案了",
    },
    [4202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 4202,
        modelId = 210507,
        talkPos = 2,
        desc = "对了,仔细看看套装的效果，战斗中可事半功倍哦",
    },
    [4201] = {
        nextGuideId = 4202,
        action = "Id_dress",
        id = 4201,
        modelId = 210507,
        talkPos = 1,
        desc = "看来已经装备好猩红梦魇的专属质点了。",
    },
    [101] = {
        nextGuideId = 102,
        action = "Id_dress",
        id = 101,
        modelId = 210507,
        talkPos = 1,
        desc = "精灵基础属性已经有很大提升了！",
    },
    [4101] = {
        nextGuideId = 4102,
        action = "Id_dress",
        id = 4101,
        modelId = 210507,
        talkPos = 1,
        desc = "精灵基础属性已经有很大提升了！",
    },
    [201] = {
        nextGuideId = 202,
        action = "Id_dress",
        id = 201,
        modelId = 210507,
        talkPos = 1,
        desc = "看来已经装备好反转折纸的专属质点了。",
    },
    [1501] = {
        nextGuideId = 1502,
        action = "Id_happy",
        id = 1501,
        modelId = 210507,
        talkPos = 1,
        desc = "搭配宝石，会更进一步强化技能的效果。",
    },
    [102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 102,
        modelId = 210507,
        talkPos = 2,
        desc = "赶紧去下一关试试看吧！",
    },
    [401] = {
        nextGuideId = 402,
        action = "Id_dress",
        id = 401,
        modelId = 210507,
        talkPos = 1,
        desc = "信物也是提升战力的一种有效方式。",
    },
    [2301] = {
        nextGuideId = 2302,
        action = "Id_happy",
        id = 2301,
        modelId = 210507,
        talkPos = 1,
        desc = "不错,看来你已经解锁了三个不同的天使树方案了",
    },
    [1202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 1202,
        modelId = 210507,
        talkPos = 2,
        desc = "对了,仔细看看套装的效果，战斗中可事半功倍哦",
    },
    [3402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 3402,
        modelId = 210507,
        talkPos = 2,
        desc = "反转十香的专属信物，拥有特殊的羁绊效果哦。",
    },
    [301] = {
        nextGuideId = 302,
        action = "Id_happy",
        id = 301,
        modelId = 210507,
        talkPos = 1,
        desc = "不错,你已经解锁了三个不同的天使树方案了",
    },
    [3301] = {
        nextGuideId = 3302,
        action = "Id_happy",
        id = 3301,
        modelId = 210507,
        talkPos = 1,
        desc = "不错,看来你已经解锁了三个不同的天使树方案了",
    },
    [4303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 4303,
        modelId = 210507,
        talkPos = 1,
        desc = " 并且还搭配了不同的被动方案，快试试看吧！",
    },
    [3101] = {
        nextGuideId = 3102,
        action = "Id_dress",
        id = 3101,
        modelId = 210507,
        talkPos = 1,
        desc = "精灵基础属性已经有很大提升了！",
    },
    [3302] = {
        nextGuideId = 3303,
        action = "Id_happy",
        id = 3302,
        modelId = 210507,
        talkPos = 2,
        desc = "方案不同，强化的技能方向也有所不同。",
    },
    [2302] = {
        nextGuideId = 2303,
        action = "Id_happy",
        id = 2302,
        modelId = 210507,
        talkPos = 2,
        desc = "方案不同，强化的技能方向也有所不同。",
    },
    [402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 402,
        modelId = 210507,
        talkPos = 2,
        desc = "反转折纸的专属信物，拥有特殊的羁绊效果哦。",
    },
    [1301] = {
        nextGuideId = 1302,
        action = "Id_happy",
        id = 1301,
        modelId = 210507,
        talkPos = 1,
        desc = "不错,看来你已经解锁了三个不同的天使树方案了",
    },
    [302] = {
        nextGuideId = 303,
        action = "Id_happy",
        id = 302,
        modelId = 210507,
        talkPos = 2,
        desc = "方案不同，强化的技能方向也有所不同。",
    },
    [303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 303,
        modelId = 210507,
        talkPos = 1,
        desc = " 并且还搭配了不同的被动方案，快试试看吧！",
    },
    [1502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 1502,
        modelId = 210507,
        talkPos = 2,
        desc = "好了,技巧本司令都告诉你了,快去试试吧！",
    },
    [202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 202,
        modelId = 210507,
        talkPos = 2,
        desc = "对了,仔细看看套装效果，战斗中可事半功倍哦",
    },
}