local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-bingoDivinationView_Layer1_bingo_Game",
			UUID = "22bf49a3_661a_49ba_a0f1_373f2bd36c5c",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
					UUID = "0833ab79_83cb_49b5_89e5_84b0385df9fc",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "1161504d_ab89_4351_bdb0_d17685dfb332",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Image_inner_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "73fa029c_c2f4_4422_9f4b_1165fd3f4c72",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_inner",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/card/007.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "top_part1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "955d4243_bd44_4ddb_bdb6_a589d1af143a",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "1",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "60",
							ignoreSize = "False",
							name = "top_part1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -568,
								PositionY = 320,
								IsPercent = true,
								PercentX = -50,
								PercentY = 50,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1136",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_back_top_part1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "5c6a0dcb_52cf_42de_95d0_4e9b96ba4bce",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "52",
									ignoreSize = "True",
									name = "Button_back",
									normal = "ui/common/btn_back.png",
									pressed = "ui/common/btn_back.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 73,
										PositionY = -32,
									},
									UItype = "Button",
									width = "62",
									ZOrder = "1",
								},
								{
									controlID = "Image_zuan_bg_top_part1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "d8f17aa5_380d_4749_a489_fcea0f49847e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "False",
									name = "Image_zuan_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/res_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 970,
										PositionY = -37,
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_chip_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "ec480e03_0002_443f_839c_563d67b02334",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_chip",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "99999999",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -49,
												PositionY = -2,
											},
											width = "98",
											ZOrder = "1",
										},
										{
											controlID = "Button_add_chip_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "2cbfb6bf_f544_4658_afbd_e73ec1788ca1",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "38",
											ignoreSize = "True",
											name = "Button_add_chip",
											normal = "ui/common/jiahao.png",
											pressed = "ui/common/jiahao.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 92,
												PositionY = 1,
											},
											UItype = "Button",
											width = "38",
											ZOrder = "1",
										},
										{
											controlID = "Image_chip_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "77322033_7c72_4556_b20d_a4a4129ca92f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_chip",
											scaleX = "0.5",
											scaleY = "0.5",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/system/005.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -72,
												PositionY = 1,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_chip_delta_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "b9b9c129_f3e7_4518_a3b9_449c9f2747b0",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#00FFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "True",
											name = "Label_chip_delta",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -49,
												PositionY = -2,
											},
											width = "0",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Image_di_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "e734a27f_b97b_4cdb_8961_ac1d3962acfe",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "360",
							ignoreSize = "True",
							name = "Image_di",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/card/006.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 60,
							},
							width = "956",
							ZOrder = "1",
						},
						{
							controlID = "Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "9b8444d8_a2e7_45ed_8942_0febd5eb3b11",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "308",
							ignoreSize = "False",
							name = "Panel_card_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -320,
								PositionY = 64,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "198",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_front_card_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "ecc09584_7728_4191_9aaf_a97c76581735",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "308",
									ignoreSize = "True",
									name = "Button_front_card",
									normal = "ui/activity/bingoGame/card/002.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									UItype = "Button",
									width = "198",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Button_front_card_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "615d990b_e952_4b33_a82f_c57bd3366049",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Num",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 15,
											},
											width = "56",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Button_front_card_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "90b71dea_f642_4f6d_841a_9e3158951d14",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "268",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/role/activity/card_102.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "174",
											ZOrder = "1",
										},
										{
											controlID = "Image_up_Button_front_card_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "9d453eb6_394c_4ee1_a53b_8422a42ea863",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "308",
											ignoreSize = "True",
											name = "Image_up",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/003.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "198",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_back_card_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "401461e1_3d34_42fd_9e25_8d2d429ba312",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "308",
									ignoreSize = "True",
									name = "Image_back_card",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/card/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "198",
									ZOrder = "1",
								},
								{
									controlID = "Spine_card_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "fc6298d2_3a75_4b7f_b482_bc9d2303a05f",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_card",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/evt_effect_card/evt_effect_card",
										animationName = "kaishi",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 6,
										PositionY = -7,
										relativeToName = "Panel",
									},
									visible = "False",
									ZOrder = "1",
								},
								{
									controlID = "Panel_select_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "39727687_429d_4540_89d5_7b2fa6f56809",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "308",
									ignoreSize = "False",
									name = "Panel_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "198",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_1_Panel_select_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "f0a15e48_6664_4e5a_abfe_b0892c36abf7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -82,
												PositionY = 137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_2_Panel_select_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "ae3e9062_b740_46f5_8a29_d4533c0d2f84",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_2",
											scaleX = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 82,
												PositionY = 137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_3_Panel_select_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "d345c8a9_68b2_4d15_8941_7bd541a79817",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_3",
											scaleX = "-1",
											scaleY = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 82,
												PositionY = -137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_4_Panel_select_Panel_card_1_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "b51265a5_b505_43b4_ad40_e5d33cb3308e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_4",
											scaleY = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -82,
												PositionY = -137,
											},
											width = "72",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "db054194_2dd3_4372_ac09_bc859ec9f6a7",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "308",
							ignoreSize = "False",
							name = "Panel_card_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = 64,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "198",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_front_card_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "99a1c48c_1bf1_4f56_ac68_a1d42ef479a0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "308",
									ignoreSize = "True",
									name = "Button_front_card",
									normal = "ui/activity/bingoGame/card/002.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									UItype = "Button",
									width = "198",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Button_front_card_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "755a8ad8_da36_4c4c_ab7d_96c1bd67f178",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Num",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 15,
											},
											width = "56",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Button_front_card_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "6e95cc4e_b483_4fab_a0ed_7bd5f29942fe",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "268",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/role/activity/card_102.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "174",
											ZOrder = "1",
										},
										{
											controlID = "Image_up_Button_front_card_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "524f9c46_698d_47fa_a642_f7ef8079ce57",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "308",
											ignoreSize = "True",
											name = "Image_up",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/003.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "198",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_back_card_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "37bf82fb_1bf6_431a_83f2_037f6bd862e1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "308",
									ignoreSize = "True",
									name = "Image_back_card",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/card/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "198",
									ZOrder = "1",
								},
								{
									controlID = "Spine_card_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "42704329_4a57_4762_b8fb_cf99d76300b2",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_card",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/evt_effect_card/evt_effect_card",
										animationName = "kaishi",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 6,
										PositionY = -7,
										relativeToName = "Panel",
									},
									visible = "False",
									ZOrder = "1",
								},
								{
									controlID = "Panel_select_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "415cae18_3d8a_4235_94ca_88d7de38c1e4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "308",
									ignoreSize = "False",
									name = "Panel_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "198",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_1_Panel_select_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "6ee8337c_e556_4942_a9a0_d8a4ae92321b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -82,
												PositionY = 137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_2_Panel_select_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "c26bfe2c_9d60_447a_9397_0720db2a4088",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_2",
											scaleX = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 82,
												PositionY = 137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_3_Panel_select_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "4ed19665_daad_46ac_9703_244115de9fda",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_3",
											scaleX = "-1",
											scaleY = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 82,
												PositionY = -137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_4_Panel_select_Panel_card_2_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "84c02e52_f8c5_41b8_a9a5_9a05f5d6b9cb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_4",
											scaleY = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -82,
												PositionY = -137,
											},
											width = "72",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "91adecaf_022e_4801_bedf_95d6866379b8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "308",
							ignoreSize = "False",
							name = "Panel_card_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 320,
								PositionY = 64,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "198",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_front_card_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "bf2bb85b_2c25_4fef_853f_2da72e2a5651",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "308",
									ignoreSize = "True",
									name = "Button_front_card",
									normal = "ui/activity/bingoGame/card/002.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									UItype = "Button",
									width = "198",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Button_front_card_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "a0a699f1_661c_4c3d_b0fc_b892c8aed434",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Num",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 15,
											},
											width = "56",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Button_front_card_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "5259a465_68e2_46a3_917f_580521c3d0dc",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "268",
											ignoreSize = "True",
											name = "Image_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/role/activity/card_102.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "174",
											ZOrder = "1",
										},
										{
											controlID = "Image_up_Button_front_card_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "8861a4b6_559e_4362_899b_b7433e02d999",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "308",
											ignoreSize = "True",
											name = "Image_up",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/003.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "198",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_back_card_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "1a40c394_9f3e_4387_a0fd_b367e26b4c35",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "308",
									ignoreSize = "True",
									name = "Image_back_card",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/card/001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "198",
									ZOrder = "1",
								},
								{
									controlID = "Spine_card_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "e3469de3_45b0_4bec_b2ff_558a0c0fd9a2",
									classname = "MESpine",
									dstBlendFunc = "771",
									name = "Spine_card",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									spineModel = 
									{
										SpinePath = "effect/evt_effect_card/evt_effect_card",
										animationName = "kaishi",
										IsLoop = true,
										IsPlay = true,
										IsUseQueue = false,
										AnimationQueue = 
										{
											
										},
									},
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 5,
										PositionY = -7,
										relativeToName = "Panel",
									},
									visible = "False",
									ZOrder = "1",
								},
								{
									controlID = "Panel_select_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "4bfbd3ff_1c06_437c_9e76_8632dd7bce39",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "308",
									ignoreSize = "False",
									name = "Panel_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "198",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_1_Panel_select_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "e2554015_954c_45ff_bd71_3bc2fb9df9b3",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -82,
												PositionY = 137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_2_Panel_select_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "14f093e3_84bd_4356_9161_dc498d75fee7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_2",
											scaleX = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 82,
												PositionY = 137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_3_Panel_select_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "8bc30f13_6df2_4643_9c24_2fb0c4502ff8",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_3",
											scaleX = "-1",
											scaleY = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 82,
												PositionY = -137,
											},
											width = "72",
											ZOrder = "1",
										},
										{
											controlID = "Image_4_Panel_select_Panel_card_3_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "863926e4_7bfe_42bd_b439_5ac8e281c315",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_4",
											scaleY = "-1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/bingoGame/card/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -82,
												PositionY = -137,
											},
											width = "72",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_result_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "e61ca248_cdcf_43aa_a507_a98f84d5d131",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "45",
							ignoreSize = "False",
							name = "Panel_result",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -320,
								PositionY = -118,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							visible = "False",
							width = "300",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_diban_Panel_result_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "5fc82320_2e18_4e19_b6ac_f5d9c290809c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "45",
									ignoreSize = "False",
									name = "Image_diban",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/top_bar_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "160",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_resultNum_Image_diban_Panel_result_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "b426056d_0f17_4ab6_8c10_83adaf4d8262",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_resultNum",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "999",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "41",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "361bebef_bdca_4d9a_b880_a98572d85fb6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "152",
							ignoreSize = "True",
							name = "Image_bottom",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/card/005.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -212,
							},
							width = "954",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_vote_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "6ec17467_e5a6_4579_b022_911a2024437e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "90",
									ignoreSize = "False",
									name = "Panel_vote",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -304,
										PositionY = -43,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "300",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_odds_num_Panel_vote_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "d1f43e73_fa56_47c9_8d3a_4dc63a7d09a2",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_odds_num",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Posibilidades",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -11,
												PositionY = 61,
											},
											width = "108",
											ZOrder = "1",
										},
										{
											controlID = "Label_vote_num_Panel_vote_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "92e3b74a_df68_4fcc_b4f6_2c8e14d06af3",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_vote_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "5000",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 28,
												PositionY = 26,
											},
											width = "73",
											ZOrder = "1",
										},
										{
											controlID = "Image_voteIcon_Panel_vote_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "033bed15_cddf_4a0c_9733_c752357a073a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "64",
											ignoreSize = "True",
											name = "Image_voteIcon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -74,
												PositionY = 42,
											},
											width = "64",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_down_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "4f491e9e_5b97_4ecb_8bc7_d43ca033dc16",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_down",
									normal = "ui/activity/bingoGame/luckyPlate/007.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -67,
										PositionY = -23,
									},
									UItype = "Button",
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_add_Button_down_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "de0a5946_6590_446b_a780_efb2d14aca6f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "28",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "35",
											ignoreSize = "True",
											name = "Label_add",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "-",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -20,
												PositionY = 2,
											},
											width = "15",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Button_down_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "8755c61c_b979_4f9a_b0e0_82a07e0a147c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											scaleX = "0.5",
											scaleY = "0.5",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/item/goods/500066.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 18,
												PositionY = 2,
											},
											width = "100",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_endtime_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "7c62a328_5dd4_47cd_8305_6b4fa42e027e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_endtime",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Selecciona una tarjeta",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 106,
										PositionY = -15,
									},
									width = "171",
									ZOrder = "1",
								},
								{
									controlID = "Button_up_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "9c9b1e01_c416_4111_b586_fefe294faf76",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_up",
									normal = "ui/activity/bingoGame/luckyPlate/007.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 75,
										PositionY = -23,
									},
									UItype = "Button",
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_add_Button_up_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "049870ba_76cc_43c4_893a_b19e46e1b195",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "28",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "35",
											ignoreSize = "True",
											name = "Label_add",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "+",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -20,
												PositionY = 2,
											},
											width = "22",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Button_up_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "04a9059c_d54a_4247_a882_7e48739cbf23",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											scaleX = "0.5",
											scaleY = "0.5",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/item/goods/500066.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 18,
												PositionY = 2,
											},
											width = "100",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_do_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "76b7ca5d_1d8b_4d25_a29b_4de3ea6a269c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_do",
									normal = "ui/activity/bingoGame/luckyPlate/006.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 350,
										PositionY = -23,
									},
									UItype = "Button",
									width = "156",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_enterPlot_Button_do_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "9c21cab6_dd47_4f08_949c_472bcb1e87c6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB83F59",
												StrokeSize = 2,
											},
											height = "34",
											ignoreSize = "True",
											name = "Label_enterPlot",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Empezar adivinación",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "97",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_xipai_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "629f3a46_cb3f_4d84_8cd7_15b7ecfa1576",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_xipai",
									normal = "ui/activity/bingoGame/luckyPlate/006.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 350,
										PositionY = -23,
									},
									UItype = "Button",
									width = "156",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_enterPlot_Button_xipai_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
											UUID = "d0b78d65_34c3_48f5_ab59_764222166a5c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB83F59",
												StrokeSize = 2,
											},
											height = "34",
											ignoreSize = "True",
											name = "Label_enterPlot",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Barajar",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "54",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_vote_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "a1d57011_167c_4460_86ca_87d6037eda4b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "False",
									name = "Label_vote",
									nTextAlign = "1",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Reglas de apuesta Reglas de apuesta Reglas de apuesta Reglas de apuesta",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 152,
										PositionY = 36,
									},
									width = "500",
									ZOrder = "1",
								},
								{
									controlID = "Image_dot1_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "0fe9cad2_c221_4523_8958_20ab4450c56b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "Image_dot1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/luckyPlate/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -118,
										PositionY = 36,
									},
									width = "24",
									ZOrder = "1",
								},
								{
									controlID = "Image_dot2_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "3878e46e_792f_4af8_8ebe_63f62c6d9bb4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "Image_dot2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/luckyPlate/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 418,
										PositionY = 36,
									},
									width = "24",
									ZOrder = "1",
								},
								{
									controlID = "Image_vote_Image_bottom_Panel_root_Panel-bingoDivinationView_Layer1_bingo_Game",
									UUID = "5583ea46_d6b3_404c_94e7_1491ccf928aa",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_vote",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/item/goods/500066.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -303,
										PositionY = -19,
									},
									width = "100",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-bingoDivinationView_Layer1_bingo_Game",
					UUID = "d28dc81a_460d_40f0_9aee_41af2ae24b25",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = -442,
						TopPosition = 762,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_diceItem_Panel_prefab_Panel-bingoDivinationView_Layer1_bingo_Game",
							UUID = "9898db7b_49fa_4b46_96f4_279af29075f9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "110",
							ignoreSize = "False",
							name = "Panel_diceItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -672,
								PositionY = 162,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "110",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/bingoGame/bg.png",
			"ui/activity/bingoGame/card/007.png",
			"ui/common/btn_back.png",
			"ui/common/res_bg.png",
			"ui/common/jiahao.png",
			"icon/system/005.png",
			"ui/activity/bingoGame/card/006.png",
			"ui/activity/bingoGame/card/002.png",
			"icon/role/activity/card_102.png",
			"ui/activity/bingoGame/card/003.png",
			"ui/activity/bingoGame/card/001.png",
			"ui/activity/bingoGame/card/008.png",
			"ui/common/top_bar_bg.png",
			"ui/activity/bingoGame/card/005.png",
			"ui/activity/bingoGame/luckyPlate/007.png",
			"icon/item/goods/500066.png",
			"ui/activity/bingoGame/luckyPlate/006.png",
			"ui/activity/bingoGame/luckyPlate/005.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

