local t = {
		{
			name="dispatchMainLayer",
			ui ="dispatchMainLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="dispatch",
			canLoad=true,
			logic="",
		},
		{
			name="dispatchHeroLayer",
			ui ="dispatchHeroLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="dispatch",
			canLoad=true,
			logic="",
		},
		{
			name="dispatchDetailLayer",
			ui ="dispatchDetailLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="dispatch",
			canLoad=true,
			logic="",
		},
		{
			name="dispatchAddHeroLayer",
			ui ="dispatchAddHeroLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="dispatch",
			canLoad=true,
			logic="",
		},
		{
			name="dispatchRewardShowLayer",
			ui ="dispatchRewardShowLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="dispatch",
			canLoad=true,
			logic="",
		},
}
return t
