local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-chapterDetailView_zhounianqing_activity_Game",
			UUID = "2b1b080a_87ce_4b10_87f3_6749392111ec",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1386",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
					UUID = "51f4b588_f94f_4db6_a05d_42cb4596c2b3",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_base",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -88,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "c21e23fb_e59e_46e7_a4bb_7a78a11e1bc8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "428",
							ignoreSize = "False",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/common/pop_ui/pop_bg_01.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 528,
								PositionY = 320,
							},
							width = "738",
							ZOrder = "1",
						},
						{
							controlID = "Image_shadow_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "c61b15c5_7491_4baf_b3c5_1ae3e2f1f2b2",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "234",
							ignoreSize = "True",
							name = "Image_shadow",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/znq_huigu/tip/018.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 886,
								PositionY = 116,
							},
							width = "454",
							ZOrder = "1",
						},
						{
							controlID = "image_1_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "b5f88c55_623a_490e_8ee9_c1d7423bc41e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "184",
							ignoreSize = "True",
							name = "image_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/znq_huigu/tip/001.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 529,
								PositionY = 389,
							},
							width = "720",
							ZOrder = "1",
						},
						{
							controlID = "Image_tip1_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "c49fede7_40cf_4679_b977_98560225f63e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "34",
							ignoreSize = "True",
							name = "Image_tip1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/znq_huigu/tip/004.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 261,
								PositionY = 278,
							},
							width = "186",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_tip1_Image_tip1_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "5b2c837f_b65e_4354_a9ce_e00751e6986f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_tip1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "ข้อมูลด่าน",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -20,
										PositionY = -2,
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_tip2_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "1530dc81_8d50_4d1e_bf52_5ddb491b73cb",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "34",
							ignoreSize = "True",
							name = "Image_tip2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/znq_huigu/tip/004.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 697,
								PositionY = 279,
							},
							width = "186",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_tip2_Image_tip2_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "f6a4dba3_0642_4efe_93dd_cd5932a6db8a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_tip2",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "ข้อมูลรางวัล",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -20,
										PositionY = -2,
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Label_name_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "86ef8187_d79e_4ab6_b23c_4698d085fc9a",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF30354A",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "28",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "35",
							ignoreSize = "True",
							name = "Label_name",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "ด่านความจำ",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 170,
								PositionY = 502,
							},
							width = "114",
							ZOrder = "1",
						},
						{
							controlID = "Panel_titleName_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "c854b4e0_0b45_4722_9b41_0dd0aba1dc92",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "31",
							ignoreSize = "False",
							name = "Panel_titleName",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 285,
								PositionY = 489,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "159",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_title_line_Panel_titleName_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "f51acdf7_0f0c_49d3_8a99_57cd9dfd5d32",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "26",
									ignoreSize = "True",
									name = "Image_title_line",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/pop_ui/pop_ui_02.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 5,
										PositionY = 16,
									},
									width = "2",
									ZOrder = "1",
								},
								{
									controlID = "Label_englishName_Panel_titleName_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "231a1fe0_cd93_4e88_9bf9_d4bdd0bbbf6c",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF30354A",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "18",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "21",
									ignoreSize = "True",
									name = "Label_englishName",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "หน่วยความจำ",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 11,
										PositionY = 9,
									},
									width = "66",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_close_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "61bd58ab_8188_4710_8581_1aa830915f7f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "60",
							ignoreSize = "True",
							name = "Button_close",
							normal = "ui/common/pop_ui/pop_btn_02.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 868,
								PositionY = 503,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
						},
						{
							controlID = "chapter_des_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "780455cf_3f9f_4ad6_8e1d_b7c99975b3ed",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "1",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF49557F",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "0",
							ignoreSize = "False",
							name = "chapter_des",
							nTextAlign = "0",
							nTextHAlign = "0",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "รายละเอียดด่าน",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 196,
								PositionY = 254,
							},
							width = "377",
							ZOrder = "1",
						},
						{
							controlID = "Button_fight_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "dd9c0abd_66f7_4d34_8115_fa0234adf024",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "54",
							ignoreSize = "True",
							name = "Button_fight",
							normal = "ui/common/button_middle_n.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 821,
								PositionY = 148,
							},
							UItype = "Button",
							width = "124",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_chapterDetailView_1_Button_fight_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "8f8e62de_b09b_4f18_97af_0d84808905d6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_chapterDetailView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "จัดเตรียม",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_dating_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "ee6db7c7_f87b_45e7_b134_94cfad7ca4f7",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "54",
							ignoreSize = "True",
							name = "Button_dating",
							normal = "ui/common/button_middle_n.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 821,
								PositionY = 148,
							},
							UItype = "Button",
							width = "124",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_chapterDetailView_1_Button_dating_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "29058fb1_c98f_483f_b228_66ff34194d61",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_chapterDetailView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "เดท",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "ScrollView_reward_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "2497171e_faec_447b_ba49_c9853f23df6b",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "67",
							ignoreSize = "False",
							innerHeight = "67",
							innerWidth = "284",
							name = "ScrollView_reward",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 597,
								PositionY = 190,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "284",
							ZOrder = "1",
						},
						{
							controlID = "ScrollView_chapter_Panel_base_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "336641e3_37e1_4448_9cb6_5f704f94bec6",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "165",
							ignoreSize = "False",
							innerHeight = "165",
							innerWidth = "663",
							name = "ScrollView_chapter",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 194,
								PositionY = 307,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "663",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
					UUID = "ac145ef9_f579_4dad_bb17_56744f13ca3d",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 579,
						PositionY = -452,
						LeftPositon = 11,
						TopPosition = 772,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "47370e82_59ab_4884_914b_90b80e56a715",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.55",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "False",
							name = "Panel_levelItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -304,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "144",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_diban_Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "39bffe0e_9911_4e50_8df5_989e81b29ed7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "118",
									ignoreSize = "True",
									name = "Image_diban",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/levleDiban.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "118",
									ZOrder = "1",
								},
								{
									controlID = "Button_level_Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "a85394b6_9150_4730_910e_bac7c87892d2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "90",
									ignoreSize = "True",
									name = "Button_level",
									normal = "icon/fuben/level_1.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										
									},
									UItype = "Button",
									width = "105",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_type_Button_level_Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
											UUID = "a4190b6b_a981_4d9b_9aed_7d733393762a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "30",
											ignoreSize = "True",
											name = "Image_type",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/fighting_paly.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "30",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_Button_level_Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
											UUID = "0422560d_3daf_4e6a_825e_514bffee8ad4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#66000000",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1-1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -63,
											},
											width = "29",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_top_Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "316ca3be_020a_49e4_951d_a9a0ebec2385",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "118",
									ignoreSize = "True",
									name = "Image_top",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/levelTop.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "118",
									ZOrder = "1",
								},
								{
									controlID = "Image_lock_pre_Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "6cfe751a_5d66_4488_8409_8acdd2b2e58e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "135",
									ignoreSize = "True",
									name = "Image_lock_pre",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/plot_leve_lock.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "135",
									ZOrder = "1",
								},
								{
									controlID = "Image_select_Panel_levelItem_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "14a1ce56_4e3e_4f2b_8e2f_1f55198d97a7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "156",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/unlock.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "156",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_line_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
							UUID = "bbda7162_a93c_4ca6_b0cd_59544173450f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.55",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "False",
							name = "Panel_line",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -204,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "58",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_line_Panel_line_Panel_prefab_Panel-chapterDetailView_zhounianqing_activity_Game",
									UUID = "4497cde6_face_47e4_9bc1_11fe3a1f4e8f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "26",
									ignoreSize = "True",
									name = "Image_line",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/znq_huigu/tip/003.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "82",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/common/pop_ui/pop_bg_01.png",
			"ui/activity/znq_huigu/tip/018.png",
			"ui/activity/znq_huigu/tip/001.png",
			"ui/activity/znq_huigu/tip/004.png",
			"ui/common/pop_ui/pop_ui_02.png",
			"ui/common/pop_ui/pop_btn_02.png",
			"ui/common/button_middle_n.png",
			"ui/fuben/levleDiban.png",
			"icon/fuben/level_1.png",
			"ui/fuben/fighting_paly.png",
			"ui/fuben/levelTop.png",
			"ui/fuben/plot_leve_lock.png",
			"ui/fuben/unlock.png",
			"ui/activity/znq_huigu/tip/003.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

