local t = {
		{
			name="updateLayer",
			ui ="updateLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="loginLayer",
			ui ="loginLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="loginLoading",
			ui ="loginLoading.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="downLoadingTips",
			ui ="downLoadingTips.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="ActivationLayer",
			ui ="ActivationLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="loginWaiting",
			ui ="loginWaiting.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="noticeBoard",
			ui ="noticeBoard.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="serverChoose",
			ui ="serverChoose.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="cleanUpView",
			ui ="cleanUpView.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="loginNotice",
			ui ="loginNotice.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="loginLayerNew1",
			ui ="loginLayerNew1.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
		{
			name="oneYearloginLayer",
			ui ="oneYearloginLayer.lua",
			x=0,
			y=0,
			speed=0,
			layer="loginScene",
			canLoad=true,
			logic="",
		},
}
return t
