local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-SimulationSummonExchangeView_Simulation_summon_Game",
			UUID = "903f3b86_0403_4033_b6c7_f155da2137cb",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
					UUID = "c556e527_fa79_4d70_89e3_d6ce0aa754b9",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FF800080;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 418,
						PositionY = 355,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "bbf3871a_f3d4_4fbe_be84_5769f6673a25",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/summon/bg_result.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel_root",
								nGravity = 6,
								nAlign = 5
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Spine_bgfoo_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "9585d596_6384_49e6_920b_f0c5cf356e85",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_bgfoo",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/summon_show_jindu/summon_show_jindu",
								animationName = "animation",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
							},
							ZOrder = "1",
						},
						{
							controlID = "Spine_SimulationSummonExchangeView_1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "f7c26ae3_c425_4d5d_b1c6_cc683b33a489",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_SimulationSummonExchangeView_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/summon_show_jindu/summon_show_jindu",
								animationName = "jindu_10",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							ZOrder = "1",
						},
						{
							controlID = "Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "a1b9db71_4100_4fcb_9c98_984241dc17d7",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "187",
							ignoreSize = "False",
							name = "Panel_SimulationSummon1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = 196,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1038",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_SimulationSummonExchangeView_1_Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "c372e464_c432_4b4c_9c03_0d20e2806796",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "142",
									ignoreSize = "True",
									name = "Image_SimulationSummonExchangeView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/tchtwx.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "987",
									ZOrder = "1",
								},
								{
									controlID = "Image_Select_Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "f2eb987b_3bbd_4f99_89ca_e7df515c86df",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "187",
									ignoreSize = "True",
									name = "Image_Select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/tcht.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "1038",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_SimulationSummonExchangeView_1_Image_Select_Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
											UUID = "1b178978_fcc9_4394_8bf6_859d8148faf9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "54",
											ignoreSize = "True",
											name = "Image_SimulationSummonExchangeView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/selected.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 449,
											},
											width = "54",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_SimulationSummonExchangeView_2_Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "c1a04b9b_c4ba_4850_85e0_23f8a4eea06e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "45",
									ignoreSize = "True",
									name = "Image_SimulationSummonExchangeView_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -477,
										PositionY = 61,
									},
									width = "43",
									ZOrder = "1",
								},
								{
									controlID = "Label_SimulationSummonExchangeView_1_Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "c66a4a68_e4f3_4456_ac2e_ac097a4aba7d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_SimulationSummonExchangeView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "第一次保存",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -357,
										PositionY = 44,
									},
									width = "133",
									ZOrder = "1",
								},
								{
									controlID = "Panel_items_Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "4da908cc_d5e3_4849_beb9_540505316345",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "142",
									ignoreSize = "False",
									name = "Panel_items",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "987",
									ZOrder = "1",
								},
								{
									controlID = "Label_isReceive_Panel_SimulationSummon1_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "7bd98b0a_af40_4ea0_b77a_dc4e0cbb9c1f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_isReceive",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "已兑换",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 309,
										PositionY = 44,
									},
									width = "80",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "6b60f1b0_5175_4037_9aa2_cae52de000cf",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "187",
							ignoreSize = "False",
							name = "Panel_SimulationSummon2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = 36,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1038",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_SimulationSummonExchangeView_1_Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "ec5df88e_8666_40e8_bb83_c79c1bb153b1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "142",
									ignoreSize = "True",
									name = "Image_SimulationSummonExchangeView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/tchtwx.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "987",
									ZOrder = "1",
								},
								{
									controlID = "Image_Select_Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "63511e72_8125_418f_bfc5_0887a7372b91",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "187",
									ignoreSize = "True",
									name = "Image_Select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/tcht.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "1038",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_SimulationSummonExchangeView_1_Image_Select_Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
											UUID = "d8b4af10_775e_44bc_b55b_9b4caea40fc1",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "54",
											ignoreSize = "True",
											name = "Image_SimulationSummonExchangeView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/selected.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 449,
											},
											width = "54",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_SimulationSummonExchangeView_2_Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "7c5332b2_6eab_439b_a9fe_4fe558231b15",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "45",
									ignoreSize = "True",
									name = "Image_SimulationSummonExchangeView_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -477,
										PositionY = 62,
									},
									width = "43",
									ZOrder = "1",
								},
								{
									controlID = "Label_SimulationSummonExchangeView_1_Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "d3ef8335_f30a_47ab_b590_64cfd9360efd",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_SimulationSummonExchangeView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "第二次保存",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -357,
										PositionY = 44,
									},
									width = "133",
									ZOrder = "1",
								},
								{
									controlID = "Panel_items_Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "7d484fd8_ffdc_441d_aa29_b2f1481b257c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "142",
									ignoreSize = "False",
									name = "Panel_items",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "987",
									ZOrder = "1",
								},
								{
									controlID = "Label_isReceive_Panel_SimulationSummon2_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "96860330_2384_4232_bfb0_78aa2cccb2e5",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_isReceive",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "已兑换",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 309,
										PositionY = 44,
									},
									width = "80",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "83a5478a_630e_4812_9214_7c3bec86d2ae",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "187",
							ignoreSize = "False",
							name = "Panel_SimulationSummon3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -126,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1038",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_SimulationSummonExchangeView_1_Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "4628bfab_115b_4126_8ba5_ab2f0c963627",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "142",
									ignoreSize = "True",
									name = "Image_SimulationSummonExchangeView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/tchtwx.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "987",
									ZOrder = "1",
								},
								{
									controlID = "Image_Select_Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "6b071f0f_954c_4bb4_99a9_7ff2b0f3d1e1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "187",
									ignoreSize = "True",
									name = "Image_Select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/tcht.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "1038",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_SimulationSummonExchangeView_1_Image_Select_Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
											UUID = "1a49c457_8fd7_453c_b9ef_63d4a805ffdb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "54",
											ignoreSize = "True",
											name = "Image_SimulationSummonExchangeView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/selected.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 449,
											},
											width = "54",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_SimulationSummonExchangeView_2_Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "142a1929_ebe2_4c65_94f5_ef8cfc521f80",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "45",
									ignoreSize = "True",
									name = "Image_SimulationSummonExchangeView_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -477,
										PositionY = 62,
									},
									width = "43",
									ZOrder = "1",
								},
								{
									controlID = "Label_SimulationSummonExchangeView_1_Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "71ee45d5_d558_402e_bc32_3896b13fcc4c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "True",
									name = "Label_SimulationSummonExchangeView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "第三次保存",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -357,
										PositionY = 44,
									},
									width = "133",
									ZOrder = "1",
								},
								{
									controlID = "Panel_items_Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "9c953dac_eb1b_489e_9886_ff6d6c005409",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "142",
									ignoreSize = "False",
									name = "Panel_items",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "987",
									ZOrder = "1",
								},
								{
									controlID = "Label_isReceive_Panel_SimulationSummon3_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "0d5da4c7_9c3e_4050_a1ac_95cff6c3c264",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_isReceive",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "已兑换",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 309,
										PositionY = 44,
									},
									width = "80",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_back_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "6853c9f0_2568_43ee_842b_8a101584fc7c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							disabled = "ui/common/button_big_blue_n.png",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "58",
							ignoreSize = "True",
							name = "Button_back",
							normal = "ui/common/button_big_blue_n.png",
							pressed = "ui/common/button_big_blue_n.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -203,
								PositionY = -265,
							},
							UItype = "Button",
							width = "134",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_SimulationSummonExchangeView_1_Button_back_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "3df27008_e6d2_45e0_a589_3145b43314aa",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "30",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "Label_SimulationSummonExchangeView_1",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "返回",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "62",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_ok_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "4dbdd2a6_b38a_43cb_b9a7_d8fdb023b35c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							disabled = "ui/common/button_big_n.png",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "58",
							ignoreSize = "True",
							name = "Button_ok",
							normal = "ui/common/button_big_n.png",
							pressed = "ui/common/button_big_n.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 194,
								PositionY = -267,
							},
							UItype = "Button",
							width = "134",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_unlock_bg_Button_ok_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "3fb0c28d_3083_49c7_b452_cca770ac1541",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "58",
									ignoreSize = "True",
									name = "Image_unlock_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/new_ui/new_15.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -216,
										PositionY = 2,
									},
									width = "141",
									ZOrder = "1",
								},
								{
									controlID = "Label_text_Button_ok_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "1cd86731_46bd_426f_a550_ff4a9343da2c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "30",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "Label_text",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "返回",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "62",
									ZOrder = "1",
								},
								{
									controlID = "Image_costIcon_Button_ok_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "b4432bf7_ab65_4fe1_aacb_4f3d734883f0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_costIcon",
									scaleX = "0.35",
									scaleY = "0.35",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/system/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -184,
									},
									width = "100",
									ZOrder = "1",
								},
								{
									controlID = "Label_costNum_Button_ok_Panel_root_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "197e4414_02cc_4827_a08b_32815af63c9b",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#00FFFFFF",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_costNum",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "x280",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -85,
									},
									width = "49",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
					UUID = "3e17cd97_cc91_430b_be9a_51ed288d56d4",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -57,
						PositionY = -636,
						LeftPositon = -57,
						TopPosition = 706,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_summonItem_Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "12d637d2_6285_43aa_b3ae_82acb39051c6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "103",
							ignoreSize = "False",
							name = "Panel_summonItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 306,
								PositionY = 156,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "431",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_select_Panel_summonItem_Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "fa0065f3_e844_4939_9391_7c5ecec8ac91",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "103",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/pt.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "431",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_summonItem_Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "8ee4500a_8e87_49a5_843c_d8fda67f9430",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "68",
									ignoreSize = "True",
									name = "Image_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fuben/plot.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 137,
										PositionY = -8,
									},
									width = "68",
									ZOrder = "1",
								},
								{
									controlID = "Label_name_Panel_summonItem_Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "f2084045_b659_4038_99c6_f926e34adc0b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "26",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "34",
									ignoreSize = "True",
									name = "Label_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "精灵名称",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -181,
										PositionY = 33,
									},
									width = "107",
									ZOrder = "1",
								},
								{
									controlID = "Image_upTips_Panel_summonItem_Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "3c6bdb3a_19ee_43dd_a1db_6af3817bc12e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "46",
									ignoreSize = "True",
									name = "Image_upTips",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/024.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -103,
										PositionY = -17,
									},
									width = "168",
									ZOrder = "1",
								},
								{
									controlID = "Image_lock_Panel_summonItem_Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
									UUID = "adb541be_4572_4897_b62c_deae9a78cdbf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "102",
									ignoreSize = "True",
									name = "Image_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/summon/simulation/lock.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "434",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_check_Panel_prefab_Panel-SimulationSummonExchangeView_Simulation_summon_Game",
							UUID = "890b9206_59e8_4dd3_83ce_f21aa22f847d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "70",
							ignoreSize = "True",
							name = "Button_check",
							normal = "ui/summon/check.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								
							},
							UItype = "Button",
							width = "70",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/summon/bg_result.png",
			"ui/summon/simulation/tchtwx.png",
			"ui/summon/simulation/tcht.png",
			"ui/common/selected.png",
			"ui/summon/simulation/1.png",
			"ui/summon/simulation/2.png",
			"ui/summon/simulation/3.png",
			"ui/common/button_big_blue_n.png",
			"ui/common/button_big_n.png",
			"ui/fairy/new_ui/new_15.png",
			"icon/system/005.png",
			"ui/summon/simulation/pt.png",
			"ui/fuben/plot.png",
			"ui/summon/024.png",
			"ui/summon/simulation/lock.png",
			"ui/summon/check.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

