local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-musicgame_musicgame_battle_Game",
			UUID = "ae98d8dc_86fd_440c_9dc6_0bd38e2b6d85",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-musicgame_musicgame_battle_Game",
					UUID = "539977e2_7bdb_4844_a49d_b529d4cac0f5",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "35",
					sizepercenty = "62",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Spine_back_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "c60ed4d2_0a89_40db_a691_fbb549d1e8eb",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_back",
							scaleX = "0.475",
							scaleY = "0.475",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/effects_11001_skillD/effects_11001_skillD",
								animationName = "effects_11001_skillD3_loop",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 319,
								relativeToName = "Panel_effect",
								nGravity = 6,
								nAlign = 5
							},
							ZOrder = "1",
						},
						{
							controlID = "Image_bg_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "2035e084_695d_43fd_862d_22afa3cc83a8",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/bg1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 320,
								IsPercent = true,
								PercentX = 50,
								PercentY = 50,
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Image_top_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "aba71b6c_fd2d_4e9f_aca5_c4c2e711b538",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "1",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "48",
							ignoreSize = "True",
							name = "Image_top",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/top.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 640,
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Image_track_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "8ba5be93_406a_446d_bd22_c91c4e42ecb9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "538",
							ignoreSize = "True",
							name = "Image_track",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/track.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 371,
								IsPercent = true,
								PercentX = 50,
								PercentY = 58,
							},
							width = "978",
							ZOrder = "1",
						},
						{
							controlID = "Image_hightlight1_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "06d86e1c_03e1_4c63_9d30_3831bf8c29ca",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "542",
							ignoreSize = "True",
							name = "Image_hightlight1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/highlight1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 290,
								PositionY = 98,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "428",
							ZOrder = "1",
						},
						{
							controlID = "Image_hightlight2_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "c5843c71_a066_4084_8e8a_c491cef9a60f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "542",
							ignoreSize = "True",
							name = "Image_hightlight2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/highlight2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 410,
								PositionY = 98,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "276",
							ZOrder = "1",
						},
						{
							controlID = "Image_hightlight3_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "fb1183fb_0287_4886_8f16_332dfe0a7826",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "542",
							ignoreSize = "True",
							name = "Image_hightlight3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/highlight3.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 98,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "200",
							ZOrder = "1",
						},
						{
							controlID = "Image_hightlight4_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "a676e2da_1e26_4b52_abc5_d9022689dbd6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							flipX = "True",
							height = "542",
							ignoreSize = "True",
							name = "Image_hightlight4",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/highlight2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 725,
								PositionY = 98,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "276",
							ZOrder = "1",
						},
						{
							controlID = "Image_hightlight5_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "c052e048_3c40_4b00_add1_2e7eacaf8634",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							flipX = "True",
							height = "542",
							ignoreSize = "True",
							name = "Image_hightlight5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/highlight1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 845,
								PositionY = 98,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "428",
							ZOrder = "1",
						},
						{
							controlID = "Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "efd5e565_039f_4acd_98fe_b2c5ed5150d5",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "538",
							ignoreSize = "False",
							name = "Panel_notes",
							sizepercentx = "100",
							sizepercenty = "84",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 102,
								TopPosition = 3,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1136",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "ed_point3_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "e0aacfe7_74cf_4046_80c6_40fc3193d773",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "ed_point3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 568,
										IsPercent = true,
										PercentX = 50,
									},
									width = "198",
									ZOrder = "1",
								},
								{
									controlID = "ed_point2_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "2161863d_4f7d_4139_ad53_203b540e7cb2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									flipX = "True",
									height = "38",
									ignoreSize = "True",
									name = "ed_point2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 369,
									},
									width = "202",
									ZOrder = "1",
								},
								{
									controlID = "ed_point1_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "5caa416b_73e2_4986_95f0_09debede125e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									flipX = "True",
									height = "38",
									ignoreSize = "True",
									name = "ed_point1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 174,
									},
									width = "214",
									ZOrder = "1",
								},
								{
									controlID = "ed_point4_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "ba08045c_3e64_424f_9b39_d52ac49713be",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "ed_point4",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 766,
									},
									width = "202",
									ZOrder = "1",
								},
								{
									controlID = "ed_point5_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "8356fc30_543f_47c3_ad9f_51e755ad9390",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "ed_point5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 961,
									},
									width = "214",
									ZOrder = "1",
								},
								{
									controlID = "st_point3_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "39d64208_41e9_410b_badb_ab4d71a1de5f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "st_point3",
									scaleX = "0.22",
									scaleY = "0.22",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 568,
										PositionY = 538,
									},
									width = "198",
									ZOrder = "1",
								},
								{
									controlID = "st_point2_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "dd4761d3_858b_4bc7_ac98_65d9c5e22cc2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									flipX = "True",
									height = "38",
									ignoreSize = "True",
									name = "st_point2",
									scaleX = "0.22",
									scaleY = "0.22",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 523,
										PositionY = 538,
									},
									width = "202",
									ZOrder = "1",
								},
								{
									controlID = "st_point5_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "28288453_544b_4bbf_a22e_9c42afaebb65",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "st_point5",
									scaleX = "0.22",
									scaleY = "0.22",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 656,
										PositionY = 538,
									},
									width = "214",
									ZOrder = "1",
								},
								{
									controlID = "st_point4_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "7e50ab02_5791_4e15_a867_f647504b0a89",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "st_point4",
									scaleX = "0.22",
									scaleY = "0.22",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 612,
										PositionY = 538,
									},
									width = "202",
									ZOrder = "1",
								},
								{
									controlID = "st_point1_Panel_notes_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "8feea834_d80b_4e3f_bfc7_845707e32140",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									flipX = "True",
									height = "38",
									ignoreSize = "True",
									name = "st_point1",
									scaleX = "0.22",
									scaleY = "0.22",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/note1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 479,
										PositionY = 538,
									},
									width = "214",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_score_box_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "342e844d_6388_4831_a86b_af15e093c96e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "60",
							ignoreSize = "True",
							name = "Image_score_box",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/scorebox.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1053,
								PositionY = 442,
								relativeToName = "Panel",
							},
							width = "412",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "LabelBMFont_score_Image_score_box_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "f2ee6d2f_e889_4b36_985b_fd0970736331",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/yinfujifen.fnt",
									height = "32",
									ignoreSize = "True",
									name = "LabelBMFont_score",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "888",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -24,
										PositionY = 8,
									},
									width = "132",
									ZOrder = "1",
								},
								{
									controlID = "Image_combo_Image_score_box_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "03cc8cc7_18a2_40c9_a0d5_9fff6c2e959c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "Image_combo",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/musicgame/combo.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 53,
									},
									width = "100",
									ZOrder = "1",
								},
								{
									controlID = "Label_combo_Image_score_box_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "34d77376_750b_4f91_b9d9_5222afe6cc30",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFE3D4F0",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "Label_combo",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "0",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = 50,
										relativeToName = "Panel",
									},
									width = "27",
									ZOrder = "1",
								},
								{
									controlID = "Label_atk_Image_score_box_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "7c283e25_ba4e_48bd_bf08_c2f7461ccb76",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFE3E4F0",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_atk",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "ANG",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -55,
										PositionY = -73,
									},
									width = "53",
									ZOrder = "1",
								},
								{
									controlID = "Label_atk_value_Image_score_box_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "92f5f701_4fe3_4526_9640_08b27bb36997",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFE3E4F0",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "Label_atk_value",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "+30%",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 77,
										PositionY = -71,
									},
									width = "94",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_bottom_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "b54505f5_33cf_4099_9946_538653486e59",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "100",
							ignoreSize = "True",
							name = "Image_bottom",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/bottom.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								IsPercent = true,
								PercentX = 50,
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Button_key1_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "d801ea5c_fbb2_4574_bd02_313a0f9a93cf",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "100",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_key1",
							normal = "ui/musicgame/key1.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 149,
								PositionY = 50,
							},
							UItype = "Button",
							width = "252",
							ZOrder = "1",
						},
						{
							controlID = "Button_key2_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "d7e61be0_ea78_4206_b1b5_bee5c43990f5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "100",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_key2",
							normal = "ui/musicgame/key2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 352,
								PositionY = 50,
							},
							UItype = "Button",
							width = "232",
							ZOrder = "1",
						},
						{
							controlID = "Button_key5_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "2f5077f0_1f66_49e3_a540_e02970c460e6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "100",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_key5",
							normal = "ui/musicgame/key5.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 986,
								PositionY = 50,
							},
							UItype = "Button",
							width = "260",
							ZOrder = "1",
						},
						{
							controlID = "Button_key4_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "3f5803e6_b1b8_42e0_8bc2_a12cf4abd704",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "100",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_key4",
							normal = "ui/musicgame/key4.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 782,
								PositionY = 50,
							},
							UItype = "Button",
							width = "232",
							ZOrder = "1",
						},
						{
							controlID = "Button_key3_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "69846e41_1b72_4dec_bdc9_eeffc0940f06",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "100",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_key3",
							normal = "ui/musicgame/key3.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 50,
							},
							UItype = "Button",
							width = "220",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "8c5f9747_cae0_45dd_881b_4ccfa2f42239",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "24",
							ignoreSize = "True",
							name = "Image_line",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/line.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 100,
							},
							visible = "False",
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Spine_longpress1_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "4b22e838_dde9_4e03_89f5_cffc008e6773",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_longpress1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/effects_11001_skillD/effects_11001_skillD",
								animationName = "effects_11001_skillD2_loop",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 166,
								PositionY = 100,
							},
							visible = "False",
							ZOrder = "1",
						},
						{
							controlID = "Spine_longpress2_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "e0e8592d_2870_4364_ab98_8134375ffa70",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_longpress2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/effects_11001_skillD/effects_11001_skillD",
								animationName = "effects_11001_skillD2_loop",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 370,
								PositionY = 100,
							},
							visible = "False",
							ZOrder = "1",
						},
						{
							controlID = "Spine_longpress3_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "5926f1b2_92ff_47b1_9e94_02fdf67fb921",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_longpress3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/effects_11001_skillD/effects_11001_skillD",
								animationName = "effects_11001_skillD2",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 566,
								PositionY = 100,
							},
							visible = "False",
							ZOrder = "1",
						},
						{
							controlID = "Spine_longpress4_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "aece7028_bc30_4c13_9141_a9d14139030e",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_longpress4",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/effects_11001_skillD/effects_11001_skillD",
								animationName = "effects_11001_skillD2_loop",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 770,
								PositionY = 100,
							},
							visible = "False",
							ZOrder = "1",
						},
						{
							controlID = "Spine_longpress5_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "0f6cd297_12e5_432d_b75a_afd24f7adcd6",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_longpress5",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/effects_11001_skillD/effects_11001_skillD",
								animationName = "effects_11001_skillD2_loop",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 966,
								PositionY = 100,
							},
							visible = "False",
							ZOrder = "1",
						},
						{
							controlID = "Image_timeBox_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "547b09db_d0e0_4942_ad40_163cba00e400",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "110",
							ignoreSize = "True",
							name = "Image_timeBox",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/musicgame/timebox.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 78,
								PositionY = 535,
								LeftPositon = -56,
								TopPosition = 55,
								relativeToName = "Panel",
							},
							width = "129",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "LabelBMFont_time_Image_timeBox_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "8e99f3df_3746_4994_9364_676fb88b79f5",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFE3E4F0",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "42",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "52",
									ignoreSize = "True",
									name = "LabelBMFont_time",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "00",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -9,
										PositionY = -3,
									},
									width = "75",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_exit_Panel_root_Panel-musicgame_musicgame_battle_Game",
							UUID = "a6b8e64b_3ee1_454b_9f98_4b7a829f86b7",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "44",
							HitType = 
							{
								nHitType = 3,
							},
							ignoreSize = "True",
							name = "Button_exit",
							normal = "ui/btn.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 1048,
								PositionY = 571,
							},
							UItype = "Button",
							width = "110",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_exit_Button_exit_Panel_root_Panel-musicgame_musicgame_battle_Game",
									UUID = "859ce01e_52a8_43eb_aef9_deee3832bf10",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFF7F7F8",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF30354A",
										StrokeSize = 2,
									},
									height = "31",
									ignoreSize = "True",
									name = "Label_exit",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Überspringen",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = -2,
									},
									width = "49",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_effect_Panel-musicgame_musicgame_battle_Game",
					UUID = "af882596_4ebe_4224_bcc0_e326fc41514b",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_effect",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/musicgame/bg1.png",
			"ui/musicgame/top.png",
			"ui/musicgame/track.png",
			"ui/musicgame/highlight1.png",
			"ui/musicgame/highlight2.png",
			"ui/musicgame/highlight3.png",
			"ui/musicgame/note3.png",
			"ui/musicgame/note2.png",
			"ui/musicgame/note1.png",
			"ui/musicgame/scorebox.png",
			"ui/musicgame/combo.png",
			"ui/musicgame/bottom.png",
			"ui/musicgame/key1.png",
			"ui/musicgame/key2.png",
			"ui/musicgame/key5.png",
			"ui/musicgame/key4.png",
			"ui/musicgame/key3.png",
			"ui/musicgame/line.png",
			"ui/musicgame/timebox.png",
			"ui/btn.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

