local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-duanwuMakeView_duanwu_activity_Game",
			UUID = "890bf82a_0108_49d0_9585_0a5344fb7056",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
					UUID = "a92d3abf_b296_4b4f_98c5_bfbe5a69a7b2",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
							UUID = "359d3cc1_a5f4_40bd_ab4d_2ece7d77d912",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/duanwu/main/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Spine_boat_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
							UUID = "291a2dc7_66f8_4231_8beb_99586102d384",
							classname = "MESpine",
							dstBlendFunc = "771",
							name = "Spine_boat",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							spineModel = 
							{
								SpinePath = "effect/ui_event_duanwu/ui_event_duanwu",
								animationName = "ui_event_duanwu_1",
								IsLoop = true,
								IsPlay = true,
								IsUseQueue = false,
								AnimationQueue = 
								{
									
								},
							},
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
							},
							ZOrder = "1",
						},
						{
							controlID = "Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
							UUID = "b5803b90_0fbf_4ed5_aa4c_115b51c9f521",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "148",
							ignoreSize = "True",
							name = "Image_make_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/duanwu/make/010.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 146,
							},
							width = "1064",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_target_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "102adc06_f40e_4dbb_bb43_7ebd0c8c89ac",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_target",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -424,
										PositionY = 7,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
								},
								{
									controlID = "Image_target_num_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "e217a8ed_0603_4003_9a34_25807b94b23a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "32",
									ignoreSize = "True",
									name = "Image_target_num",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/007.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -424,
										PositionY = -50,
									},
									width = "130",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_target_num_Image_target_num_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "bfcaef0f_a18a_4444_8db1_d301b6739311",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_target_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Memiliki 7753",
											touchAble = "False",
											touchScaleEnable = "True",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "86",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_1_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "c214fcaa_8a85_4eab_bff4_57ef26e69ad3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -240,
										PositionY = 5,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_1_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "68ddbd3c_4b36_4bd9_8b6e_188ab7a6d6c5",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Image_add_Panel_item_1_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "c3e6f351_1856_430a_85f5_0693eb406ebe",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/duanwu/make/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 73,
												PositionY = -3,
											},
											width = "40",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_2_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "62dfecb3_93a1_481a_846d_979afbab882d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -98,
										PositionY = 5,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_2_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "8b698178_9020_473c_a020_dc6a1a4cb478",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Image_add_Panel_item_2_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "46214bca_9603_479e_97e0_4c0491cd8efc",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/duanwu/make/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 72,
												PositionY = -3,
											},
											width = "40",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_3_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "d2ebfc4d_2404_444b_99ab_6ce19c605c77",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 39,
										PositionY = 5,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_3_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "ebdb5d07_2503_4c67_9281_8466070403f4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_select_num_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "d5a22047_48e3_4921_aa1f_d7199c6659d6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "39",
									ignoreSize = "False",
									name = "Image_select_num",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/top_bar_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 261,
										PositionY = -3,
									},
									width = "156",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_down_Image_select_num_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "e452a4de_8f70_426f_96ec_91caca891aa3",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "42",
											ignoreSize = "False",
											name = "Button_down",
											normal = "ui/common/mini_pop/027.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -75,
												PositionY = 1,
											},
											UItype = "Button",
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Button_up_Image_select_num_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "eb19d9e4_7233_41bf_998f_176c92c074db",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "42",
											ignoreSize = "False",
											name = "Button_up",
											normal = "ui/common/mini_pop/028.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 79,
												PositionY = 1,
											},
											UItype = "Button",
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Label_num_Image_select_num_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "6eab707b_1ae4_49da_9ffb_ac5d2e2187fb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "999",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "41",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_make_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "0e161e3a_95c9_4ab2_aff0_b035ae377dd8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "114",
									ignoreSize = "True",
									name = "Button_make",
									normal = "ui/activity/duanwu/make/006.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 443,
										PositionY = 1,
									},
									UItype = "Button",
									width = "114",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_make_Button_make_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "727c01dd_4dcb_4e93_8be3_c0d4a0dea543",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF238AC0",
												StrokeSize = 2,
											},
											height = "36",
											ignoreSize = "True",
											name = "Label_make",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Craft",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "57",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_not_enough_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "06f90bc2_0ac4_42b0_8649_4f40553470c8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "114",
									ignoreSize = "True",
									name = "Image_not_enough",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 443,
										PositionY = 1,
									},
									width = "114",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_not_enough_Image_not_enough_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "134c0ff4_5ad5_4983_abac_7293613211bd",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF68768F",
												StrokeSize = 2,
											},
											height = "80",
											ignoreSize = "False",
											name = "Label_not_enough",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Material tidak cukup",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "72",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_name_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "de099385_e480_4466_8a3d_d7f42edc1896",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_name",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -507,
										PositionY = 29,
									},
									width = "72",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_name_1_Image_name_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "c53c3011_282a_410c_a9f0_5ea6ed367404",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB38B2A",
												StrokeSize = 1,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_name_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Merah",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -7,
												PositionY = 18,
											},
											width = "26",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_2_Image_name_Image_make_1_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "573a5297_a2d6_441b_a70a_c10613fe9caf",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB38B2A",
												StrokeSize = 1,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_name_2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Kacang",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 6,
												PositionY = -21,
											},
											width = "26",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
							UUID = "75917b87_45e5_41a2_9381_58037f63b951",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "148",
							ignoreSize = "True",
							name = "Image_make_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/duanwu/make/010.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -14,
							},
							width = "1064",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_target_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "30659608_7b99_48fb_88d3_e4fb020efa61",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_target",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -424,
										PositionY = 7,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
								},
								{
									controlID = "Image_target_num_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "00841103_f6a9_480b_843e_a08f61391f46",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "32",
									ignoreSize = "True",
									name = "Image_target_num",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/007.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -424,
										PositionY = -50,
									},
									width = "130",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_target_num_Image_target_num_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "f1ae9a37_26cf_41d7_99be_7a753a46f2a7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_target_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Memiliki 7753",
											touchAble = "False",
											touchScaleEnable = "True",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "86",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_1_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "9cfe4a3f_617b_423b_a122_e5833cb00e28",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -240,
										PositionY = 6,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_1_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "2194eb95_6cf0_4ecf_bd45_c77ad0f390f9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Image_add_Panel_item_1_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "69afb0dd_ee66_433c_9690_fe074f3e8e1d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/duanwu/make/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 73,
												PositionY = -3,
											},
											width = "40",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_2_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "7b7536dc_1a29_43aa_b761_123fc44f083e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -99,
										PositionY = 6,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_2_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "e4ef0a3e_fd99_44b3_822e_74eeb6648492",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Image_add_Panel_item_2_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "cf6ba90c_e151_4cd2_a5ed_e94a69ce9c0a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/duanwu/make/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 72,
												PositionY = -3,
											},
											width = "40",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_3_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "2b4bdce9_b4dd_4bfe_b795_4fedcacc46ca",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 39,
										PositionY = 6,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_3_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "bd090037_95e1_4385_8ad8_f6b8a595c11d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_select_num_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "009de9c5_dcba_43e3_844f_45f8a7f81925",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "39",
									ignoreSize = "False",
									name = "Image_select_num",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/top_bar_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 261,
										PositionY = -3,
									},
									width = "156",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_down_Image_select_num_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "0aea726a_c537_49a2_8c00_631dc63ef2d5",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "42",
											ignoreSize = "False",
											name = "Button_down",
											normal = "ui/common/mini_pop/027.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -75,
												PositionY = 1,
											},
											UItype = "Button",
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Button_up_Image_select_num_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "c28fb7c8_7410_4842_839d_566843fb29d8",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "42",
											ignoreSize = "False",
											name = "Button_up",
											normal = "ui/common/mini_pop/028.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 79,
												PositionY = 1,
											},
											UItype = "Button",
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Label_num_Image_select_num_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "152deaa1_6bd7_4d7b_8e91_36409f574722",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "999",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "41",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_make_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "76e33f69_1a80_4a84_a17e_d0f07f4b2f0a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "114",
									ignoreSize = "True",
									name = "Button_make",
									normal = "ui/activity/duanwu/make/006.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 444,
										PositionY = 1,
									},
									UItype = "Button",
									width = "114",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_make_Button_make_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "a308a642_7246_416d_9eaf_831b106c71d1",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF238AC0",
												StrokeSize = 2,
											},
											height = "36",
											ignoreSize = "True",
											name = "Label_make",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Craft",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "57",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_not_enough_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "c4f2dab9_0c70_485a_9fee_ae9b125c4154",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "114",
									ignoreSize = "True",
									name = "Image_not_enough",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 443,
										PositionY = 1,
									},
									width = "114",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_not_enough_Image_not_enough_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "79a9c5da_689a_4505_9ae6_0bca41a03704",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF68768F",
												StrokeSize = 2,
											},
											height = "80",
											ignoreSize = "False",
											name = "Label_not_enough",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Material tidak cukup",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "72",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_name_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "92bf1f77_1bde_476a_ae14_0f3095115c27",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_name",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -507,
										PositionY = 29,
									},
									width = "72",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_name_1_Image_name_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "4b78f6cc_fda4_40e1_968c_a1a48242ca60",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB38B2A",
												StrokeSize = 1,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_name_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Merah",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -7,
												PositionY = 18,
											},
											width = "26",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_2_Image_name_Image_make_2_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "83196b1a_277b_44a9_ae22_e270fde50013",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB38B2A",
												StrokeSize = 1,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_name_2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Kacang",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 6,
												PositionY = -21,
											},
											width = "26",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
							UUID = "e900f8e7_5cfb_4095_b2d2_990a494d3f43",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "148",
							ignoreSize = "True",
							name = "Image_make_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/duanwu/make/010.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -173,
							},
							width = "1064",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_target_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "7101568a_a697_4991_8e63_bf0996910060",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_target",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -424,
										PositionY = 7,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
								},
								{
									controlID = "Image_target_num_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "83c8eae8_c560_4e69_ba94_5451b1f3baac",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "32",
									ignoreSize = "True",
									name = "Image_target_num",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/007.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -424,
										PositionY = -50,
									},
									width = "130",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_target_num_Image_target_num_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "5599cb3d_5ccc_4875_b87b_5552aa7db894",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_target_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Memiliki 7753",
											touchAble = "False",
											touchScaleEnable = "True",
											UILayoutViewModel = 
											{
												PositionY = -1,
											},
											width = "86",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_1_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "dfd2eb5c_1477_4aeb_b451_3589749dde68",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -240,
										PositionY = 6,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_1_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "4f116ddb_175f_44a7_9363_9d01eac6abef",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Image_add_Panel_item_1_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "7d9bca86_0503_4cab_a92c_b30fb18a3795",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/duanwu/make/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 73,
												PositionY = -3,
											},
											width = "40",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_2_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "80819c1c_795e_4bca_99bc_24a43e8bbc82",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -99,
										PositionY = 6,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_2_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "7cc165d0_5a08_4d45_8a1b_cce405c6d740",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Image_add_Panel_item_2_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "1fd7c7e6_571d_4f2b_9c3d_4f72e0a4854f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "40",
											ignoreSize = "True",
											name = "Image_add",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/duanwu/make/008.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 72,
												PositionY = -3,
											},
											width = "40",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_3_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "38aea1f6_f2d0_4205_bb02_dad01c8c27a3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_item_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 39,
										PositionY = 6,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "80",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Panel_item_3_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "936a0fa2_919b_497a_b261_5126bbebf4ea",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF34837D",
												StrokeSize = 2,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "0-0",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -58,
											},
											width = "42",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_select_num_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "6571ade4_de26_4b59_ab3e_2570d7d5dd54",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "39",
									ignoreSize = "False",
									name = "Image_select_num",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/top_bar_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 261,
										PositionY = -3,
									},
									width = "156",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_down_Image_select_num_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "6514565d_5e23_45cc_9133_a1e3b0226ced",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "42",
											ignoreSize = "False",
											name = "Button_down",
											normal = "ui/common/mini_pop/027.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -75,
												PositionY = 1,
											},
											UItype = "Button",
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Button_up_Image_select_num_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "c0b6d4ca_ce6d_43ba_8c0f_ddacf08b0dcd",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "42",
											ignoreSize = "False",
											name = "Button_up",
											normal = "ui/common/mini_pop/028.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 79,
												PositionY = 1,
											},
											UItype = "Button",
											width = "42",
											ZOrder = "1",
										},
										{
											controlID = "Label_num_Image_select_num_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "c6d9ed4f_af85_4b8e_9f7f_0c88ef793dec",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "999",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "41",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_make_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "e93bd66d_a03f_4d45_8143_d7076616b62f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "114",
									ignoreSize = "True",
									name = "Button_make",
									normal = "ui/activity/duanwu/make/006.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 444,
										PositionY = 1,
									},
									UItype = "Button",
									width = "114",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_make_Button_make_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "4e4b3b29_27b5_491f_8e9a_c13cd233df94",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF238AC0",
												StrokeSize = 2,
											},
											height = "36",
											ignoreSize = "True",
											name = "Label_make",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Craft",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "57",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_not_enough_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "8a2bc457_a126_46ce_88a1_cd585afea69d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "114",
									ignoreSize = "True",
									name = "Image_not_enough",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 443,
										PositionY = 1,
									},
									width = "114",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_not_enough_Image_not_enough_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "9d190635_11ca_48ca_85c7_8808f29d1788",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF68768F",
												StrokeSize = 2,
											},
											height = "80",
											ignoreSize = "False",
											name = "Label_not_enough",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Material tidak cukup",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "72",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_name_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
									UUID = "152a0ee8_8886_4a67_afe6_dc9c83225a5c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_name",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/duanwu/make/002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -507,
										PositionY = 29,
									},
									width = "72",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_name_1_Image_name_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "36d3fe7d_40a5_4eda_8d36_346f81deed9c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB38B2A",
												StrokeSize = 1,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_name_1",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Merah",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -7,
												PositionY = 18,
											},
											width = "26",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_2_Image_name_Image_make_3_Panel_root_Panel-duanwuMakeView_duanwu_activity_Game",
											UUID = "e90e6169_2b15_4974_88fa_ce80a17b08d7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB38B2A",
												StrokeSize = 1,
											},
											height = "29",
											ignoreSize = "True",
											name = "Label_name_2",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Kacang",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 6,
												PositionY = -21,
											},
											width = "26",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-duanwuMakeView_duanwu_activity_Game",
					UUID = "29495bf1_bb64_4b71_8e4e_d46e22edac31",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = -440,
						TopPosition = 760,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/duanwu/main/bg.png",
			"ui/activity/duanwu/make/010.png",
			"ui/activity/duanwu/make/007.png",
			"ui/activity/duanwu/make/008.png",
			"ui/common/top_bar_bg.png",
			"ui/common/mini_pop/027.png",
			"ui/common/mini_pop/028.png",
			"ui/activity/duanwu/make/006.png",
			"ui/activity/duanwu/make/005.png",
			"ui/activity/duanwu/make/002.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

