local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
			UUID = "7f5c8c87_70f4_41bc_8995_b60be61a4f5b",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "710",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "1020",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
					UUID = "7987b5f7_3901_4a73_b0a3_ca1d57793151",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
							UUID = "25ea0045_3c4e_49f0_8bd6_634be8ad4ab5",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "534",
							ignoreSize = "True",
							name = "Image_ad",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/whiteQueenAssist/leagueScore/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "919",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_timing_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "8f49ffce_0f94_42a7_9b00_9d07c85486ff",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "25",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF49557F",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "False",
									name = "Label_timing",
									nTextAlign = "1",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -417,
										PositionY = 223,
									},
									width = "0",
									ZOrder = "1",
								},
								{
									controlID = "Button_get_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "80a651cb_ce20_4318_a0ca_5c989f5a026f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "63",
									ignoreSize = "True",
									name = "Button_get",
									normal = "ui/activity/whiteQueenAssist/serverScore/button_00.png",
									pressed = "ui/activity/whiteQueenAssist/serverScore/button_00.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 103,
										PositionY = -216,
									},
									UItype = "Button",
									width = "178",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "btn_label_Button_get_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "98b6b7f2_c6de_45e7_b47f_87917f1b8768",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF435FBB",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "btn_label",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Peringkat",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "117",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "ScrollView_reward_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "37dce4cb_e1be_488a_aed2_2770bfad8e97",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "460",
									ignoreSize = "False",
									innerHeight = "460",
									innerWidth = "246",
									name = "ScrollView_reward",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 210,
										PositionY = -246,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "246",
									ZOrder = "1",
								},
								{
									controlID = "Label_all_score_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "87030eda_2da5_42f7_8703_070acd09c059",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "0",
									ignoreSize = "False",
									name = "Label_all_score",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Server",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 332,
										PositionY = 241,
									},
									width = "241",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_des_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "9c857c83_8d2a_407e_b435_081e677c2d36",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "108",
									ignoreSize = "False",
									innerHeight = "108",
									innerWidth = "442",
									name = "ScrollView_des",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -449,
										PositionY = -264,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "442",
									ZOrder = "1",
								},
								{
									controlID = "Panel_no_league_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "646e45dd_c49f_4c03_9c61_6ae410f57364",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "486",
									ignoreSize = "False",
									name = "Panel_no_league",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 207,
										PositionY = -264,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "247",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_no_league_Panel_no_league_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "c5833976_fafa_4bb8_b331_52b288bf8fb3",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FF435FBB",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_no_league",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 123,
												PositionY = 271,
											},
											width = "239",
											ZOrder = "1",
										},
										{
											controlID = "Button_join_league_Panel_no_league_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "a77d9e64_fec0_451a_8b54_4d31ac0b7fea",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "63",
											ignoreSize = "True",
											name = "Button_join_league",
											normal = "ui/activity/whiteQueenAssist/serverScore/button_00.png",
											pressed = "ui/activity/whiteQueenAssist/serverScore/button_00.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 120,
												PositionY = 140,
											},
											UItype = "Button",
											width = "178",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "btn_label_Button_join_league_Panel_no_league_Image_ad_Panel_root_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
													UUID = "1416c6b3_0c21_4bbb_b2ce_50ee0a17e5ad",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF435FBB",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "btn_label",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Bergabung sekarang",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "117",
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
					UUID = "b888dbcc_b5a7_45ae_980e_16dbed9b20da",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 704,
						PositionY = -575,
						LeftPositon = 1148,
						TopPosition = 301,
						relativeToName = "Panel",
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
							UUID = "05d06d07_29be_4dc0_ada2_017c43a7c1c2",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "130",
							ignoreSize = "False",
							name = "Panel_reward_item",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 78,
								PositionY = 300,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "246",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_reward_1_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "4ec37ec4_fd97_4cab_8817_abacd767c6eb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "130",
									ignoreSize = "False",
									name = "Panel_reward_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 60,
										PositionY = 66,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_title_Panel_reward_1_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "e8922c97_51f3_4779_ab62_a18e1d5ac080",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF5D8DBF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_title",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1111000",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 53,
											},
											width = "110",
											ZOrder = "1",
										},
										{
											controlID = "image_bg_Panel_reward_1_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "08332d0b_c6e7_4cca_852a_1df346380d79",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "110",
											ignoreSize = "True",
											name = "image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/whiteQueenAssist/leagueScore/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -12,
											},
											width = "110",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "image_icon_image_bg_Panel_reward_1_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
													UUID = "ce2bb9f3_3403_45d4_831a_b03aa23701f0",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "64",
													ignoreSize = "True",
													name = "image_icon",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "64",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "img_geted_Panel_reward_1_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "3fa2b984_7856_4408_ae31_fbb2097a4110",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "84",
											ignoreSize = "True",
											name = "img_geted",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/whiteQueenAssist/leagueScore/img_geted.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 8,
												PositionY = -23,
											},
											width = "90",
											ZOrder = "1",
										},
										{
											controlID = "Label_get_Panel_reward_1_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "c362a485_e96b_4c80_ba97_bfcca71acb7c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFD159A9",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_get",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "领  取",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -15,
											},
											width = "59",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_reward_2_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "e6c5e3fb_499d_43c9_b9f5_5b454994ed3d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "130",
									ignoreSize = "False",
									name = "Panel_reward_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 182,
										PositionY = 66,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_title_Panel_reward_2_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "7f6cc70b_1a3a_4e3b_969a_d8f696275c93",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF5D8DBF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_title",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1111000",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 53,
											},
											width = "110",
											ZOrder = "1",
										},
										{
											controlID = "image_bg_Panel_reward_2_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "8b376e19_039f_43ef_bd18_a779f5586812",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "110",
											ignoreSize = "True",
											name = "image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/whiteQueenAssist/leagueScore/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -12,
											},
											width = "110",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "image_icon_image_bg_Panel_reward_2_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
													UUID = "a2f81316_fd1c_465a_9030_0940265d4631",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "64",
													ignoreSize = "True",
													name = "image_icon",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "64",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "img_geted_Panel_reward_2_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "35142308_1c43_424d_8552_d1dd0869dc3d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "84",
											ignoreSize = "True",
											name = "img_geted",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/whiteQueenAssist/leagueScore/img_geted.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 8,
												PositionY = -23,
											},
											width = "90",
											ZOrder = "1",
										},
										{
											controlID = "Label_get_Panel_reward_2_Panel_reward_item_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
											UUID = "e71da1aa_b935_4137_bdfa_68f201b206b2",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFD159A9",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_get",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "领  取",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -15,
											},
											width = "59",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_des_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
							UUID = "17319c68_9edb_496f_ba4b_426fb663580d",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "1",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "96",
							ignoreSize = "False",
							name = "Panel_des",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 232,
								PositionY = 226,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "442",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_title_Panel_des_Panel_prefab_Panel-whiteQueenLeagueScoreView_activityWhiteQueenEn_activity_Game",
									UUID = "12f42084_548f_4e16_8607_d1c0747b9668",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "1",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF184866",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "0",
									ignoreSize = "False",
									name = "Label_title",
									nTextAlign = "0",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "442",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/whiteQueenAssist/leagueScore/bg.png",
			"ui/activity/whiteQueenAssist/serverScore/button_00.png",
			"ui/activity/whiteQueenAssist/leagueScore/001.png",
			"ui/activity/whiteQueenAssist/leagueScore/img_geted.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

