return {
    [1] = {
        roleId = 101,
        endWeight = 40,
        id = 1,
        dress = 20,
        gift = 0,
        cgWeight = 40,
    },
    [2] = {
        roleId = 102,
        endWeight = 40,
        id = 2,
        dress = 20,
        gift = 0,
        cgWeight = 40,
    },
    [3] = {
        roleId = 103,
        endWeight = 40,
        id = 3,
        dress = 20,
        gift = 0,
        cgWeight = 40,
    },
    [4] = {
        roleId = 104,
        endWeight = 40,
        id = 4,
        dress = 20,
        gift = 0,
        cgWeight = 40,
    },
    [5] = {
        roleId = 105,
        endWeight = 40,
        id = 5,
        dress = 20,
        gift = 0,
        cgWeight = 40,
    },
    [6] = {
        roleId = 112,
        endWeight = 50,
        id = 6,
        dress = 0,
        gift = 0,
        cgWeight = 50,
    },
    [7] = {
        roleId = 113,
        endWeight = 40,
        id = 7,
        dress = 20,
        gift = 0,
        cgWeight = 40,
    },
}