local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
			UUID = "7036a364_e52f_4b2c_b688_b86edbfff4fd",
			anchorPoint = "False",
			anchorPointX = "0.5",
			anchorPointY = "0.5",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "548",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "888",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
					UUID = "ea0a1978_4277_4974_a305_39b33c61ac2f",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FF40E0D0;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "ScrollView_goods_Panel_root_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
							UUID = "5622a157_eec0_4b2c_85fa_61b6b2526b5c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "True",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "490",
							ignoreSize = "False",
							innerHeight = "490",
							innerWidth = "910",
							name = "ScrollView_goods",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 3,
								PositionY = -20,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "910",
							ZOrder = "1",
						},
						{
							controlID = "Panel_resource_Panel_root_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
							UUID = "c468c310_4ded_4689_a1d1_cabccaec1410",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "32",
							ignoreSize = "False",
							name = "Panel_resource",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -19,
								PositionY = 247,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "856",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_resource_Panel_resource_Panel_root_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
									UUID = "fc857031_17bd_4013_aca2_060ec601875c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "45",
									ignoreSize = "True",
									name = "Image_resource",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/fanshiAssist/storeActivity/01.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -271,
									},
									width = "297",
									ZOrder = "1",
								},
								{
									controlID = "Label_timing_Panel_resource_Panel_root_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
									UUID = "8e410ccb_6c47_488e_bd2f_3344d5bf0d92",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFC4C6E5",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_timing",
									nTextAlign = "1",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "End in 48d 20h",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -355,
										PositionY = 2,
									},
									width = "129",
									ZOrder = "1",
								},
								{
									controlID = "Image_gift_Panel_resource_Panel_root_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
									UUID = "c48041ba_3120_4d3d_a7bd_5998cf2b609a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "46",
									ignoreSize = "True",
									name = "Image_gift",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/assist/kuangsan/gift_001.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 353,
									},
									width = "246",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_giftActivityView_1_Panel_root_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
							UUID = "1f328cff_5f82_4c9e_a0b9_1a11b6ca3d3a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_giftActivityView_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/fanshiAssist/storeActivity/09.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 510,
								PositionY = 39,
							},
							width = "142",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
					UUID = "0cad928c_c914_4b83_98ea_df2febde885f",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "548",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 704,
						PositionY = -575,
						LeftPositon = 1148,
						TopPosition = 301,
						relativeToName = "Panel",
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "888",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
							UUID = "b81c3882_c1d3_41ee_a6de_ce810902e07b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "485",
							ignoreSize = "False",
							name = "Panel_gift",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 400,
								PositionY = 551,
								LeftPositon = 615,
								TopPosition = 740,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "263",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
									UUID = "f0f2ff78_d2ff_4c13_a33d_31dcc9c78fc9",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "500",
									ignoreSize = "True",
									name = "Image_diban",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/fanshiAssist/storeActivity/03.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "274",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_num_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "a54585f7_336a_4021_b824_97744f778422",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF431A5A",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "False",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Weekend Pack",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 214,
											},
											width = "245",
											ZOrder = "1",
										},
										{
											controlID = "Label_buyCount_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "deb73030_d6f5_4eb1_a815_c69d35682730",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_buyCount",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "TextLable",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = 179,
											},
											width = "80",
											ZOrder = "1",
										},
										{
											controlID = "Label_countdown_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "f5a1689b_0aa9_4887_ad42_064934d97ec9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_countdown",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "End in 07h 45m",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -99,
											},
											width = "134",
											ZOrder = "1",
										},
										{
											controlID = "Label_tips_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "bb0fdcc6_123f_44a2_ad5a_42fc37623eff",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "18",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "21",
											ignoreSize = "True",
											name = "Label_tips",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Chances Left",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -20,
												PositionY = -215,
											},
											width = "100",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_giftActivityView6_1_Label_tips_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
													UUID = "110578b4_b967_4716_9895_11a3a2f146ab",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "25",
													ignoreSize = "True",
													name = "Image_giftActivityView6_1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/activity/fanshiAssist/storeActivity/06.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 20,
													},
													width = "155",
													ZOrder = "-1",
												},
											},
										},
										{
											controlID = "Label_leftTime_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "37ce7125_81b9_418e_92f3_12b603068d5b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "18",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "21",
											ignoreSize = "True",
											name = "Label_leftTime",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 49,
												PositionY = -216,
											},
											width = "8",
											ZOrder = "1",
										},
										{
											controlID = "Image_title_di_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "9fe8498b_eb94_44c8_9ae1_749063b19fd9",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "47",
											ignoreSize = "True",
											name = "Image_title_di",
											scaleX = "0.7",
											scaleY = "0.7",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/recharge/7.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 131,
												PositionY = 183,
											},
											width = "131",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_title_desc1_Image_title_di_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
													UUID = "8f32876e_49f6_429b_8eb1_2e181cc2850d",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FFCA4465",
														StrokeSize = 2,
													},
													height = "33",
													ignoreSize = "True",
													name = "Label_title_desc1",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Double",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -47,
														PositionY = 4,
													},
													width = "88",
													ZOrder = "1",
												},
												{
													controlID = "Label_title_desc_Image_title_di_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
													UUID = "dceb4637_617c_4a50_9e77_ccec1de49834",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FFD7812B",
														StrokeSize = 2,
													},
													height = "33",
													ignoreSize = "True",
													name = "Label_title_desc",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "200% Reward for First Top-up",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -66,
														PositionY = 4,
													},
													visible = "False",
													width = "393",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_item_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "b38b6276_3d7a_46af_a855_eb9632a51fcf",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "200",
											ignoreSize = "False",
											name = "Panel_item",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = 40,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "211",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_reward_1_Panel_item_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
													UUID = "093e72ae_bd45_40a9_8962_d708bd64a4e6",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "80",
													ignoreSize = "False",
													name = "Image_reward_1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = -53,
														PositionY = -42,
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "80",
													ZOrder = "1",
												},
												{
													controlID = "Image_reward_2_Panel_item_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
													UUID = "17e69321_7820_44cf_963d_e1d04579a23c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "80",
													ignoreSize = "False",
													name = "Image_reward_2",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 50,
														PositionY = -42,
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "80",
													ZOrder = "1",
												},
												{
													controlID = "Image_reward_3_Panel_item_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
													UUID = "4fe0b1bb_ee7a_47e0_b93d_55fd7e9ae934",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "80",
													ignoreSize = "False",
													name = "Image_reward_3",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = -53,
														PositionY = 54,
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "80",
													ZOrder = "1",
												},
												{
													controlID = "Image_reward_4_Panel_item_Image_diban_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
													UUID = "150f4a4e_f1ac_461a_bcec_a03e796acf01",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "80",
													ignoreSize = "False",
													name = "Image_reward_4",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 50,
														PositionY = 54,
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "80",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Button_buy_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
									UUID = "b7ea53ad_1889_4735_8518_3f9edb65de59",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "84",
									ignoreSize = "True",
									name = "Button_buy",
									normal = "ui/activity/fanshiAssist/storeActivity/07.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -155,
									},
									UItype = "Button",
									width = "174",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_price_Button_buy_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "12f51d10_2abd_4816_a8d2_998aa8cc4eea",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFCF3FA1",
												StrokeSize = 1,
											},
											height = "28",
											ignoreSize = "True",
											name = "Label_price",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "¥999",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionY = -2,
											},
											width = "63",
											ZOrder = "1",
										},
										{
											controlID = "Image_exchange_Button_buy_Panel_gift_Panel_prefab_Panel-giftActivityViewFanshi_fanshiAssist_activity_Game",
											UUID = "d2b69ac3_7013_401f_a6ea_1b90c32ba6d0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "30",
											ignoreSize = "False",
											name = "Image_exchange",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -20,
												PositionY = -1,
											},
											visible = "False",
											width = "30",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/fanshiAssist/storeActivity/01.png",
			"ui/activity/assist/kuangsan/gift_001.png",
			"ui/activity/fanshiAssist/storeActivity/09.png",
			"ui/activity/fanshiAssist/storeActivity/03.png",
			"ui/activity/fanshiAssist/storeActivity/06.png",
			"ui/recharge/7.png",
			"ui/activity/fanshiAssist/storeActivity/07.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

