local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-sxBirthdayCityView_Layer1_activity_Game",
			UUID = "d40e2eb2_ab81_44bf_bed8_0f6cf8d90c6d",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "709",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1020",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "zhaungshi2_Panel-sxBirthdayCityView_Layer1_activity_Game",
					UUID = "4c1723cb_bb80_476a_8f2d_7899d06a8c1f",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					flipX = "True",
					height = "166",
					ignoreSize = "True",
					name = "zhaungshi2",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui/activity/sx_birthday/travel/5.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 837,
						PositionY = 636,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "366",
					ZOrder = "2",
				},
				{
					controlID = "zhaungshi1_Panel-sxBirthdayCityView_Layer1_activity_Game",
					UUID = "82004efd_4f1b_44a7_b090_e22027ea4d97",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "166",
					ignoreSize = "True",
					name = "zhaungshi1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui/activity/sx_birthday/travel/5.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = 635,
						TopPosition = 1,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "366",
					ZOrder = "11",
				},
				{
					controlID = "Image_bg_Panel-sxBirthdayCityView_Layer1_activity_Game",
					UUID = "78e7cc30_8e78_4fb5_b99c_0dd493114d5e",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "64",
					ignoreSize = "True",
					name = "Image_bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 510,
						PositionY = 359,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "64",
					ZOrder = "1",
				},
				{
					controlID = "Image_di_Panel-sxBirthdayCityView_Layer1_activity_Game",
					UUID = "8a309976_df2a_4448_9864_586bbf1e0050",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "Image_di",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui/activity/sx_birthday/travel/7.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					width = "717",
					ZOrder = "1",
				},
				{
					controlID = "Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
					UUID = "41f51732_bcdb_462b_bc51_ecfd15c330b2",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "255",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 510,
						PositionY = 359,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "zhuangshi_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "fbefee00_e7e4_4540_b549_5619631e22b3",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "400",
							ignoreSize = "False",
							name = "zhuangshi",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								LeftPositon = 510,
								TopPosition = -45,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "400",
							ZOrder = "1",
						},
						{
							controlID = "Image_name_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "041d1bdf_ca4e_495a_84a1_52fd6011ba87",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "42",
							ignoreSize = "True",
							name = "Image_name",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg4.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -153,
								PositionY = 218,
							},
							width = "312",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_name_Image_name_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "8caae058_3056_49a6_a426_3d203cc232f8",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF234C74",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Seaside Journey",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -124,
										PositionY = -2,
									},
									width = "99",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "36d6d64e_9c4f_48f1_8822_3a05a1fcaf1e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "138",
							ignoreSize = "False",
							name = "Panel_part_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -165,
								PositionY = 119,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "524",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_unlock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "165a5ce3_d775_4fcf_8eab_cdaa93a138e1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_unlock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "524",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_dating_Image_unlock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "4f0c3f45_7259_46a9_a0c8_431f029cb12e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "57",
											HitType = 
											{
												nHitType = 3,
											},
											ignoreSize = "True",
											name = "Button_dating",
											normal = "ui/activity/sx_birthday/travel/SXSR_YH_button_2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 182,
												PositionY = -29,
											},
											UItype = "Button",
											width = "101",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_dating_Button_dating_Image_unlock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
													UUID = "31676bd1_7573_48c6_94de_54c1547f38c9",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "30",
													ignoreSize = "True",
													name = "Label_dating",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Date",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionY = -3,
													},
													width = "51",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Image_lock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "93ad643c_500c_4117_9dd3_e071573d4a78",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "524",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_lock2_Image_lock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "5ee96a18_357b_44b3_9d69_78728538d7cf",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_lock2",
											scaleX = "0.6",
											scaleY = "0.6",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/lock2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 223,
												PositionY = 2,
											},
											visible = "False",
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Image_order_lock_Image_lock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "e3581a59_f06b_4ac7_b51b_b318bfe334b4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "116",
											ignoreSize = "True",
											name = "Image_order_lock",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -206,
											},
											width = "122",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_order_lock_Image_order_lock_Image_lock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
													UUID = "5d6d8471_501e_49d4_9cde_5ee57058b67c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFB685B8",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "36",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "45",
													ignoreSize = "True",
													name = "Label_order_lock",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "1",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "22",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Image_complete_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "e3a5b2f9_559b_40da_9a8d_8e5d42477f3d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_complete",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "524",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "a558cce3_2f05_4d03_8fc7_7ecbe123b77c",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_CG_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -232,
										PositionY = 2,
									},
									width = "137",
									ZOrder = "1",
								},
								{
									controlID = "Image_order_unlock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "35c4062d_87be_450c_b74f_c479f76d7a41",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "116",
									ignoreSize = "True",
									name = "Image_order_unlock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -224,
										PositionY = 17,
									},
									visible = "False",
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_order_unlock_Image_order_unlock_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "04fd1245_793d_4a0c_864e_f76ad9290290",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF57ABE5",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "36",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "45",
											ignoreSize = "True",
											name = "Label_order_unlock",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "22",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_order_complete_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "ee42ca51_d6b6_451b_88b8_d3b56607c514",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "116",
									ignoreSize = "True",
									name = "Image_order_complete",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -224,
										PositionY = 17,
									},
									visible = "False",
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_order_complete_Image_order_complete_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "e1f97fda_f08e_4748_9eaa_6546d9a1d098",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF57ABE5",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "36",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "45",
											ignoreSize = "True",
											name = "Label_order_complete",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "22",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_part_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "c17109cb_67f1_4284_9009_41263c950ae7",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_part",
									nTextAlign = "1",
									nTextHAlign = "1",
									rotation = "-15",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "1",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -207,
										PositionY = -40,
									},
									width = "14",
									ZOrder = "1",
								},
								{
									controlID = "Label_title_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "ce3cd475_0627_4485_8af8_d5e8dd94c6b7",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF2B2955",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_title",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Complete Event",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -153,
										PositionY = 30,
									},
									width = "91",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc_Panel_part_1_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "c6a8ea96_9e1c_433a_8742_2619b25a2428",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF49557F",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "46",
									ignoreSize = "False",
									name = "Label_desc",
									nTextAlign = "0",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Description",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -153,
										PositionY = -21,
									},
									width = "252",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "a5b839f2_4de4_46a9_89e6_f8e8918c862e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "138",
							ignoreSize = "False",
							name = "Panel_part_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -105,
								PositionY = -21,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "524",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_unlock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "3765df95_944c_4ebe_9537_43c44a27fcc4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_unlock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "524",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_dating_Image_unlock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "3f8df7c6_fb4e_4a62_b209_d1091e8f3d86",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "57",
											HitType = 
											{
												nHitType = 3,
											},
											ignoreSize = "True",
											name = "Button_dating",
											normal = "ui/activity/sx_birthday/travel/SXSR_YH_button_2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 182,
												PositionY = -29,
											},
											UItype = "Button",
											width = "101",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_dating_Button_dating_Image_unlock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
													UUID = "9c15734f_77cb_4658_8830_eca73c3e73b3",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "30",
													ignoreSize = "True",
													name = "Label_dating",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Date",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionY = -3,
													},
													width = "51",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Image_lock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "2df2d5f4_d9c8_4b6f_a55c_fee84705e493",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "524",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_lock2_Image_lock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "468915ff_d405_42cf_8dd5_c4f013c0098f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_lock2",
											scaleX = "0.6",
											scaleY = "0.6",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/lock2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 223,
												PositionY = 2,
											},
											visible = "False",
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Image_order_lock_Image_lock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "658750e9_a6e3_4a88_95a7_f68dd262211f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "116",
											ignoreSize = "True",
											name = "Image_order_lock",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -206,
											},
											visible = "False",
											width = "122",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_order_lock_Image_order_lock_Image_lock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
													UUID = "81f5b77e_f950_46b1_bc29_efae9911c016",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFB685B8",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "36",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "45",
													ignoreSize = "True",
													name = "Label_order_lock",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "1",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "22",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Image_complete_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "6c34d2ea_4da3_4402_b47a_289f0be6330b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_complete",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "524",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "8d1de3d9_5206_43de_9e53_3c95248e19a1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_CG_2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -232,
									},
									width = "137",
									ZOrder = "1",
								},
								{
									controlID = "Image_order_unlock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "b00b173d_2afd_40e9_9af6_8bd13d5bf9ac",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "116",
									ignoreSize = "True",
									name = "Image_order_unlock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -219,
										PositionY = 11,
									},
									visible = "False",
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_order_unlock_Image_order_unlock_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "f41e5418_04a8_46f4_959e_cf26ba2d56c5",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF57ABE5",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "36",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "45",
											ignoreSize = "True",
											name = "Label_order_unlock",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "22",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_order_complete_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "dabd6bc7_efe4_4f59_8127_6b0ef5cd8deb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "116",
									ignoreSize = "True",
									name = "Image_order_complete",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -219,
										PositionY = 13,
									},
									visible = "False",
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_order_complete_Image_order_complete_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "1c4c088f_7497_43a3_8627_b44493c27d93",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF57ABE5",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "36",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "45",
											ignoreSize = "True",
											name = "Label_order_complete",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "22",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_part_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "ae73c99b_5258_4e1a_a951_714d32dd7239",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_part",
									nTextAlign = "1",
									nTextHAlign = "1",
									rotation = "-15",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "2",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -207,
										PositionY = -41,
									},
									width = "18",
									ZOrder = "1",
								},
								{
									controlID = "Label_title_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "24887877_4e1d_4917_ac9b_2cb8db12a0e0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF2B2955",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_title",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Complete Event",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -153,
										PositionY = 30,
									},
									width = "91",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc_Panel_part_2_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "60c0af99_d0c0_446a_ae40_59e7a21413b2",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF49557F",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "46",
									ignoreSize = "False",
									name = "Label_desc",
									nTextAlign = "0",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Description",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -153,
										PositionY = -21,
									},
									width = "252",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "9c43302e_83bf_4b90_82fc_64aa66482d8b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "138",
							ignoreSize = "False",
							name = "Panel_part_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -41,
								PositionY = -162,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "524",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_unlock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "8a24c611_d476_4856_9abe_a38143c32507",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_unlock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "524",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_dating_Image_unlock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "76912795_b337_46fe_9ef0_714c351ad081",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "57",
											HitType = 
											{
												nHitType = 3,
											},
											ignoreSize = "True",
											name = "Button_dating",
											normal = "ui/activity/sx_birthday/travel/SXSR_YH_button_2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 182,
												PositionY = -28,
											},
											UItype = "Button",
											width = "101",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_dating_Button_dating_Image_unlock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
													UUID = "abe7e4eb_965d_4083_b4e6_1ea5efd170b8",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "30",
													ignoreSize = "True",
													name = "Label_dating",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Date",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionY = -3,
													},
													width = "51",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Image_lock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "465df90e_2d20_4396_a5a4_8e05eb8e0ed0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "524",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_lock2_Image_lock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "19709597_62c9_4c81_92e8_17362467417e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_lock2",
											scaleX = "0.6",
											scaleY = "0.6",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fuben/lock2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 223,
												PositionY = 2,
											},
											visible = "False",
											width = "100",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_complete_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "27662280_ad5e_440e_9d28_b78a3007c98b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_complete",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "524",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "15d57973_5cc0_48fe_88b0_5de8ac23dc71",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "149",
									ignoreSize = "True",
									name = "Image_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_CG_3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -232,
									},
									width = "137",
									ZOrder = "1",
								},
								{
									controlID = "Image_order_unlock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "7921f89e_05ac_499e_8962_60dd73d35463",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "116",
									ignoreSize = "True",
									name = "Image_order_unlock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -206,
									},
									visible = "False",
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_order_unlock_Image_order_unlock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "f2f984b7_7ae1_4d39_8cf2_e7710a93ee8d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF57ABE5",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "36",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "45",
											ignoreSize = "True",
											name = "Label_order_unlock",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "22",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_order_lock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "3d4104b4_9709_49ce_95f2_ba4a8279f7c3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "116",
									ignoreSize = "True",
									name = "Image_order_lock",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -206,
									},
									visible = "False",
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_order_lock_Image_order_lock_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "c9de71d4_c18f_4bd9_8d87_0dfacd81710e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFB685B8",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "36",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "45",
											ignoreSize = "True",
											name = "Label_order_lock",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "22",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_order_complete_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "1440d557_e4a0_4b18_b896_bdbabd17c974",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "116",
									ignoreSize = "True",
									name = "Image_order_complete",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg_3_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -206,
									},
									visible = "False",
									width = "122",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_order_complete_Image_order_complete_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
											UUID = "fbf66d8c_b9a6_4fcd_87ad_e63f9f721818",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF57ABE5",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "36",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "45",
											ignoreSize = "True",
											name = "Label_order_complete",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "1",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "22",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_part_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "1e4691c7_73b4_4794_be73_c8a7eacdaf65",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_part",
									nTextAlign = "1",
									nTextHAlign = "1",
									rotation = "-15",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "3",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -207,
										PositionY = -41,
									},
									width = "18",
									ZOrder = "1",
								},
								{
									controlID = "Label_title_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "b86257b0_b976_41cf_9475_32e2748d58d5",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF2B2955",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_title",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Complete Event",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -153,
										PositionY = 30,
									},
									width = "91",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc_Panel_part_3_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "34a1973c_9214_4597_ac9b_579809248700",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF49557F",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "46",
									ignoreSize = "False",
									name = "Label_desc",
									nTextAlign = "0",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Description",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -153,
										PositionY = -21,
									},
									width = "252",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Image_zd_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "e6717add_8509_4ef2_9f76_d3e78b9433eb",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_zd",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/dating/1214Dating/day/021.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -693,
							},
							visible = "False",
							width = "702",
							ZOrder = "1",
						},
						{
							controlID = "Image_place_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "9e869fd5_cf93_4a7b_9c64_5466f1dc9f6c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "71",
							ignoreSize = "True",
							name = "Image_place",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/sx_birthday/travel/4.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1,
								PositionY = -275,
							},
							width = "1386",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_place_Image_place_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "42dc815b_df0b_4c4f_ad6f_9656aa1472b8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF5D6078",
										StrokeSize = 1,
									},
									height = "32",
									ignoreSize = "True",
									name = "Label_place",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Location Name 5",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -478,
										PositionY = -2,
									},
									width = "126",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc_Image_place_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "a6cbaba8_9433_4e83_baf9_10008a2c26ef",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF5D6078",
										StrokeSize = 1,
									},
									height = "54",
									ignoreSize = "False",
									name = "Label_desc",
									nTextAlign = "1",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Description Text",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -379,
									},
									width = "292",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Label_get_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "04dff676_fa8d_44b2_8477_003c1b84ee0e",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "font/MFLiHei_Noncommercial.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF5D6078",
								StrokeSize = 1,
							},
							height = "29",
							ignoreSize = "True",
							name = "Label_get",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "You may get",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 11,
								PositionY = -277,
							},
							width = "90",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_sxBirthdayCityView_1_Label_get_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "c0b6975a_4fa0_4658_af0b_3e3406fc97ea",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "30",
									ignoreSize = "True",
									name = "Image_sxBirthdayCityView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg6.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 100,
										PositionY = 2,
									},
									visible = "False",
									width = "18",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "ScrollView_reward_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "c3cf127a_9f74_446e_95c5_5b73355c0c3e",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							bounceEnable = "False",
							classname = "MEScrollView",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							direction = "2",
							dstBlendFunc = "771",
							height = "75",
							ignoreSize = "False",
							innerHeight = "75",
							innerWidth = "290",
							name = "ScrollView_reward",
							showScrollbar = "False",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 121,
								PositionY = -274,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "290",
							ZOrder = "1",
						},
						{
							controlID = "Image_cost_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "2981215c_b9c9_4137_a65e_11e7f94b7e32",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "71",
							ignoreSize = "True",
							name = "Image_cost",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/sx_birthday/travel/SXSR_YH_bg7.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 483,
								PositionY = -275,
							},
							width = "144",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Label_cost_num_Image_cost_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "ff0fee0d_d96f_49e0_9a3d_88a4f3d60dfb",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "24",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF5D6078",
										StrokeSize = 1,
									},
									height = "29",
									ignoreSize = "True",
									name = "Label_cost_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "5",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 1,
										PositionY = -20,
									},
									width = "16",
									ZOrder = "1",
								},
								{
									controlID = "Image_cost_icon_Image_cost_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
									UUID = "47ff8904_56ad_4518_8b94_a67fbeedbcf3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_cost_icon",
									scaleX = "0.3",
									scaleY = "0.3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/system/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -9,
										PositionY = -19,
									},
									width = "100",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Button_explore_Panel_root_Panel-sxBirthdayCityView_Layer1_activity_Game",
							UUID = "8a1859d4_4ee1_422f_bf68_d1695ce967ef",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "129",
							ignoreSize = "True",
							name = "Button_explore",
							normal = "ui/activity/sx_birthday/travel/btn_explore.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 484,
								PositionY = -222,
								LeftPositon = 1567,
								TopPosition = 175,
								relativeToName = "Panel",
							},
							UItype = "Button",
							width = "123",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-sxBirthdayCityView_Layer1_activity_Game",
					UUID = "d194ea2e_c342_41c8_add1_84b5a288f7fb",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					opacity = "177",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 510,
						PositionY = 359,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					visible = "False",
					width = "2000",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/sx_birthday/travel/5.png",
			"ui/activity/sx_birthday/travel/7.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg4.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg2.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_button_2.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg1.png",
			"ui/fuben/lock2.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg_3_2.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg3.png",
			"ui/activity/sx_birthday/travel/SXSR_CG_1.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg_3_1.png",
			"ui/activity/sx_birthday/travel/SXSR_CG_2.png",
			"ui/activity/sx_birthday/travel/SXSR_CG_3.png",
			"ui/dating/1214Dating/day/021.png",
			"ui/activity/sx_birthday/travel/4.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg6.png",
			"ui/activity/sx_birthday/travel/SXSR_YH_bg7.png",
			"icon/system/005.png",
			"ui/activity/sx_birthday/travel/btn_explore.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

