return {
    [1301] = {
        nextGuideId = 1302,
        action = "Id_happy",
        id = 1301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [2301] = {
        nextGuideId = 2302,
        action = "Id_happy",
        id = 2301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [7301] = {
        nextGuideId = 7302,
        action = "Id_happy",
        id = 7301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [7302] = {
        nextGuideId = 7303,
        action = "Id_happy",
        id = 7302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [2302] = {
        nextGuideId = 2303,
        action = "Id_happy",
        id = 2302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [1302] = {
        nextGuideId = 1303,
        action = "Id_happy",
        id = 1302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [401] = {
        nextGuideId = 402,
        action = "Id_dress",
        id = 401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [2303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 2303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [5401] = {
        nextGuideId = 5402,
        action = "Id_dress",
        id = 5401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [5402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 5402,
        modelId = 210507,
        talkPos = 2,
        desc = "Invertierte Origami exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
    [302] = {
        nextGuideId = 303,
        action = "Id_happy",
        id = 302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [8202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 8202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [6102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 6102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [2401] = {
        nextGuideId = 2402,
        action = "Id_dress",
        id = 2401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [7501] = {
        nextGuideId = 7502,
        action = "Id_happy",
        id = 7501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [7502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 7502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [2402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 2402,
        modelId = 210507,
        talkPos = 2,
        desc = "Blancs exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
    [4201] = {
        nextGuideId = 4202,
        action = "Id_dress",
        id = 4201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Purpurroter Alptraum ausgerüstet hast.",
    },
    [3101] = {
        nextGuideId = 3102,
        action = "Id_dress",
        id = 3101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [4202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 4202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [3102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 3102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [501] = {
        nextGuideId = 502,
        action = "Id_happy",
        id = 501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [6301] = {
        nextGuideId = 6302,
        action = "Id_happy",
        id = 6301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [1401] = {
        nextGuideId = 1402,
        action = "Id_dress",
        id = 1401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [6303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 6303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [2501] = {
        nextGuideId = 2502,
        action = "Id_happy",
        id = 2501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [2502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 2502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [1402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 1402,
        modelId = 210507,
        talkPos = 2,
        desc = "Neptunes exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
    [3201] = {
        nextGuideId = 3202,
        action = "Id_dress",
        id = 3201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Invertierte Tohka ausgerüstet hast.",
    },
    [4402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 4402,
        modelId = 210507,
        talkPos = 2,
        desc = "Dieses Souvenir hat einen besonderen Bond-Effekt.",
    },
    [303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [5102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 5102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [6501] = {
        nextGuideId = 6502,
        action = "Id_happy",
        id = 6501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [6502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 6502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [7201] = {
        nextGuideId = 7202,
        action = "Id_dress",
        id = 7201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Noire ausgerüstet hast.",
    },
    [1102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 1102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [7202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 7202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [8501] = {
        nextGuideId = 8502,
        action = "Id_happy",
        id = 8501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [8502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 8502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [3301] = {
        nextGuideId = 3302,
        action = "Id_happy",
        id = 3301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [5301] = {
        nextGuideId = 5302,
        action = "Id_happy",
        id = 5301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [3302] = {
        nextGuideId = 3303,
        action = "Id_happy",
        id = 3302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [7303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 7303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [5303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 5303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [8401] = {
        nextGuideId = 8402,
        action = "Id_dress",
        id = 8401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [3303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 3303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [8303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 8303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [1501] = {
        nextGuideId = 1502,
        action = "Id_happy",
        id = 1501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [7401] = {
        nextGuideId = 7402,
        action = "Id_dress",
        id = 7401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [1303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 1303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [7402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 7402,
        modelId = 210507,
        talkPos = 2,
        desc = "Invertierte Origami exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
    [8101] = {
        nextGuideId = 8102,
        action = "Id_dress",
        id = 8101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [4101] = {
        nextGuideId = 4102,
        action = "Id_dress",
        id = 4101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [8102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 8102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [4102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 4102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [1502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 1502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [3401] = {
        nextGuideId = 3402,
        action = "Id_dress",
        id = 3401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [1201] = {
        nextGuideId = 1202,
        action = "Id_dress",
        id = 1201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Neptune ausgerüstet hast.",
    },
    [5501] = {
        nextGuideId = 5502,
        action = "Id_happy",
        id = 5501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [8201] = {
        nextGuideId = 8202,
        action = "Id_dress",
        id = 8201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Vert ausgerüstet hast.",
    },
    [3402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 3402,
        modelId = 210507,
        talkPos = 2,
        desc = "Invertierte Tohka exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
    [6201] = {
        nextGuideId = 6202,
        action = "Id_dress",
        id = 6201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Mayuri ausgerüstet hast.",
    },
    [8402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 8402,
        modelId = 210507,
        talkPos = 2,
        desc = "Invertierte Origami exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
    [2101] = {
        nextGuideId = 2102,
        action = "Id_dress",
        id = 2101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [3501] = {
        nextGuideId = 3502,
        action = "Id_happy",
        id = 3501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [7101] = {
        nextGuideId = 7102,
        action = "Id_dress",
        id = 7101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [6402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 6402,
        modelId = 210507,
        talkPos = 2,
        desc = "Invertierte Origami exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
    [2102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 2102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [1202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 1202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [3202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 3202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [6302] = {
        nextGuideId = 6303,
        action = "Id_happy",
        id = 6302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [4301] = {
        nextGuideId = 4302,
        action = "Id_happy",
        id = 4301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [6202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 6202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [4302] = {
        nextGuideId = 4303,
        action = "Id_happy",
        id = 4302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [6101] = {
        nextGuideId = 6102,
        action = "Id_dress",
        id = 6101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [4303] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 4303,
        modelId = 210507,
        talkPos = 1,
        desc = "Außerdem sind sie mit verschiedenen passiven Voreinstellungen ausgestattet. Probier sie jetzt aus!",
    },
    [201] = {
        nextGuideId = 202,
        action = "Id_dress",
        id = 201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Invertierte Origami ausgerüstet hast.",
    },
    [102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [5502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 5502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [3502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 3502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [6401] = {
        nextGuideId = 6402,
        action = "Id_dress",
        id = 6401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [5302] = {
        nextGuideId = 5303,
        action = "Id_happy",
        id = 5302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [2201] = {
        nextGuideId = 2202,
        action = "Id_dress",
        id = 2201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Blanc ausgerüstet hast.",
    },
    [301] = {
        nextGuideId = 302,
        action = "Id_happy",
        id = 301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [1101] = {
        nextGuideId = 1102,
        action = "Id_dress",
        id = 1101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [7102] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 7102,
        modelId = 210507,
        talkPos = 2,
        desc = "Probieren wir sie auf der nächsten Stufe aus!",
    },
    [2202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 2202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [101] = {
        nextGuideId = 102,
        action = "Id_dress",
        id = 101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [8301] = {
        nextGuideId = 8302,
        action = "Id_happy",
        id = 8301,
        modelId = 210507,
        talkPos = 1,
        desc = "Großartig. Jetzt habt ihr drei verschiedene voreingestellte Fähigkeitsbäume für Engel freigeschaltet.",
    },
    [8302] = {
        nextGuideId = 8303,
        action = "Id_happy",
        id = 8302,
        modelId = 210507,
        talkPos = 2,
        desc = "Diese Voreinstellungen können deine Fähigkeiten in verschiedene Richtungen verstärken.",
    },
    [4501] = {
        nextGuideId = 4502,
        action = "Id_happy",
        id = 4501,
        modelId = 210507,
        talkPos = 1,
        desc = "Mit Edelsteinen können die Effekte deiner Fähigkeiten noch verstärkt werden.",
    },
    [5101] = {
        nextGuideId = 5102,
        action = "Id_dress",
        id = 5101,
        modelId = 210507,
        talkPos = 1,
        desc = "Unsere Geister haben jetzt viel höhere Basis-Attribute!",
    },
    [4502] = {
        nextGuideId = 0,
        action = "Id_happy",
        id = 4502,
        modelId = 210507,
        talkPos = 2,
        desc = "In Ordnung! Ich habe dir alle Tipps und Tricks beigebracht, geh und probiere sie selbst aus!",
    },
    [5201] = {
        nextGuideId = 5202,
        action = "Id_dress",
        id = 5201,
        modelId = 210507,
        talkPos = 1,
        desc = "Es scheint, dass du das spezielle Sephira für Mikoto Misaka ausgerüstet hast.",
    },
    [4401] = {
        nextGuideId = 4402,
        action = "Id_dress",
        id = 4401,
        modelId = 210507,
        talkPos = 1,
        desc = "Auch Souvenirs erhöhen deine KK effektiv.",
    },
    [5202] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 5202,
        modelId = 210507,
        talkPos = 2,
        desc = "Übrigens können Set-Effekte eine gute Hilfe in Kämpfen sein.",
    },
    [402] = {
        nextGuideId = 0,
        action = "Id_dress",
        id = 402,
        modelId = 210507,
        talkPos = 2,
        desc = "Invertierte Origami exklusives Souvenir. Es hat einen besonderen Bond-Effekt.",
    },
}