---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/7/24 0024 20:14
---

local FavorInfoView =  class("FavorInfoView", BaseLayer)

function FavorInfoView:initData(data)
    self.roleId = RoleDataMgr:getUseId()
    self.favorLevel = RoleDataMgr:getFavorLevel(self.roleId)

    self.pos = data.pos
end

function FavorInfoView:ctor(data)
    self.super.ctor(self)

    self:initData(data)
    self:init("lua.uiconfig.common.favorInfoView")
end

function FavorInfoView:initUI(ui)
    self.super.initUI(self, ui)

    self.Image_bottom = TFDirector:getChildByPath(ui, "Image_bottom")
    self.LoadingBar_favor = TFDirector:getChildByPath(self.Image_bottom, "LoadingBar_favor")
    self.Label_favorValue = TFDirector:getChildByPath(self.Image_bottom, "Label_favorValue")
    self.Image_enter = TFDirector:getChildByPath(self.Image_bottom, "Image_enter")

    self.Image_bottom:Pos(self.pos)
    self.LoadingBar_favor:setPercent(RoleDataMgr:getFavorPercent(self.roleId))
    self.Label_favorValue:setText(self.favorLevel)

end

function FavorInfoView:registerEvents()
    self.Image_enter:Touchable(true)
    self.Image_enter:onClick(function()

    end)
end

return FavorInfoView
