local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-baoshiChooselView_Layer1_fairyNew_Game",
			UUID = "50db47b0_68ed_4740_8f89_7e32aa31f3a5",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
					UUID = "eba00182_250c_4484_869c_317e2c379354",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_base",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 125,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "background_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
							UUID = "98b22ee5_9949_4082_9008_dfb46163e595",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "background",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "scene/bg/bg_common.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 568,
								PositionY = 320,
								IsPercent = true,
								PercentX = 50,
								PercentY = 50,
							},
							width = "1386",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_b2_background_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
									UUID = "3b190330_4fe2_4d27_b4bb_47f06b439e0d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "640",
									ignoreSize = "True",
									name = "Image_b2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/new_ui/new_bg_04.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -693,
										IsPercent = true,
										PercentX = -50,
									},
									width = "1386",
									ZOrder = "1",
								},
								{
									controlID = "Image_b2(2)_background_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
									UUID = "bb31ce91_6414_4aec_8408_98a05b9a9bf6",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "2",
									ignoreSize = "True",
									name = "Image_b2(2)",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									texturePath = "ui/Equipment/new_ui/12.jpg",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -693,
										IsPercent = true,
										PercentX = -50,
									},
									width = "2",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
							UUID = "82535f96_3d1d_40aa_b3e8_da0b36ebf7b4",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "Panel_left",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "560",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
									UUID = "00c2ce87_b21f_4872_884f_5d35d0defd82",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "640",
									ignoreSize = "False",
									name = "Panel_pos",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "600",
									ZOrder = "2",
									components = 
									{
										
										{
											controlID = "Spine_down_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "36353d6a_b58d_459d_a63e_136171f4d427",
											classname = "MESpine",
											dstBlendFunc = "771",
											name = "Spine_down",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											spineModel = 
											{
												SpinePath = "effect/ui_stone_bg/ui_stone_bg",
												animationName = "BG_down",
												IsLoop = true,
												IsPlay = true,
												IsUseQueue = false,
												AnimationQueue = 
												{
													
												},
											},
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 301,
												PositionY = 291,
											},
											ZOrder = "1",
										},
										{
											controlID = "Spine_up_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "6b1ee60a_fc2f_4504_9b40_3fe43bfa08c1",
											classname = "MESpine",
											dstBlendFunc = "771",
											name = "Spine_up",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											spineModel = 
											{
												SpinePath = "effect/ui_stone_bg/ui_stone_bg",
												animationName = "BG_up",
												IsLoop = true,
												IsPlay = true,
												IsUseQueue = false,
												AnimationQueue = 
												{
													
												},
											},
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 301,
												PositionY = 291,
											},
											ZOrder = "1",
										},
										{
											controlID = "Image_angel_icon_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "c4c2512a_115a_43b7_a716_cc8596b94059",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "180",
											ignoreSize = "True",
											name = "Image_angel_icon",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fairy/new_ui/baoshi/skill_icon.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 301,
												PositionY = 291,
											},
											width = "180",
											ZOrder = "1",
										},
										{
											controlID = "Panel_pos_1_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "f2a1e088_529d_4202_93e9_5770269edfa4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "False",
											name = "Panel_pos_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 206,
												PositionY = 371,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "120",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_add_Panel_pos_1_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "c0a9f83a_9f46_4d6d_99e3_164fec2650ed",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_add",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/020.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_select_Panel_pos_1_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "7587804f_c09c_4f52_90cf_5ecddc33818a",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "160",
													ignoreSize = "True",
													name = "Image_select",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/019.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "160",
													ZOrder = "1",
												},
												{
													controlID = "Image_bg_Panel_pos_1_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "e8c1830d_16fa_45ea_ba71_73cb74f0e454",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/008.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_bg_Panel_pos_1_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "0a429cf7_b066_417e_9863_00f762fae32f",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_quality_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/009.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "42",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_Panel_pos_1_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "7e72444c_92d7_4928_8d18_d532f66c9a8b",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "159",
													ignoreSize = "True",
													name = "Image_quality",
													rotation = "32",
													scaleX = "0.1",
													scaleY = "0.1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/common/hero/quality_aa.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "225",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_pos_1_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "b8d18732_e3ce_4099_bbcb_6b8b9f899549",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "100",
													ignoreSize = "True",
													name = "Image_icon",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/item/goods/510201.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "100",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_pos_2_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "8968a971_6c7f_4235_ab2a_da7a610635d6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "False",
											name = "Panel_pos_2",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 206,
												PositionY = 220,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "120",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_add_Panel_pos_2_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "117d2621_83f2_4c7b_97f7_a4c7c69db03c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_add",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/020.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_select_Panel_pos_2_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "1593e0cc_eb24_4118_a58b_8fad9d5da47c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "160",
													ignoreSize = "True",
													name = "Image_select",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/019.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "160",
													ZOrder = "1",
												},
												{
													controlID = "Image_bg_Panel_pos_2_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "e8961005_3718_4e67_834f_6002a8d71d22",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/008.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_bg_Panel_pos_2_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "579433b1_6a1a_459f_bf2d_c1af22b7ba48",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_quality_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/009.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "42",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_Panel_pos_2_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "3845212e_ba1d_489f_a789_361619d5b98c",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "159",
													ignoreSize = "True",
													name = "Image_quality",
													rotation = "32",
													scaleX = "0.1",
													scaleY = "0.1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/common/hero/quality_aa.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "225",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_pos_2_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "91783732_9590_4341_a01e_acf6564576a3",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "100",
													ignoreSize = "True",
													name = "Image_icon",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/item/goods/510201.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "100",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_pos_3_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "1d7ffd0d_6983_4aca_8d7e_77c81d506759",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "False",
											name = "Panel_pos_3",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 399,
												PositionY = 220,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "120",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_add_Panel_pos_3_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "35ba8acf_e7b1_4ae2_8091_c8834ea47ffa",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_add",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/020.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_select_Panel_pos_3_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "cfbe5e25_dd9b_49d4_9154_6b9f7685f7fc",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "160",
													ignoreSize = "True",
													name = "Image_select",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/019.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "160",
													ZOrder = "1",
												},
												{
													controlID = "Image_bg_Panel_pos_3_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "85aa162f_9186_417e_bba5_8be27ba59b8f",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/008.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_bg_Panel_pos_3_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "f2a80ecf_2dc1_43a8_a6c7_af422ead5b01",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_quality_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/009.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "42",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_Panel_pos_3_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "4c6bc6da_5488_4644_828c_19e9daec3e98",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "159",
													ignoreSize = "True",
													name = "Image_quality",
													rotation = "32",
													scaleX = "0.1",
													scaleY = "0.1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/common/hero/quality_aa.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "225",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_pos_3_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "6e06b963_7fe1_47f6_8bde_c6904e78f699",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "100",
													ignoreSize = "True",
													name = "Image_icon",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/item/goods/510201.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "100",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_pos_4_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "d76ad7e5_071d_4eb5_9d71_646fb764854e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "False",
											name = "Panel_pos_4",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 399,
												PositionY = 371,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "120",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_add_Panel_pos_4_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "681728db_531b_4283_93dc_01b91aa959ad",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_add",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/020.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_select_Panel_pos_4_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "0e6ec533_2d29_4cbe_b1b8_1a76438e6fba",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "160",
													ignoreSize = "True",
													name = "Image_select",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/019.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "160",
													ZOrder = "1",
												},
												{
													controlID = "Image_bg_Panel_pos_4_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "398f7714_4aa6_4e6f_b780_bd48b67b9a18",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "120",
													ignoreSize = "True",
													name = "Image_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/008.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_bg_Panel_pos_4_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "5b69e60f_b5b0_4e6a_b9b4_fa81190d094a",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_quality_bg",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/009.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "42",
													ZOrder = "1",
												},
												{
													controlID = "Image_quality_Panel_pos_4_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "f51b6535_b1bc_4df5_b20f_e5de51bf79f6",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "159",
													ignoreSize = "True",
													name = "Image_quality",
													rotation = "32",
													scaleX = "0.1",
													scaleY = "0.1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/common/hero/quality_aa.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 25,
														PositionY = 42,
													},
													width = "225",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_pos_4_Panel_pos_Panel_left_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "9338d6fe_fb37_4e3b_9241_4a2480a02298",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "100",
													ignoreSize = "True",
													name = "Image_icon",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/item/goods/510201.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "100",
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
						{
							controlID = "Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
							UUID = "e9a63e4b_d5ef_436f_9dd0_90641749f746",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "Panel_right",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 565,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "570",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
									UUID = "ea61618c_2bb1_44f1_8fd2_d5da53f470fb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "576",
									ignoreSize = "False",
									name = "Image_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/new_ui/rightBG.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 327,
									},
									width = "630",
									ZOrder = "1",
								},
								{
									controlID = "Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
									UUID = "f8de130d_ae3c_4f3e_aea5_78ca010d19fd",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "489",
									ignoreSize = "False",
									name = "Panel_detail",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -8,
										PositionY = 80,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "570",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_detail_name_Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "8686a89b_db1c_4f60_bcaf_9a99e7744ac1",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "False",
											name = "Panel_detail_name",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 25,
												PositionY = 445,
												relativeToName = "Panel",
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "400",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_name_Panel_detail_name_Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "10477b2c_be27_462e_a56d_5b007f02be25",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "28",
													ignoreSize = "True",
													name = "Label_name",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Pilih Gem",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 15,
														PositionY = 21,
													},
													width = "115",
													ZOrder = "1",
												},
												{
													controlID = "Label_EnglishName_Panel_detail_name_Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "f39a986a_e12b_463a_b6dc_a4c3edd2a2e6",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "phanta.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "12",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "14",
													ignoreSize = "True",
													name = "Label_EnglishName",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Choose the gem",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 15,
													},
													visible = "False",
													width = "83",
													ZOrder = "1",
												},
												{
													controlID = "Image_info_line_Panel_detail_name_Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "1e24b878_4aa7_44c0_adf0_8e7c03f0ec9b",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "45",
													ignoreSize = "False",
													name = "Image_info_line",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/new_34.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 10,
														PositionY = 17,
													},
													width = "4",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Image_mid_bg_Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "c9f17cf7_d3b2_4c51_8848_7f329f109b51",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "420",
											ignoreSize = "False",
											name = "Image_mid_bg",
											opacity = "100",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/1763.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 35,
												PositionY = 217,
											},
											width = "540",
											ZOrder = "1",
										},
										{
											controlID = "ScrollView_items_Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "74f2c2e9_60a5_4fca_8919_1f06775289b3",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											bounceEnable = "True",
											classname = "MEScrollView",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											direction = "1",
											dstBlendFunc = "771",
											height = "410",
											ignoreSize = "False",
											innerHeight = "410",
											innerWidth = "536",
											name = "ScrollView_items",
											showScrollbar = "False",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 35,
												PositionY = 11,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "536",
											ZOrder = "1",
										},
										{
											controlID = "Label_no_gems_Panel_detail_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "1118829b_4baf_4920_a707_caf020087625",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_no_gems",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "TextLable",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 280,
												PositionY = 250,
											},
											width = "88",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
									UUID = "350a9d07_e2c1_40d1_b9ac_371bb292fe28",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "80",
									ignoreSize = "False",
									name = "Panel_di",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -8,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "570",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Button_sort_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "f6ff3c22_1f69_4fa8_8a95_78dbf9934cfa",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "55",
											HitType = 
											{
												nHitType = 3,
											},
											ignoreSize = "False",
											name = "Button_sort",
											normal = "ui/common/button_big_blue_n.png",
											pressed = "ui/common/button_big_blue_n.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 63,
												PositionY = 40,
											},
											UItype = "Button",
											width = "55",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_baoshiChooselView_1_Button_sort_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "41b77323_df60_47dd_aad3_534effeea60e",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_baoshiChooselView_1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/033.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_change_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "67532356_6346_4dbd_8109_9dc67d9e9a9c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "58",
											HitType = 
											{
												nHitType = 3,
											},
											ignoreSize = "True",
											name = "Button_change",
											normal = "ui/fairy/new_ui/new_12.png",
											pressed = "ui/fairy/new_ui/new_12.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 509,
												PositionY = 40,
											},
											UItype = "Button",
											width = "134",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_change_Button_change_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "f201b644_9da3_4df7_b531_81e0f7ce8707",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "0",
													ignoreSize = "False",
													name = "Label_change",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Konfirmasi Ubah",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "120",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_drop_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "92e7f8f8_d222_4c8c_9e5c_b06ccc79ffb3",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "58",
											HitType = 
											{
												nHitType = 3,
											},
											ignoreSize = "True",
											name = "Button_drop",
											normal = "ui/fairy/new_ui/new_12.png",
											pressed = "ui/fairy/new_ui/new_12.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 509,
												PositionY = 40,
											},
											UItype = "Button",
											width = "134",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_drop_Button_drop_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "73baaaec_145d_4dd5_a47d_9b36655d45f2",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "27",
													ignoreSize = "True",
													name = "Label_drop",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Lepas",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "61",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_dress_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "00980986_914f_4555_a105_16b3cfb6527c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "58",
											HitType = 
											{
												nHitType = 3,
											},
											ignoreSize = "True",
											name = "Button_dress",
											normal = "ui/fairy/new_ui/new_12.png",
											pressed = "ui/fairy/new_ui/new_12.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 509,
												PositionY = 40,
											},
											UItype = "Button",
											width = "134",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_dress_Button_dress_Panel_di_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "b63be87c_7498_4bea_b764_834c99b8fc1b",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "27",
													ignoreSize = "True",
													name = "Label_dress",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Equip",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "58",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
									UUID = "ca25ae29_947c_4040_8bbf_458293c4d86a",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "False",
									name = "Panel_baoshi_item",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 33,
										PositionY = -300,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "536",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_bg_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "ab2b1dab_602d_4080_a555_95504e5f5766",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "112",
											ignoreSize = "True",
											name = "Image_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/fairy/new_ui/baoshi/JLXL_bg_5_lv.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 268,
												PositionY = 60,
											},
											width = "528",
											ZOrder = "1",
										},
										{
											controlID = "Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "80f90851_3d0b_4fe0_8807_b671a1ebf8d8",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "120",
											ignoreSize = "False",
											name = "Panel_info",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "536",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_name_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "67c09952_e00a_458c_b83e_c6975340e75c",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "18",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "21",
													ignoreSize = "True",
													name = "Label_name",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Nama Gem",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 8,
														PositionY = 99,
													},
													width = "90",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_bg_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "2abd5630_8bd4_4785_873f_41df983bbca8",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "110",
													ignoreSize = "True",
													name = "Image_icon_bg",
													scaleX = "0.7",
													scaleY = "0.7",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/common/frame_green.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 46,
														PositionY = 46,
													},
													width = "110",
													ZOrder = "1",
												},
												{
													controlID = "Image_icon_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "0901f911_1c11_4989_9645_596d2088d516",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "33",
													ignoreSize = "True",
													name = "Image_icon",
													scaleX = "0.9",
													scaleY = "0.9",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/new_angle_icon.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 46,
														PositionY = 46,
													},
													width = "36",
													ZOrder = "1",
												},
												{
													controlID = "Label_desc_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "2dbb6813_8a16_4609_b3b8_91eb7cc068d4",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "70",
													ignoreSize = "False",
													name = "Label_desc",
													nTextAlign = "1",
													nTextHAlign = "0",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Efek Gem Efek Gem",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 87,
														PositionY = 45,
													},
													width = "220",
													ZOrder = "1",
												},
												{
													controlID = "Image_pos1_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "0f5d57e0_e091_43d7_81d4_92b1bc6a4ae8",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "7",
													ignoreSize = "True",
													name = "Image_pos1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/031.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 513,
														PositionY = 106,
													},
													width = "6",
													ZOrder = "1",
												},
												{
													controlID = "Image_pos2_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "0e4b6b0a_0274_4829_b4bd_45d101b4a00f",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "7",
													ignoreSize = "True",
													name = "Image_pos2",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/031.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 513,
														PositionY = 96,
													},
													width = "6",
													ZOrder = "1",
												},
												{
													controlID = "Image_pos3_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "97e7af6e_3fa5_46e3_a837_64b53346cd70",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "7",
													ignoreSize = "True",
													name = "Image_pos3",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/031.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 523,
														PositionY = 96,
													},
													width = "6",
													ZOrder = "1",
												},
												{
													controlID = "Image_pos4_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "e954b3e5_4baa_41d4_882d_d4b65658ebf9",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "7",
													ignoreSize = "True",
													name = "Image_pos4",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/031.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 523,
														PositionY = 106,
													},
													width = "6",
													ZOrder = "1",
												},
												{
													controlID = "Image_skill1_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "cb3d2834_d9f6_40a4_a056_56b311f593a1",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "68",
													ignoreSize = "True",
													name = "Image_skill1",
													scaleX = "0.74",
													scaleY = "0.74",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/kuang_bg.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 354,
														PositionY = 55,
													},
													width = "68",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_skill_icon_Image_skill1_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
															UUID = "b3401154_7452_47e0_985b_835ce1f8bb87",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "33",
															ignoreSize = "True",
															name = "Image_skill_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/fairy/new_ui/new_angle_icon.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "36",
															ZOrder = "1",
														},
														{
															controlID = "Label_skill_name_Image_skill1_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
															UUID = "aa25a441_a91c_4d80_80d0_5cbed8beabbf",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "22",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "25",
															ignoreSize = "True",
															name = "Label_skill_name",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "ATK",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -48,
															},
															width = "39",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Image_skill2_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "5e81b06f_1544_43b3_a824_650b9beadb6e",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "68",
													ignoreSize = "True",
													name = "Image_skill2",
													scaleX = "0.74",
													scaleY = "0.74",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/kuang_bg.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 424,
														PositionY = 55,
													},
													width = "68",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_skill_icon_Image_skill2_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
															UUID = "b475f921_f75b_4c5b_9161_540aa33c517f",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "33",
															ignoreSize = "True",
															name = "Image_skill_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/fairy/new_ui/new_angle_icon.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "36",
															ZOrder = "1",
														},
														{
															controlID = "Label_skill_name_Image_skill2_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
															UUID = "d1583302_e446_4d49_a04b_2ebaca67b01b",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "22",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "25",
															ignoreSize = "True",
															name = "Label_skill_name",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "ATK",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -48,
															},
															width = "39",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Image_skill3_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "1b36df57_da2e_4e01_9fe0_6f553ffab245",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "68",
													ignoreSize = "True",
													name = "Image_skill3",
													scaleX = "0.74",
													scaleY = "0.74",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/kuang_bg.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 494,
														PositionY = 55,
													},
													width = "68",
													ZOrder = "1",
													components = 
													{
														
														{
															controlID = "Image_skill_icon_Image_skill3_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
															UUID = "703753fd_b14d_44eb_82c5_c2a950e47a67",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															backGroundScale9Enable = "False",
															classname = "MEImage",
															dstBlendFunc = "771",
															height = "33",
															ignoreSize = "True",
															name = "Image_skill_icon",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "1",
															texturePath = "ui/fairy/new_ui/new_angle_icon.png",
															touchAble = "False",
															UILayoutViewModel = 
															{
																
															},
															width = "36",
															ZOrder = "1",
														},
														{
															controlID = "Label_skill_name_Image_skill3_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
															UUID = "7d42e933_1d14_4be7_84ba_3a6244ad039d",
															anchorPoint = "False",
															anchorPointX = "0.5",
															anchorPointY = "0.5",
															classname = "MELabel",
															compPath = "luacomponents.common.MEIconLabel",
															dstBlendFunc = "771",
															FontColor = "#FFFFFFFF",
															fontName = "font/fangzheng_zhunyuan.ttf",
															fontShadow = 
															{
																IsShadow = false,
																ShadowColor = "#FFFFFFFF",
																ShadowAlpha = 255,
																OffsetX = 0,
																OffsetY = 0,
															},
															fontSize = "22",
															fontStroke = 
															{
																IsStroke = false,
																StrokeColor = "#FFE6E6E6",
																StrokeSize = 1,
															},
															height = "25",
															ignoreSize = "True",
															name = "Label_skill_name",
															nTextAlign = "1",
															nTextHAlign = "1",
															sizepercentx = "0",
															sizepercenty = "0",
															sizeType = "0",
															srcBlendFunc = "770",
															text = "ATK",
															touchAble = "False",
															touchScaleEnable = "False",
															UILayoutViewModel = 
															{
																PositionY = -48,
															},
															width = "39",
															ZOrder = "1",
														},
													},
												},
												{
													controlID = "Image_quality_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "ec0108d9_fdcf_4a7d_b414_677a74800180",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "159",
													ignoreSize = "True",
													name = "Image_quality",
													scaleX = "0.18",
													scaleY = "0.18",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/common/hero/quality_ss.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 270,
														PositionY = 100,
													},
													width = "262",
													ZOrder = "1",
												},
												{
													controlID = "Image_select_Panel_info_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
													UUID = "2894ebc8_12a8_4cf7_b4b8_b0d209688bdf",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "122",
													ignoreSize = "True",
													name = "Image_select",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/new_ui/baoshi/JLXL_bg_select.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 269,
														PositionY = 60,
													},
													width = "538",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Image_carry_Panel_baoshi_item_Panel_right_Panel_base_Panel-baoshiChooselView_Layer1_fairyNew_Game",
											UUID = "155d1dab_e56a_4936_8cf1_9420ce701b87",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "46",
											ignoreSize = "True",
											name = "Image_carry",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/bag/new_ui/new_10.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 467,
												PositionY = 101,
											},
											width = "86",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"scene/bg/bg_common.png",
			"ui/fairy/new_ui/new_bg_04.png",
			"ui/Equipment/new_ui/12.jpg",
			"ui/fairy/new_ui/baoshi/skill_icon.png",
			"ui/fairy/new_ui/baoshi/020.png",
			"ui/fairy/new_ui/baoshi/019.png",
			"ui/fairy/new_ui/baoshi/008.png",
			"ui/fairy/new_ui/baoshi/009.png",
			"ui/common/hero/quality_aa.png",
			"icon/item/goods/510201.png",
			"ui/fairy/new_ui/rightBG.png",
			"ui/fairy/new_ui/new_34.png",
			"ui/common/1763.png",
			"ui/common/button_big_blue_n.png",
			"ui/fairy/new_ui/baoshi/033.png",
			"ui/fairy/new_ui/new_12.png",
			"ui/fairy/new_ui/baoshi/JLXL_bg_5_lv.png",
			"ui/common/frame_green.png",
			"ui/fairy/new_ui/new_angle_icon.png",
			"ui/fairy/new_ui/baoshi/031.png",
			"ui/fairy/new_ui/baoshi/kuang_bg.png",
			"ui/common/hero/quality_ss.png",
			"ui/fairy/new_ui/baoshi/JLXL_bg_select.png",
			"ui/bag/new_ui/new_10.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

