local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-2020wsj_2_wanshengjie_fuben_Game",
			UUID = "a559b8a9_6ed5_43d6_9464_0d41bada5333",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0.5",
			backGroundScale9Enable = "False",
			bgColorOpacity = "100",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FF808080;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "405",
			ignoreSize = "False",
			name = "Panel",
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				PositionX = 4,
				PositionY = 309,
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "3700",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
					UUID = "3c13c30b_2d2b_44b8_9ab5_da26467fc924",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "439",
					ignoreSize = "False",
					name = "Panel_line",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 51,
						PositionY = -57,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "3700",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_line_001_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "4d35ef1e_97d9_434d_a8ef_75f319590681",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_001",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/01.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 286,
								PositionY = 54,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_002_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "8e3a3e23_d116_449d_a840_ec25ba8c9ba3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_002",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/02.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 633,
								PositionY = 191,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_003_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "f6897d53_11c0_4953_9d4d_0902cd4fe9b2",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_003",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/03.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 659,
								PositionY = -77,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_004_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "83322699_fd81_46bb_9f16_bd3a1e27a6aa",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_004",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/04.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 844,
								PositionY = 28,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_005_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "a82cea12_7919_49f8_ab77_c66597e7ee7a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_005",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/05.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1189,
								PositionY = 81,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_006_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "0908c3b9_3bc4_4ac4_8120_663a4c6ff1fc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_006",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/06.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1513,
								PositionY = 53,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_007_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "1ddf5c8e_e381_4d23_b131_d857e26ec0d7",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_007",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/07.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1832,
								PositionY = 24,
							},
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_line_008_Panel_line_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "28d63191_1f51_423c_a79f_ef13dcf7ef9e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_line_008",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui/activity/activity_2020wsj/chapter/chapter2/04.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 844,
								PositionY = 28,
							},
							width = "64",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
					UUID = "07771a82_eb37_4cab_a296_f375464c77c5",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "439",
					ignoreSize = "False",
					name = "Panel_level",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 46,
						PositionY = -28,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "3700",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_level_001_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "a3bd752a_63fd_4f39_b59d_0f10c4f5167d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_001",
							sizepercentx = "2",
							sizepercenty = "5",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 114,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_002_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "ff1cd3d9_ff28_4732_bd72_d691c9c36632",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_002",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 468,
								PositionY = 190,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_003_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "fc2f05cd_ad25_4bdd_b399_a3fee22b7a34",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_003",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 470,
								PositionY = -135,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_004_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "0141f451_b479_4b91_8e67_628c409db203",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_004",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 696,
								PositionY = -34,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_005_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "262437fd_0a36_4a51_8458_11d09ebc11e2",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_005",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 696,
								PositionY = 85,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_006_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "33d70a7d_a11e_45d5_b340_59ac8eaf1522",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_006",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1039,
								PositionY = 16,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_007_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "2e3ad175_d390_489c_8724_9ae7c32c0a1e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_007",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1359,
								PositionY = 80,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_008_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "2477a4b1_d921_4904_8542_fd1ed99d30a1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_008",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 1658,
								PositionY = -41,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "Panel_level_009_Panel_level_Panel-2020wsj_2_wanshengjie_fuben_Game",
							UUID = "75280a9d_a0ff_4b00_9174_d633f50f57e0",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "150",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "Panel_level_009",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 2042,
								PositionY = 15,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "40",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/activity_2020wsj/chapter/chapter2/01.png",
			"ui/activity/activity_2020wsj/chapter/chapter2/02.png",
			"ui/activity/activity_2020wsj/chapter/chapter2/03.png",
			"ui/activity/activity_2020wsj/chapter/chapter2/04.png",
			"ui/activity/activity_2020wsj/chapter/chapter2/05.png",
			"ui/activity/activity_2020wsj/chapter/chapter2/06.png",
			"ui/activity/activity_2020wsj/chapter/chapter2/07.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

