local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-RankNoticeView_Layer1_MainScene_Game",
			UUID = "92f14afe_de66_42f4_8488_291b2390f8ea",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Image_bg_Panel-RankNoticeView_Layer1_MainScene_Game",
					UUID = "8de0eaa7_14cf_4327_9436_4a376655adfb",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "Image_bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui/common/bg_01.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 510,
						PositionY = 354,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "1386",
					ZOrder = "1",
				},
				{
					controlID = "Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
					UUID = "0ce80c4e_2820_4c07_9620_7d638b3298b5",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -58,
						PositionY = 34,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Relative",
						nType = "3"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_right_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
							UUID = "b724b227_168c_4b03_b9f6_448e735f3321",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "600",
							ignoreSize = "False",
							name = "Panel_right",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel_root",
								nType = 3,
								nGravity = 4,
								nAlign = 7
							},
							uipanelviewmodel = 
							{
								Layout="Relative",
								nType = "3"
							},
							width = "116",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_tab_bg_Panel_right_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "be099621_79bc_4676_9882_4835a3564923",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "570",
									ignoreSize = "True",
									name = "Image_tab_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/left_bar_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -19,
										LeftPositon = -19,
										relativeToName = "Panel_right",
										nType = 3,
										nGravity = 4,
										nAlign = 7
									},
									width = "114",
									ZOrder = "1",
								},
								{
									controlID = "ScrollView_RankNoticeView_1_Panel_right_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "58a32389_78fe_4906_a648_aed46779c904",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "True",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "565",
									ignoreSize = "False",
									innerHeight = "576",
									innerWidth = "116",
									name = "ScrollView_RankNoticeView_1",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = 5,
										TopPosition = 30,
										relativeToName = "Panel_right",
										nType = 3,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "116",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
							UUID = "936a4a65_8d71_44f2_83af_1c7ac72b29fe",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "533",
							ignoreSize = "False",
							name = "Panel_top",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 118,
								PositionY = 35,
								LeftPositon = 118,
								BottomPosition = 35,
								relativeToName = "Panel_root",
								nType = 3,
								nGravity = 4,
								nAlign = 7
							},
							uipanelviewmodel = 
							{
								Layout="Relative",
								nType = "3"
							},
							width = "600",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "ea1a6521_2266_45de_8c54_cacff4ea49f4",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "506",
									ignoreSize = "False",
									name = "Panel_rank_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										relativeToName = "Panel_top",
										nType = 3,
										nGravity = 4,
										nAlign = 7
									},
									uipanelviewmodel = 
									{
										Layout="Relative",
										nType = "3"
									},
									width = "193",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_rank_1_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "a748cede_b1bc_423b_8aa9_b89bf97ae04f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "506",
											ignoreSize = "True",
											name = "Image_rank_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/img_1.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 253,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 5
											},
											width = "189",
											ZOrder = "1",
										},
										{
											controlID = "img_diban_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "bd038dd5_29e4_4dde_b40c_08d278152a2e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "436",
											ignoreSize = "True",
											name = "img_diban",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/img_7.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 281,
												TopPosition = 7,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 2
											},
											width = "181",
											ZOrder = "1",
										},
										{
											controlID = "Panel_paint_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "4a72b132_8a1b_423d_9b93_35ccf3c7734a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "436",
											ignoreSize = "False",
											name = "Panel_paint",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 278,
												BottomPosition = 60,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "182",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_none_Panel_paint_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "222cca62_25ae_4149_8f2c_5823873181d6",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "427",
													ignoreSize = "True",
													name = "Image_none",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/mainLayer/rank_notice/img_5.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = -27,
														relativeToName = "Panel_paint",
														nGravity = 6,
														nAlign = 8
													},
													width = "182",
													ZOrder = "1",
												},
												{
													controlID = "Image_paint_Panel_paint_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "9a7663ad_8888_4120_a79f_d9e9615aa2f5",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "64",
													ignoreSize = "True",
													name = "Image_paint",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														relativeToName = "Panel_rank_1",
														nGravity = 6,
														nAlign = 5
													},
													visible = "False",
													width = "64",
													ZOrder = "1",
												},
												{
													controlID = "panel_paint_Panel_paint_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "741f130c_52d3_41dd_9c50_1afada4250f4",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "0",
													ignoreSize = "False",
													name = "panel_paint",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "0",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_detail_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "60ca2fe7_241c_43a6_bb18_e3ee14a75d35",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_detail",
											normal = "ui/mainLayer/rank_notice/img_2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 160,
												PositionY = 88,
												LeftPositon = 134,
												BottomPosition = 66,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 4,
												nAlign = 7
											},
											UItype = "Button",
											width = "51",
											ZOrder = "1",
										},
										{
											controlID = "Image_bottom_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "fe4d35ed_583f_42d4_be54_66d9931bce59",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "62",
											ignoreSize = "True",
											name = "Image_bottom",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/1-2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 31,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "182",
											ZOrder = "1",
										},
										{
											controlID = "Label_rank_value_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "0254c987_8932_48d2_ace8_c32dc5be855b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF4566AA",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_rank_value",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "等級：70",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 44,
												BottomPosition = 33,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "84",
											ZOrder = "1",
										},
										{
											controlID = "Label_player_name_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "c7b8a671_717f_4acc_a188_e0bf24ca42de",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF4566AA",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "19",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "24",
											ignoreSize = "True",
											name = "Label_player_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "一二三四五六",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 15,
												BottomPosition = 3,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "117",
											ZOrder = "1",
										},
										{
											controlID = "Image_top_Panel_rank_1_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "eec0a721_18a0_4058_88ad_79b25c7ba8cf",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "76",
											ignoreSize = "True",
											name = "Image_top",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/1-1.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 509,
												TopPosition = -41,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 2
											},
											width = "198",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "34e631ee_d022_4009_87d8_a67995db03d5",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "506",
									ignoreSize = "False",
									name = "Panel_rank_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 196,
										LeftPositon = 196,
										relativeToName = "Panel_top",
										nType = 3,
										nGravity = 4,
										nAlign = 7
									},
									uipanelviewmodel = 
									{
										Layout="Relative",
										nType = "3"
									},
									width = "193",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_rank_1_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "69c418d1_c795_49a5_bb2f_f9c46fc42ed0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "506",
											ignoreSize = "True",
											name = "Image_rank_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/img_1.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 253,
												relativeToName = "Panel_rank_2",
												nType = 3,
												nGravity = 6,
												nAlign = 5
											},
											width = "189",
											ZOrder = "1",
										},
										{
											controlID = "img_diban_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "2db233be_e329_40f6_a5ed_1776dbe2b1c9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "436",
											ignoreSize = "True",
											name = "img_diban",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/img_7.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 281,
												TopPosition = 7,
												relativeToName = "Panel_rank_2",
												nType = 3,
												nGravity = 6,
												nAlign = 2
											},
											width = "181",
											ZOrder = "1",
										},
										{
											controlID = "Panel_paint_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "7d82bb3f_8ecb_4618_89e3_7d5425fd0a0b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "436",
											ignoreSize = "False",
											name = "Panel_paint",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 278,
												BottomPosition = 60,
												relativeToName = "Panel_rank_2",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "182",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_none_Panel_paint_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "b46c1bcc_83f3_4083_91a5_2b407fc2a111",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "427",
													ignoreSize = "True",
													name = "Image_none",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/mainLayer/rank_notice/img_5.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = -27,
														relativeToName = "Panel_paint",
														nGravity = 6,
														nAlign = 8
													},
													width = "182",
													ZOrder = "1",
												},
												{
													controlID = "Image_paint_Panel_paint_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "107b3244_b6ab_42e8_a14a_153be3045229",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "64",
													ignoreSize = "True",
													name = "Image_paint",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														relativeToName = "Panel_rank_1",
														nGravity = 6,
														nAlign = 5
													},
													visible = "False",
													width = "64",
													ZOrder = "1",
												},
												{
													controlID = "panel_paint_Panel_paint_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "a56ad822_fc56_4cf9_b0ed_25cb5f999c2f",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "0",
													ignoreSize = "False",
													name = "panel_paint",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														LeftPositon = 91,
														TopPosition = 415,
														relativeToName = "Panel_paint",
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "0",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_detail_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "dbb85cb6_a836_4b0f_9e43_974f57a5f1fe",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_detail",
											normal = "ui/mainLayer/rank_notice/img_2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 160,
												PositionY = 88,
												LeftPositon = 134,
												BottomPosition = 66,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 4,
												nAlign = 7
											},
											UItype = "Button",
											width = "51",
											ZOrder = "1",
										},
										{
											controlID = "Image_bottom_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "d52a1c4d_898d_4403_ac46_54b4a8620c9c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "62",
											ignoreSize = "True",
											name = "Image_bottom",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/2-2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 31,
												relativeToName = "Panel_rank_2",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "182",
											ZOrder = "1",
										},
										{
											controlID = "Label_rank_value_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "be17fa4b_3eea_4a72_8f59_49016bb18164",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF4566AA",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_rank_value",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "等級：70",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 44,
												BottomPosition = 33,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "84",
											ZOrder = "1",
										},
										{
											controlID = "Label_player_name_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "06b614a1_a797_4998_b1fc_e930f0c9c617",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF4566AA",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "19",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "24",
											ignoreSize = "True",
											name = "Label_player_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "一二三四五六",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 15,
												BottomPosition = 3,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "117",
											ZOrder = "1",
										},
										{
											controlID = "Image_top_Panel_rank_2_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "542784e4_e351_499e_82cd_4e98b7386930",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "76",
											ignoreSize = "True",
											name = "Image_top",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/2-1.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 504,
												TopPosition = -36,
												relativeToName = "Panel_rank_2",
												nType = 3,
												nGravity = 6,
												nAlign = 2
											},
											width = "198",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "0e2240e7_c5f0_4f6d_aff8_f8ccaecb8887",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "506",
									ignoreSize = "False",
									name = "Panel_rank_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 392,
										LeftPositon = 392,
										relativeToName = "Panel_top",
										nType = 3,
										nGravity = 4,
										nAlign = 7
									},
									uipanelviewmodel = 
									{
										Layout="Relative",
										nType = "3"
									},
									width = "193",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_rank_1_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "4d0e5993_b4dd_4e33_92ff_dfddcd43714e",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "506",
											ignoreSize = "True",
											name = "Image_rank_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/img_1.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 253,
												relativeToName = "Panel_rank_3",
												nType = 3,
												nGravity = 6,
												nAlign = 5
											},
											width = "189",
											ZOrder = "1",
										},
										{
											controlID = "img_diban_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "d8decadf_641c_468f_bc27_3b35507f4c28",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "436",
											ignoreSize = "True",
											name = "img_diban",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/img_7.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 281,
												TopPosition = 7,
												relativeToName = "Panel_rank_2",
												nType = 3,
												nGravity = 6,
												nAlign = 2
											},
											width = "181",
											ZOrder = "1",
										},
										{
											controlID = "Panel_paint_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "488eda31_d452_43e6_b775_3d1dce2d278c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "436",
											ignoreSize = "False",
											name = "Panel_paint",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 278,
												BottomPosition = 60,
												relativeToName = "Panel_rank_3",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "182",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Image_none_Panel_paint_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "bfcbe452_9898_4445_ad8b_3b73c9ccb5a1",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "427",
													ignoreSize = "True",
													name = "Image_none",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/mainLayer/rank_notice/img_5.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionY = -26,
														relativeToName = "Panel_paint",
														nGravity = 6,
														nAlign = 8
													},
													width = "182",
													ZOrder = "1",
												},
												{
													controlID = "Image_paint_Panel_paint_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "eae13194_8c48_4961_9583_f87b725a2847",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "64",
													ignoreSize = "True",
													name = "Image_paint",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														relativeToName = "Panel_rank_1",
														nGravity = 6,
														nAlign = 5
													},
													visible = "False",
													width = "64",
													ZOrder = "1",
												},
												{
													controlID = "panel_paint_Panel_paint_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
													UUID = "7ba23d30_1585_4af6_b39b_93ce4f7bca08",
													anchorPoint = "False",
													anchorPointX = "0",
													anchorPointY = "0",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "0",
													ignoreSize = "False",
													name = "panel_paint",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														LeftPositon = 91,
														TopPosition = 415,
														relativeToName = "Panel_paint",
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "0",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_detail_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "ce51c3e5_3b56_4eb9_bb60_8f0c72ea66f0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_detail",
											normal = "ui/mainLayer/rank_notice/img_2.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 160,
												PositionY = 88,
												LeftPositon = 134,
												BottomPosition = 66,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 4,
												nAlign = 7
											},
											UItype = "Button",
											width = "51",
											ZOrder = "1",
										},
										{
											controlID = "Image_bottom_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "4da1d6c0_83dd_4e73_89b6_5d8cfd4a3ca8",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "62",
											ignoreSize = "True",
											name = "Image_bottom",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/3-2.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 31,
												relativeToName = "Panel_rank_3",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "182",
											ZOrder = "1",
										},
										{
											controlID = "Label_rank_value_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "a8170e33_f855_458d_83af_7a0ecb668202",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF4566AA",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "23",
											ignoreSize = "True",
											name = "Label_rank_value",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "等級：70",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 44,
												BottomPosition = 33,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "84",
											ZOrder = "1",
										},
										{
											controlID = "Label_player_name_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "cb5648be_18e9_4257_ad98_de82da1d37fe",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FF4566AA",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "19",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "24",
											ignoreSize = "True",
											name = "Label_player_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "一二三四五六",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 15,
												BottomPosition = 3,
												relativeToName = "Panel_rank_1",
												nType = 3,
												nGravity = 6,
												nAlign = 8
											},
											width = "117",
											ZOrder = "1",
										},
										{
											controlID = "Image_top_Panel_rank_3_Panel_top_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "52d9bc15_4b4e_4bba_a8cd_242f19d9e887",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "76",
											ignoreSize = "True",
											name = "Image_top",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/3-1.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 96,
												PositionY = 509,
												TopPosition = -41,
												relativeToName = "Panel_rank_3",
												nType = 3,
												nGravity = 6,
												nAlign = 2
											},
											width = "198",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
							UUID = "b94191d1_b675_459f_ba3c_fddb8fb71092",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "1;SingleColor:#FF191970;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "510",
							ignoreSize = "False",
							name = "Panel_bottom",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 706,
								PositionY = 35,
								LeftPositon = 706,
								BottomPosition = 35,
								relativeToName = "Panel_root",
								nType = 3,
								nGravity = 4,
								nAlign = 7
							},
							uipanelviewmodel = 
							{
								Layout="Relative",
								nType = "3"
							},
							width = "432",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_rankBar_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "aeeea45f_7311_4322_a5c9_17c51a6a036b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "454",
									ignoreSize = "False",
									name = "Image_rankBar",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/scroll_bar_01.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 429,
										PositionY = 228,
										TopPosition = 55,
										relativeToName = "Panel_bottom",
										nType = 3,
										nGravity = 3,
										nAlign = 3
									},
									visible = "False",
									width = "6",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_rankScrollBar_Image_rankBar_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "63989f89_ab5c_4304_8e03_6200b8d640ac",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "454",
											ignoreSize = "False",
											name = "Image_rankScrollBar",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/common/scroll_bar_02.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "6",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_rank_scroll_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "2045e22f_9eb4_41f7_bafa_1059b4b67e97",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "454",
									ignoreSize = "False",
									name = "Panel_rank_scroll",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 7,
										relativeToName = "Panel_bottom",
										nType = 3,
										nGravity = 6,
										nAlign = 8
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "418",
									ZOrder = "1",
								},
								{
									controlID = "Scroll_rank_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "cc5d4570_a5f0_454b_82ac_3965665b830a",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "True",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "454",
									ignoreSize = "False",
									innerHeight = "454",
									innerWidth = "416",
									name = "Scroll_rank",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 5,
										LeftPositon = 5,
										relativeToName = "Panel_bottom",
										nType = 3,
										nGravity = 4,
										nAlign = 7
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									visible = "False",
									width = "416",
									ZOrder = "1",
								},
								{
									controlID = "Panel_my_rank_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "ae29da9c_0a12_42e5_8827_40abe66001d0",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FF008000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "42",
									ignoreSize = "False",
									name = "Panel_my_rank",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 8,
										PositionY = 462,
										TopPosition = 6,
										relativeToName = "Panel_bottom",
										nType = 3,
										nGravity = 6,
										nAlign = 2
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "416",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "image_di_Panel_my_rank_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "d60afe97_aeca_4723_bb57_b1ca283ee4ea",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "42",
											ignoreSize = "True",
											name = "image_di",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/mainLayer/rank_notice/img_4.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 208,
												PositionY = 21,
												relativeToName = "Panel_my_rank",
												nGravity = 6,
												nAlign = 5
											},
											width = "433",
											ZOrder = "1",
										},
										{
											controlID = "label_my_rank_Panel_my_rank_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "15618069_b681_45f4_a497_bbd202f00cbe",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "label_my_rank",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "我的排名：",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 225,
												PositionY = 21,
												LeftPositon = 109,
												TopPosition = 6,
												relativeToName = "Panel_my_rank",
												nGravity = 1,
											},
											width = "116",
											ZOrder = "1",
										},
										{
											controlID = "label_rank_Panel_my_rank_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "ce38de0f_ab57_4801_b358_4b0f579cb2c6",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "phanta.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "29",
											ignoreSize = "True",
											name = "label_rank",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "180",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 233,
												PositionY = 21,
												LeftPositon = 233,
												TopPosition = 6,
												relativeToName = "Panel_my_rank",
												nGravity = 1,
											},
											width = "40",
											ZOrder = "1",
										},
										{
											controlID = "label_no_rank_Panel_my_rank_Panel_bottom_Panel_root_Panel-RankNoticeView_Layer1_MainScene_Game",
											UUID = "f82f3fc0_9b3b_4997_a649_acacec5c18a6",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "label_no_rank",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "暫未上榜",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 233,
												PositionY = 21,
												LeftPositon = 233,
												TopPosition = 6,
												relativeToName = "Panel_my_rank",
												nGravity = 1,
											},
											width = "107",
											ZOrder = "1",
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
					UUID = "bb831d66_bea7_47aa_adf2_02711356c005",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 27,
						PositionY = -742,
						LeftPositon = 27,
						TopPosition = 811,
						relativeToName = "Panel_root",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
							UUID = "5349eb49_d7da_4963_942a_1152bc0434db",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "92",
							ignoreSize = "False",
							name = "Panel_rankItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 608,
								PositionY = 173,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "416",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_diban_Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "1feb3686_4fe1_4b61_a61c_048566a71bec",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "89",
									ignoreSize = "True",
									name = "Image_diban",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/mainLayer/rank_notice/img_3.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "416",
									ZOrder = "1",
								},
								{
									controlID = "Label_player_name_Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "1a52b413_b963_4b77_9dd5_78ddf9b94753",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3E4474",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_player_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "一二三四五六",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -40,
										PositionY = 17,
									},
									width = "134",
									ZOrder = "1",
								},
								{
									controlID = "Button_detail_Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "0fded16c_875a_4130_af65_b41886ffab23",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "44",
									ignoreSize = "True",
									name = "Button_detail",
									normal = "ui/mainLayer/rank_notice/img_2.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 182,
										PositionY = -16,
									},
									UItype = "Button",
									width = "51",
									ZOrder = "1",
								},
								{
									controlID = "Label_desc_Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "8c5c814c_ef99_4530_92f9_ae9bcb14b5bb",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF3C3F6D",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_desc",
									nTextAlign = "0",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "等級：163",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -40,
										PositionY = -26,
									},
									width = "91",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "4dc2ef86_382b_4aba_a8a9_94bcace24cb8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "98",
									ignoreSize = "True",
									name = "Image_icon",
									scaleX = "0.7",
									scaleY = "0.7",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/hero/name/1101011.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -87,
										PositionY = -2,
									},
									width = "98",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_frame_Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "eff835ad_f66e_4246_8ea4_d3207526f735",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "104",
									ignoreSize = "True",
									name = "Image_icon_frame",
									scaleX = "0.7",
									scaleY = "0.7",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/playerInfo/avatar/TXBK_moren_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -87,
										PositionY = -2,
									},
									width = "104",
									ZOrder = "1",
								},
								{
									controlID = "Label_rank_select_Panel_rankItem_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "3911c1ce_4d42_4bfb_9c7f_3b63a0d343bf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF4566AA",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "25",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "31",
									ignoreSize = "True",
									name = "Label_rank_select",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "543",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -170,
										PositionY = -2,
									},
									width = "66",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_tabItme_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
							UUID = "95d3b73c_9d76_4c8c_9116_bdb1a434e3b1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "100",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "96",
							ignoreSize = "False",
							name = "Panel_tabItme",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 57,
								PositionY = 526,
								BottomPosition = 474,
								relativeToName = "Panel_right",
								nGravity = 4,
								nAlign = 7
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "116",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_select_Panel_tabItme_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "1f1219bd_f60d_4769_a146_cd605fc6051d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "96",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/left_side/side_select.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "116",
									ZOrder = "1",
								},
								{
									controlID = "Image_icon_Panel_tabItme_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "0c5b2191_50ee_44fc_bd05_3d088c563ada",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "68",
									ignoreSize = "True",
									name = "Image_icon",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/mainLayer/rank_notice/img_level.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -8,
										PositionY = 15,
									},
									width = "68",
									ZOrder = "1",
								},
								{
									controlID = "Label_name_Panel_tabItme_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "46a2a86d_fb85_4d1b_a077_6819f6489fa7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "23",
									ignoreSize = "True",
									name = "Label_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "等級排行",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -8,
										PositionY = -25,
									},
									width = "83",
									ZOrder = "1",
								},
								{
									controlID = "Image_touch_Panel_tabItme_Panel_prefab_Panel-RankNoticeView_Layer1_MainScene_Game",
									UUID = "7f6ed24d_3a33_4187_aaf8_fb4105b2b299",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "90",
									ignoreSize = "False",
									name = "Image_touch",
									opacity = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/xj023.png",
									touchAble = "True",
									UILayoutViewModel = 
									{
										
									},
									width = "116",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/common/bg_01.png",
			"ui/common/left_bar_bg.png",
			"ui/mainLayer/rank_notice/img_1.png",
			"ui/mainLayer/rank_notice/img_7.png",
			"ui/mainLayer/rank_notice/img_5.png",
			"ui/mainLayer/rank_notice/img_2.png",
			"ui/mainLayer/rank_notice/1-2.png",
			"ui/mainLayer/rank_notice/1-1.png",
			"ui/mainLayer/rank_notice/2-2.png",
			"ui/mainLayer/rank_notice/2-1.png",
			"ui/mainLayer/rank_notice/3-2.png",
			"ui/mainLayer/rank_notice/3-1.png",
			"ui/common/scroll_bar_01.png",
			"ui/common/scroll_bar_02.png",
			"ui/mainLayer/rank_notice/img_4.png",
			"ui/mainLayer/rank_notice/img_3.png",
			"icon/hero/name/1101011.png",
			"ui/playerInfo/avatar/TXBK_moren_1.png",
			"ui/common/left_side/side_select.png",
			"ui/mainLayer/rank_notice/img_level.png",
			"ui/xj023.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

