return {
    [1] = {
        offset = {
            y = -90,
            x = 0,
        },
        tileGid = 205,
        order = 1,
        mapActorName = "3003001",
        mapActorIcon = "ui/kabalatree/event/floor_enemy_1.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_enemy_1.png",
        scale = 0.8,
        eventType = {
            [1] = 2001,
        },
        id = 1,
    },
    [2] = {
        offset = {
            y = -90,
            x = 0,
        },
        tileGid = 205,
        order = 2,
        mapActorName = "3003002",
        mapActorIcon = "ui/kabalatree/event/floor_enemy_2.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_enemy_2.png",
        scale = 0.8,
        eventType = {
            [1] = 2001,
        },
        id = 2,
    },
    [3] = {
        offset = {
            y = -70,
            x = 0,
        },
        tileGid = 205,
        order = 5,
        mapActorName = "3003003",
        mapActorIcon = "ui/kabalatree/event/floor_fight.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_fight.png",
        scale = 0.8,
        eventType = {
            [1] = 1003,
            [2] = 1013,
            [3] = 1022,
        },
        id = 3,
    },
    [4] = {
        offset = {
            y = -85,
            x = 0,
        },
        tileGid = 205,
        order = 6,
        mapActorName = "3003004",
        mapActorIcon = "ui/kabalatree/event/floor_boss.png",
        scaleMap = 1.8,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_boss.png",
        scale = 0.8,
        eventType = {
            [1] = 1001,
        },
        id = 4,
    },
    [5] = {
        offset = {
            y = -30,
            x = 0,
        },
        tileGid = 202,
        order = 30,
        mapActorName = "3003005",
        mapActorIcon = "",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "",
        scale = 0.8,
        eventType = {
        },
        id = 5,
    },
    [6] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 204,
        order = 13,
        mapActorName = "3003006",
        mapActorIcon = "ui/kabalatree/event/floor_random.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_random_1.png",
        scale = 0.8,
        eventType = {
            [1] = 2002,
            [2] = 2012,
        },
        id = 6,
    },
    [7] = {
        offset = {
            y = -80,
            x = 0,
        },
        tileGid = 205,
        order = 9,
        mapActorName = "3003007",
        mapActorIcon = "ui/kabalatree/event/floor_spot_1.png",
        scaleMap = 1.8,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_spot_1.png",
        scale = 0.8,
        eventType = {
            [1] = 1005,
        },
        id = 7,
    },
    [8] = {
        offset = {
            y = 1,
            x = 1,
        },
        tileGid = 202,
        order = 16,
        mapActorName = "3003008",
        mapActorIcon = "ui/kabalatree/event/floor_spot_2.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_spot_1.png",
        scale = 0.8,
        eventType = {
        },
        id = 8,
    },
    [9] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 203,
        order = 9,
        mapActorName = "3003009",
        mapActorIcon = "ui/kabalatree/event/floor_taskitem_1.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 0.8,
        eventType = {
            [1] = 1002,
            [2] = 1012,
        },
        id = 9,
    },
    [10] = {
        offset = {
            y = -60,
            x = 0,
        },
        tileGid = 203,
        order = 8,
        mapActorName = "3003010",
        mapActorIcon = "ui/kabalatree/event/floor_plot_1.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_plot.png",
        scale = 0.8,
        eventType = {
            [1] = 1006,
            [2] = 1016,
        },
        id = 10,
    },
    [11] = {
        offset = {
            y = -25,
            x = 0,
        },
        tileGid = 203,
        order = 10,
        mapActorName = "3003011",
        mapActorIcon = "ui/kabalatree/event/floor_store.png",
        scaleMap = 1.25,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_store.png",
        scale = 0.6,
        eventType = {
            [1] = 2004,
        },
        id = 11,
    },
    [12] = {
        offset = {
            y = -135,
            x = 0,
        },
        tileGid = 203,
        order = 11,
        mapActorName = "3003012",
        mapActorIcon = "ui/kabalatree/event/floor_transport.png",
        scaleMap = 2.05,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_transport.png",
        scale = 0.9,
        eventType = {
            [1] = 2003,
            [2] = 2013,
        },
        id = 12,
    },
    [13] = {
        offset = {
            y = 1,
            x = 1,
        },
        tileGid = 0,
        order = 17,
        mapActorName = "3003013",
        mapActorIcon = "ui/kabalatree/event/floor_spot.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_spot.png",
        scale = 0.8,
        eventType = {
        },
        id = 13,
    },
    [14] = {
        offset = {
            y = -90,
            x = 0,
        },
        tileGid = 205,
        order = 3,
        mapActorName = "3003014",
        mapActorIcon = "ui/kabalatree/event/floor_enemy_3.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_enemy_3.png",
        scale = 0.8,
        eventType = {
            [1] = 2001,
        },
        id = 14,
    },
    [15] = {
        offset = {
            y = -80,
            x = 0,
        },
        tileGid = 203,
        order = 18,
        mapActorName = "3003007",
        mapActorIcon = "ui/kabalatree/event/floor_spot_2.png",
        scaleMap = 1.8,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_spot_2.png",
        scale = 0.8,
        eventType = {
        },
        id = 15,
    },
    [16] = {
        offset = {
            y = -60,
            x = 0,
        },
        tileGid = 203,
        order = 8,
        mapActorName = "3003010",
        mapActorIcon = "ui/kabalatree/event/floor_plot_2.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_plot.png",
        scale = 0.8,
        eventType = {
            [1] = 1006,
            [2] = 1016,
        },
        id = 16,
    },
    [17] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 203,
        order = 9,
        mapActorName = "3003009",
        mapActorIcon = "ui/kabalatree/event/floor_taskitem_2.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 0.8,
        eventType = {
            [1] = 1002,
            [2] = 1012,
        },
        id = 17,
    },
    [18] = {
        offset = {
            y = -60,
            x = 0,
        },
        tileGid = 203,
        order = 8,
        mapActorName = "3003010",
        mapActorIcon = "ui/kabalatree/event/floor_plot_3.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_plot.png",
        scale = 0.8,
        eventType = {
            [1] = 1006,
            [2] = 1016,
        },
        id = 18,
    },
    [19] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 203,
        order = 9,
        mapActorName = "3003009",
        mapActorIcon = "ui/kabalatree/event/floor_taskitem_3_1.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 0.8,
        eventType = {
            [1] = 1002,
            [2] = 1012,
            [3] = 1022,
        },
        id = 19,
    },
    [20] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 203,
        order = 9,
        mapActorName = "3003009",
        mapActorIcon = "ui/kabalatree/event/floor_taskitem_3_2_2.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 0.8,
        eventType = {
            [1] = 1002,
            [2] = 1012,
            [3] = 1022,
        },
        id = 20,
    },
    [21] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 204,
        order = 15,
        mapActorName = "3003016",
        mapActorIcon = "ui/kabalatree/event/floor_random_2.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_random_2.png",
        scale = 0.8,
        eventType = {
            [1] = 2002,
            [2] = 2012,
        },
        id = 21,
    },
    [22] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 204,
        order = 14,
        mapActorName = "3003017",
        mapActorIcon = "ui/kabalatree/event/floor_random_3.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_random_3.png",
        scale = 0.8,
        eventType = {
            [1] = 2002,
            [2] = 2012,
        },
        id = 22,
    },
    [23] = {
        offset = {
        },
        tileGid = 202,
        order = 19,
        mapActorName = "3003015",
        mapActorIcon = "ui/kabalatree/event/floor_target_tile.png",
        scaleMap = 0,
        isShow = true,
        miniMapIcon = "",
        scale = 0.25,
        eventType = {
            [1] = 1004,
        },
        id = 23,
    },
    [24] = {
        offset = {
            y = -85,
            x = 0,
        },
        tileGid = 205,
        order = 7,
        mapActorName = "3003019",
        mapActorIcon = "ui/kabalatree/event/floor_boss_2.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_boss_2.png",
        scale = 0.8,
        eventType = {
            [1] = 1101,
        },
        id = 24,
    },
    [25] = {
        offset = {
            y = -80,
            x = 0,
        },
        tileGid = 203,
        order = 20,
        mapActorName = "3003020",
        mapActorIcon = "ui/kabalatree/event/floor_cube.png",
        scaleMap = 1.8,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_cube.png",
        scale = 0.8,
        eventType = {
            [1] = 3001,
        },
        id = 25,
    },
    [26] = {
        offset = {
            y = -100,
            x = 0,
        },
        tileGid = 203,
        order = 21,
        mapActorName = "3003021",
        mapActorIcon = "ui/kabalatree/event/floor_chip.png",
        scaleMap = 1.85,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_chip.png",
        scale = 0.85,
        eventType = {
            [1] = 3002,
        },
        id = 26,
    },
    [27] = {
        offset = {
            y = -90,
            x = 0,
        },
        tileGid = 203,
        order = 22,
        mapActorName = "3003022",
        mapActorIcon = "ui/kabalatree/event/floor_relic.png",
        scaleMap = 1.8,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_relic.png",
        scale = 0.8,
        eventType = {
            [1] = 3003,
        },
        id = 27,
    },
    [28] = {
        offset = {
            y = -90,
            x = 0,
        },
        tileGid = 203,
        order = 23,
        mapActorName = "3003023",
        mapActorIcon = "ui/kabalatree/event/floor_dice.png",
        scaleMap = 1.8,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_dice.png",
        scale = 0.8,
        eventType = {
            [1] = 3004,
        },
        id = 28,
    },
    [29] = {
        offset = {
            y = -50,
            x = 0,
        },
        tileGid = 203,
        order = 24,
        mapActorName = "3003024",
        mapActorIcon = "ui/kabalatree/event/floor_divination.png",
        scaleMap = 1.65,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_divination.png",
        scale = 0.8,
        eventType = {
            [1] = 3005,
        },
        id = 29,
    },
    [30] = {
        offset = {
            y = -90,
            x = 0,
        },
        tileGid = 205,
        order = 4,
        mapActorName = "3003025",
        mapActorIcon = "ui/kabalatree/event/floor_enemy_4.png",
        scaleMap = 1.7,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_enemy_4.png",
        scale = 0.8,
        eventType = {
            [1] = 2001,
        },
        id = 30,
    },
    [31] = {
        offset = {
            y = -135,
            x = 0,
        },
        tileGid = 203,
        order = 12,
        mapActorName = "3003026",
        mapActorIcon = "ui/kabalatree/event/floor_transport_2.png",
        scaleMap = 2,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_transport_2.png",
        scale = 0.9,
        eventType = {
            [1] = 2003,
            [2] = 2013,
        },
        id = 31,
    },
    [32] = {
        offset = {
            y = -75,
            x = 0,
        },
        tileGid = 204,
        order = 28,
        mapActorName = "3003029",
        mapActorIcon = "ui/kabalatree/event/floor_treasure_1.png",
        scaleMap = 1.6,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_treasure_1.png",
        scale = 0.75,
        eventType = {
            [1] = 2002,
            [2] = 2012,
        },
        id = 32,
    },
    [33] = {
        offset = {
            y = -75,
            x = 0,
        },
        tileGid = 204,
        order = 27,
        mapActorName = "3003028",
        mapActorIcon = "ui/kabalatree/event/floor_treasure_2.png",
        scaleMap = 1.6,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_treasure_2.png",
        scale = 0.75,
        eventType = {
            [1] = 2002,
            [2] = 2012,
        },
        id = 33,
    },
    [34] = {
        offset = {
            y = -75,
            x = 0,
        },
        tileGid = 204,
        order = 26,
        mapActorName = "3003027",
        mapActorIcon = "ui/kabalatree/event/floor_treasure_3.png",
        scaleMap = 1.6,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_treasure_3.png",
        scale = 0.75,
        eventType = {
            [1] = 2002,
            [2] = 2012,
        },
        id = 34,
    },
    [35] = {
        offset = {
            y = -75,
            x = 0,
        },
        tileGid = 203,
        order = 25,
        mapActorName = "3006405",
        mapActorIcon = "ui/kabalatree/event/floor_guide.png",
        scaleMap = 1.75,
        isShow = true,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 1,
        eventType = {
            [1] = 1002,
            [2] = 1012,
            [3] = 1022,
        },
        id = 35,
    },
    [36] = {
        offset = {
            y = -60,
            x = 0,
        },
        tileGid = 203,
        order = 8,
        mapActorName = "3003010",
        mapActorIcon = "ui/kabalatree/event/floor_plot_4.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_plot.png",
        scale = 0.8,
        eventType = {
            [1] = 1006,
            [2] = 1016,
        },
        id = 36,
    },
    [37] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 203,
        order = 9,
        mapActorName = "3003009",
        mapActorIcon = "ui/kabalatree/event/floor_taskitem_4.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 0.8,
        eventType = {
            [1] = 1002,
            [2] = 1012,
            [3] = 1022,
        },
        id = 37,
    },
    [38] = {
        offset = {
            y = -60,
            x = 0,
        },
        tileGid = 203,
        order = 8,
        mapActorName = "3003010",
        mapActorIcon = "ui/kabalatree/event/floor_plot_5.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_plot.png",
        scale = 0.8,
        eventType = {
            [1] = 1006,
            [2] = 1016,
        },
        id = 38,
    },
    [39] = {
        offset = {
            y = -60,
            x = 0,
        },
        tileGid = 203,
        order = 8,
        mapActorName = "3003010",
        mapActorIcon = "ui/kabalatree/event/floor_plot_6.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_plot.png",
        scale = 0.8,
        eventType = {
            [1] = 1006,
            [2] = 1016,
        },
        id = 39,
    },
    [40] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 203,
        order = 9,
        mapActorName = "3003009",
        mapActorIcon = "ui/kabalatree/event/floor_taskitem_5.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 0.8,
        eventType = {
            [1] = 1002,
            [2] = 1012,
        },
        id = 40,
    },
    [41] = {
        offset = {
            y = -40,
            x = 0,
        },
        tileGid = 203,
        order = 9,
        mapActorName = "3003009",
        mapActorIcon = "ui/kabalatree/event/floor_taskitem_6.png",
        scaleMap = 1.7,
        isShow = false,
        miniMapIcon = "ui/kabalatree/event/small_taskitem.png",
        scale = 0.8,
        eventType = {
            [1] = 1002,
            [2] = 1012,
        },
        id = 41,
    },
}