return {
    [1] = {
        pointName = "1230001",
        name = {
            [1] = 250060,
            [2] = 0.33,
        },
        id = 1,
        order = 1,
        icon = "icon/equipment/type/Kether.png",
        subType = 1,
    },
    [2] = {
        pointName = "",
        name = {
            [1] = 250120,
            [2] = 0.33,
        },
        id = 2,
        order = 2,
        icon = "",
        subType = 1,
    },
    [3] = {
        pointName = "",
        name = {
            [1] = 250200,
            [2] = 0.34,
        },
        id = 3,
        order = 3,
        icon = "",
        subType = 1,
    },
    [4] = {
        pointName = "",
        name = {
            [1] = 250050,
            [2] = 1.5,
        },
        id = 4,
        order = 4,
        icon = "",
        subType = 1,
    },
    [5] = {
        pointName = "",
        name = {
            [1] = 240040,
            [2] = 3,
        },
        id = 5,
        order = 5,
        icon = "",
        subType = 1,
    },
    [6] = {
        pointName = "",
        name = {
            [1] = 230030,
            [2] = 34.5,
        },
        id = 6,
        order = 6,
        icon = "",
        subType = 1,
    },
    [7] = {
        pointName = "",
        name = {
            [1] = 220020,
            [2] = 60,
        },
        id = 7,
        order = 7,
        icon = "",
        subType = 1,
    },
    [8] = {
        pointName = "1230003",
        name = {
            [1] = 250061,
            [2] = 0.25,
        },
        id = 8,
        order = 1,
        icon = "icon/equipment/type/Chokhmah.png",
        subType = 2,
    },
    [9] = {
        pointName = "",
        name = {
            [1] = 250071,
            [2] = 0.25,
        },
        id = 9,
        order = 2,
        icon = "",
        subType = 2,
    },
    [10] = {
        pointName = "",
        name = {
            [1] = 250121,
            [2] = 0.25,
        },
        id = 10,
        order = 3,
        icon = "",
        subType = 2,
    },
    [11] = {
        pointName = "",
        name = {
            [1] = 250201,
            [2] = 0.25,
        },
        id = 11,
        order = 4,
        icon = "",
        subType = 2,
    },
    [12] = {
        pointName = "",
        name = {
            [1] = 250051,
            [2] = 1.5,
        },
        id = 12,
        order = 5,
        icon = "",
        subType = 2,
    },
    [13] = {
        pointName = "",
        name = {
            [1] = 240041,
            [2] = 3,
        },
        id = 13,
        order = 6,
        icon = "",
        subType = 2,
    },
    [14] = {
        pointName = "",
        name = {
            [1] = 230031,
            [2] = 34.5,
        },
        id = 14,
        order = 7,
        icon = "",
        subType = 2,
    },
    [15] = {
        pointName = "",
        name = {
            [1] = 220021,
            [2] = 60,
        },
        id = 15,
        order = 8,
        icon = "",
        subType = 2,
    },
    [16] = {
        pointName = "1230005",
        name = {
            [1] = 250062,
            [2] = 0.5,
        },
        id = 16,
        order = 1,
        icon = "icon/equipment/type/Binah.png",
        subType = 3,
    },
    [17] = {
        pointName = "",
        name = {
            [1] = 250122,
            [2] = 0.5,
        },
        id = 17,
        order = 2,
        icon = "",
        subType = 3,
    },
    [18] = {
        pointName = "",
        name = {
            [1] = 250052,
            [2] = 1.5,
        },
        id = 18,
        order = 3,
        icon = "",
        subType = 3,
    },
    [19] = {
        pointName = "",
        name = {
            [1] = 240042,
            [2] = 3,
        },
        id = 19,
        order = 4,
        icon = "",
        subType = 3,
    },
    [20] = {
        pointName = "",
        name = {
            [1] = 230032,
            [2] = 34.5,
        },
        id = 20,
        order = 5,
        icon = "",
        subType = 3,
    },
    [21] = {
        pointName = "",
        name = {
            [1] = 220022,
            [2] = 60,
        },
        id = 21,
        order = 6,
        icon = "",
        subType = 3,
    },
    [22] = {
        pointName = "1230007",
        name = {
            [1] = 250073,
            [2] = 0.45,
        },
        id = 22,
        order = 1,
        icon = "icon/equipment/type/Chesed.png",
        subType = 4,
    },
    [23] = {
        pointName = "",
        name = {
            [1] = 250083,
            [2] = 0.55,
        },
        id = 23,
        order = 2,
        icon = "",
        subType = 4,
    },
    [24] = {
        pointName = "",
        name = {
            [1] = 250053,
            [2] = 1.5,
        },
        id = 24,
        order = 3,
        icon = "",
        subType = 4,
    },
    [25] = {
        pointName = "",
        name = {
            [1] = 240043,
            [2] = 3,
        },
        id = 25,
        order = 4,
        icon = "",
        subType = 4,
    },
    [26] = {
        pointName = "",
        name = {
            [1] = 230033,
            [2] = 34.5,
        },
        id = 26,
        order = 5,
        icon = "",
        subType = 4,
    },
    [27] = {
        pointName = "",
        name = {
            [1] = 220023,
            [2] = 60,
        },
        id = 27,
        order = 6,
        icon = "",
        subType = 4,
    },
    [28] = {
        pointName = "1230009",
        name = {
            [1] = 250054,
            [2] = 2.5,
        },
        id = 28,
        order = 1,
        icon = "icon/equipment/type/Geburah.png",
        subType = 5,
    },
    [29] = {
        pointName = "",
        name = {
            [1] = 240044,
            [2] = 3,
        },
        id = 29,
        order = 2,
        icon = "",
        subType = 5,
    },
    [30] = {
        pointName = "",
        name = {
            [1] = 230034,
            [2] = 34.5,
        },
        id = 30,
        order = 3,
        icon = "",
        subType = 5,
    },
    [31] = {
        pointName = "",
        name = {
            [1] = 220024,
            [2] = 60,
        },
        id = 31,
        order = 4,
        icon = "",
        subType = 5,
    },
    [32] = {
        pointName = "1230011",
        name = {
            [1] = 250075,
            [2] = 0.33,
        },
        id = 32,
        order = 1,
        icon = "icon/equipment/type/Tiphareth.png",
        subType = 6,
    },
    [33] = {
        pointName = "",
        name = {
            [1] = 250085,
            [2] = 0.33,
        },
        id = 33,
        order = 2,
        icon = "",
        subType = 6,
    },
    [34] = {
        pointName = "",
        name = {
            [1] = 250205,
            [2] = 0.34,
        },
        id = 34,
        order = 3,
        icon = "",
        subType = 6,
    },
    [35] = {
        pointName = "",
        name = {
            [1] = 250055,
            [2] = 1.5,
        },
        id = 35,
        order = 4,
        icon = "",
        subType = 6,
    },
    [36] = {
        pointName = "",
        name = {
            [1] = 240045,
            [2] = 3,
        },
        id = 36,
        order = 5,
        icon = "",
        subType = 6,
    },
    [37] = {
        pointName = "",
        name = {
            [1] = 230035,
            [2] = 34.5,
        },
        id = 37,
        order = 6,
        icon = "",
        subType = 6,
    },
    [38] = {
        pointName = "",
        name = {
            [1] = 220025,
            [2] = 60,
        },
        id = 38,
        order = 7,
        icon = "",
        subType = 6,
    },
    [39] = {
        pointName = "1230013",
        name = {
            [1] = 250086,
            [2] = 0.5,
        },
        id = 39,
        order = 1,
        icon = "icon/equipment/type/Netzach.png",
        subType = 7,
    },
    [40] = {
        pointName = "",
        name = {
            [1] = 250096,
            [2] = 0.5,
        },
        id = 40,
        order = 2,
        icon = "",
        subType = 7,
    },
    [41] = {
        pointName = "",
        name = {
            [1] = 250056,
            [2] = 1.5,
        },
        id = 41,
        order = 3,
        icon = "",
        subType = 7,
    },
    [42] = {
        pointName = "",
        name = {
            [1] = 240046,
            [2] = 3,
        },
        id = 42,
        order = 4,
        icon = "",
        subType = 7,
    },
    [43] = {
        pointName = "",
        name = {
            [1] = 230036,
            [2] = 34.5,
        },
        id = 43,
        order = 5,
        icon = "",
        subType = 7,
    },
    [44] = {
        pointName = "",
        name = {
            [1] = 220026,
            [2] = 60,
        },
        id = 44,
        order = 6,
        icon = "",
        subType = 7,
    },
    [45] = {
        pointName = "1230015",
        name = {
            [1] = 250107,
            [2] = 0.5,
        },
        id = 45,
        order = 1,
        icon = "icon/equipment/type/Hod.png",
        subType = 8,
    },
    [46] = {
        pointName = "",
        name = {
            [1] = 250057,
            [2] = 1.5,
        },
        id = 46,
        order = 3,
        icon = "",
        subType = 8,
    },
    [47] = {
        pointName = "",
        name = {
            [1] = 240047,
            [2] = 3,
        },
        id = 47,
        order = 4,
        icon = "",
        subType = 8,
    },
    [48] = {
        pointName = "",
        name = {
            [1] = 230037,
            [2] = 34.5,
        },
        id = 48,
        order = 5,
        icon = "",
        subType = 8,
    },
    [49] = {
        pointName = "",
        name = {
            [1] = 220027,
            [2] = 60,
        },
        id = 49,
        order = 6,
        icon = "",
        subType = 8,
    },
    [50] = {
        pointName = "",
        name = {
            [1] = 250098,
            [2] = 0.33,
        },
        id = 50,
        order = 2,
        icon = "",
        subType = 9,
    },
    [51] = {
        pointName = "",
        name = {
            [1] = 250108,
            [2] = 0.33,
        },
        id = 51,
        order = 3,
        icon = "",
        subType = 9,
    },
    [52] = {
        pointName = "",
        name = {
            [1] = 250058,
            [2] = 1.5,
        },
        id = 52,
        order = 4,
        icon = "",
        subType = 9,
    },
    [53] = {
        pointName = "",
        name = {
            [1] = 240048,
            [2] = 3,
        },
        id = 53,
        order = 5,
        icon = "",
        subType = 9,
    },
    [54] = {
        pointName = "",
        name = {
            [1] = 230038,
            [2] = 34.5,
        },
        id = 54,
        order = 6,
        icon = "",
        subType = 9,
    },
    [55] = {
        pointName = "",
        name = {
            [1] = 220028,
            [2] = 60,
        },
        id = 55,
        order = 7,
        icon = "",
        subType = 9,
    },
    [56] = {
        pointName = "1230019",
        name = {
            [1] = 250099,
            [2] = 0.33,
        },
        id = 56,
        order = 1,
        icon = "icon/equipment/type/Malkuth.png",
        subType = 10,
    },
    [57] = {
        pointName = "",
        name = {
            [1] = 250109,
            [2] = 0.33,
        },
        id = 57,
        order = 3,
        icon = "",
        subType = 10,
    },
    [58] = {
        pointName = "",
        name = {
            [1] = 250059,
            [2] = 1.5,
        },
        id = 58,
        order = 4,
        icon = "",
        subType = 10,
    },
    [59] = {
        pointName = "",
        name = {
            [1] = 240049,
            [2] = 3,
        },
        id = 59,
        order = 5,
        icon = "",
        subType = 10,
    },
    [60] = {
        pointName = "",
        name = {
            [1] = 230039,
            [2] = 34.5,
        },
        id = 60,
        order = 6,
        icon = "",
        subType = 10,
    },
    [61] = {
        pointName = "",
        name = {
            [1] = 220029,
            [2] = 60,
        },
        id = 61,
        order = 7,
        icon = "",
        subType = 10,
    },
    [94] = {
        pointName = "",
        name = {
            [1] = 250279,
            [2] = 0.34,
        },
        id = 94,
        order = 2,
        icon = "",
        subType = 10,
    },
    [80] = {
        pointName = "1230017",
        name = {
            [1] = 250278,
            [2] = 0.34,
        },
        id = 80,
        order = 1,
        icon = "icon/equipment/type/Yesod.png",
        subType = 9,
    },
    [72] = {
        pointName = "",
        name = {
            [1] = 250277,
            [2] = 0.5,
        },
        id = 72,
        order = 2,
        icon = "",
        subType = 8,
    },
}