local t = {
		{
			name="cityMainView",
			ui ="cityMainView.lua",
			x=0,
			y=0,
			speed=0,
			layer="city",
			canLoad=true,
			logic="",
		},
		{
			name="cityInfoView",
			ui ="cityInfoView.lua",
			x=0,
			y=0,
			speed=0,
			layer="city",
			canLoad=true,
			logic="",
		},
		{
			name="cityWorkView",
			ui ="cityWorkView.lua",
			x=0,
			y=0,
			speed=0,
			layer="city",
			canLoad=true,
			logic="",
		},
		{
			name="citySpriteSelectView",
			ui ="citySpriteSelectView.lua",
			x=0,
			y=0,
			speed=0,
			layer="city",
			canLoad=true,
			logic="",
		},
		{
			name="buildLevelUpView",
			ui ="buildLevelUpView.lua",
			x=0,
			y=0,
			speed=0,
			layer="city",
			canLoad=true,
			logic="",
		},
		{
			name="buildUnlockView",
			ui ="buildUnlockView.lua",
			x=0,
			y=0,
			speed=0,
			layer="city",
			canLoad=true,
			logic="",
		},
		{
			name="makeFoodView",
			ui ="makeFoodView.lua",
			x=0,
			y=0,
			speed=0,
			layer="city",
			canLoad=true,
			logic="",
		},
}
return t
