local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-bingoDiceView_Layer1_bingo_Game",
			UUID = "324291f1_c6b3_430e_8365_8eb64067568d",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
					UUID = "96bbc730_cc2a_408a_8bbe_3d7a99c89534",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_bg_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "da96084b_063d_4695_a572_17fad0c1710a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/bg.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Image_inner_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "2b37013b_4202_4169_9553_a823b06ffd00",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "Image_inner",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/dice/007.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "1386",
							ZOrder = "1",
						},
						{
							controlID = "Image_di_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "4ac0553b_d023_4533_9d26_b19de7a8382f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "518",
							ignoreSize = "True",
							name = "Image_di",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/dice/006.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "966",
							ZOrder = "1",
						},
						{
							controlID = "Panel_mask_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "2f72ce5f_e7bc_428c_b89c_3847f3a0cc73",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "300",
							ignoreSize = "False",
							name = "Panel_mask",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -17,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "600",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "ScrollView_dice_Panel_mask_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "51177655_74d8_44ac_a86a_e7d15b79ac53",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "100",
									bIsOpenClipping = "False",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FF0000FF;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									direction = "2",
									dstBlendFunc = "771",
									height = "110",
									ignoreSize = "False",
									innerHeight = "110",
									innerWidth = "350",
									name = "ScrollView_dice",
									showScrollbar = "False",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 31,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "350",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "top_part1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "f89b8681_1816_468f_84a4_644f55149309",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "1",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "60",
							ignoreSize = "False",
							name = "top_part1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -568,
								PositionY = 320,
								IsPercent = true,
								PercentX = -50,
								PercentY = 50,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1136",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_back_top_part1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "14262da5_6f2c_4a46_a87b_c40c0a820af6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "52",
									ignoreSize = "True",
									name = "Button_back",
									normal = "ui/common/btn_back.png",
									pressed = "ui/common/btn_back.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 72,
										PositionY = -32,
									},
									UItype = "Button",
									width = "62",
									ZOrder = "1",
								},
								{
									controlID = "Image_zuan_bg_top_part1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "ae87fb4c_e95e_47a5_8be0_6a7c88437de6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "False",
									name = "Image_zuan_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/common/res_bg.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 970,
										PositionY = -37,
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_chip_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "b2ed61a9_4144_4aaa_a19d_c3f07445f829",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "True",
											name = "Label_chip",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "99999999",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -49,
												PositionY = -2,
											},
											width = "114",
											ZOrder = "1",
										},
										{
											controlID = "Button_add_chip_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "783a5193_1502_4285_87ec_c90224c62ff9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "38",
											ignoreSize = "True",
											name = "Button_add_chip",
											normal = "ui/common/jiahao.png",
											pressed = "ui/common/jiahao.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 92,
												PositionY = 1,
											},
											UItype = "Button",
											width = "38",
											ZOrder = "1",
										},
										{
											controlID = "Image_chip_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "484903d4_52c2_4537_bbee_99011e55f91b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_chip",
											scaleX = "0.5",
											scaleY = "0.5",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/system/005.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -72,
												PositionY = 1,
											},
											width = "100",
											ZOrder = "1",
										},
										{
											controlID = "Label_chip_delta_Image_zuan_bg_top_part1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "7909cfc3_b64b_48eb_b23e_9dacacb056b6",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#00FFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "0",
											ignoreSize = "True",
											name = "Label_chip_delta",
											nTextAlign = "0",
											nTextHAlign = "0",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 6,
												PositionY = -2,
											},
											width = "0",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "9a8c55ba_5023_45d0_87f3_c340283c2c3d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "242",
							ignoreSize = "True",
							name = "Image_bottom",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/activity/bingoGame/dice/004.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -169,
							},
							width = "954",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Button_down_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "938306e7_1270_42a7_a355_fe46605b1eac",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_down",
									normal = "ui/activity/bingoGame/luckyPlate/007.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -381,
										PositionY = -71,
									},
									UItype = "Button",
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_del_Button_down_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "b1800f01_aac9_4883_901e_9897f16030df",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "28",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "35",
											ignoreSize = "True",
											name = "Label_del",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "-",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -19,
												PositionY = 2,
											},
											width = "15",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Button_down_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "04faf092_daa9_4647_bf14_cc3aa1f80af6",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											scaleX = "0.5",
											scaleY = "0.5",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/item/goods/500066.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 18,
												PositionY = 2,
											},
											width = "100",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_up_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "0fcbf096_cea9_4eb6_bc50_c8680e912868",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_up",
									normal = "ui/activity/bingoGame/luckyPlate/007.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -238,
										PositionY = -71,
									},
									UItype = "Button",
									width = "110",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_add_Button_up_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "cec0ddf4_63c3_4d9d_b7ff_b4e27ba99f57",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "28",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "35",
											ignoreSize = "True",
											name = "Label_add",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "+",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -15,
												PositionY = 2,
											},
											width = "22",
											ZOrder = "1",
										},
										{
											controlID = "Image_icon_Button_up_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "4a0fedcc_994c_4df5_98bc_65206582c828",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "100",
											ignoreSize = "True",
											name = "Image_icon",
											scaleX = "0.5",
											scaleY = "0.5",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "icon/item/goods/500066.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 18,
												PositionY = 2,
											},
											width = "100",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_do_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "05c4e2b4_0dad_40c3_9335_d492947c6767",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									ignoreSize = "True",
									name = "Button_do",
									normal = "ui/activity/bingoGame/luckyPlate/006.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 350,
										PositionY = -71,
									},
									UItype = "Button",
									width = "156",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_enterPlot_Button_do_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
											UUID = "6393e5cd_7235_47d5_90c2_679304ac9ff0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFB83F59",
												StrokeSize = 2,
											},
											height = "34",
											ignoreSize = "True",
											name = "Label_enterPlot",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "开始投掷",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "102",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Label_vote_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "fd644184_ddf8_4ac8_b5ad_a47f8a5d15bb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "50",
									ignoreSize = "False",
									name = "Label_vote",
									nTextAlign = "1",
									nTextHAlign = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "下注说明下注说明下注说明下注说明下注说明下注说明",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 48,
										PositionY = -71,
									},
									width = "310",
									ZOrder = "1",
								},
								{
									controlID = "Image_dot1_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "a5b1e6d9_b0ee_4741_99ef_033b5b03ddce",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "Image_dot1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/luckyPlate/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -127,
										PositionY = -71,
									},
									width = "24",
									ZOrder = "1",
								},
								{
									controlID = "Image_dot2_Image_bottom_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "ea7d2bb6_a77e_43b5_ade1_f267eb9458f4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "Image_dot2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/luckyPlate/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 222,
										PositionY = -71,
									},
									width = "24",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_vote_1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "0084b9cb_2e77_4b7a_96d3_d4d15be65ba3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "False",
							name = "Panel_vote_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -313,
								PositionY = -195,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "314",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_select_Panel_vote_1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "aa1f9b3a_f238_4a33_bd09_8a8895e868bf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/dice/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "314",
									ZOrder = "1",
								},
								{
									controlID = "Label_num_Panel_vote_1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "b4144dfa_d1af_4b19_8660_9bc1d5aa3cd8",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "5000",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 42,
										PositionY = 51,
									},
									width = "73",
									ZOrder = "1",
								},
								{
									controlID = "Image_vote_Panel_vote_1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "77c2d901_e48f_4636_96da_7962789f0020",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "90",
									ignoreSize = "True",
									name = "Image_vote",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/dice/003.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = 68,
									},
									width = "90",
									ZOrder = "1",
								},
								{
									controlID = "Label_odds_num_Panel_vote_1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "eaa95e17_0fe8_4700_9fe4_51904f4878e9",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_odds_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "赔率 x10",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = 86,
									},
									width = "99",
									ZOrder = "1",
								},
								{
									controlID = "Image_voteIcon_Panel_vote_1_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "be9a920b_609d_4a56_a547_4776eae9f4e6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_voteIcon",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/item/goods/500066.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 15,
										PositionY = 50,
									},
									width = "100",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_vote_3_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "1729cdd8_edd5_4006_b273_bfb59bdbff25",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "False",
							name = "Panel_vote_3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = -195,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "314",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_select_Panel_vote_3_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "b7e7ab3c_bfeb_4961_aaa5_332257642c8f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/dice/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "314",
									ZOrder = "1",
								},
								{
									controlID = "Label_num_Panel_vote_3_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "712941ff_ff5b_4407_9e36_2faa5bc7a7c1",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "5000",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 42,
										PositionY = 51,
									},
									width = "73",
									ZOrder = "1",
								},
								{
									controlID = "Image_vote_Panel_vote_3_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "3b7a8693_6615_4df1_8c94_f538e64c7431",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "90",
									ignoreSize = "True",
									name = "Image_vote",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/dice/003.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = 68,
									},
									width = "90",
									ZOrder = "1",
								},
								{
									controlID = "Label_odds_num_Panel_vote_3_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "3663c2f9_779e_4c50_a604_91073e49d59f",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_odds_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "赔率 x10",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = 86,
									},
									width = "99",
									ZOrder = "1",
								},
								{
									controlID = "Image_split_Panel_vote_3_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "652778c8_e5d2_48fa_b892_3e0908a060fe",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "108",
									ignoreSize = "True",
									name = "Image_split",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/dice/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = 70,
									},
									width = "318",
									ZOrder = "1",
								},
								{
									controlID = "Image_voteIcon_Panel_vote_3_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "6a5397c0_c476_41c7_85f3_64a691e13276",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_voteIcon",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/item/goods/500066.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 15,
										PositionY = 50,
									},
									width = "100",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "Panel_vote_2_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "6b6658dc_aee6_4f80_bbd1_6d636ec87850",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF0000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "140",
							ignoreSize = "False",
							name = "Panel_vote_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 313,
								PositionY = -195,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "314",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_select_Panel_vote_2_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "4c754c6d_02ea_4ea8_84c0_2a08e8e488c3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "120",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/dice/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "314",
									ZOrder = "1",
								},
								{
									controlID = "Label_num_Panel_vote_2_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "2aec280e_639c_4cab_8174_68633e3df85b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "20",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "25",
									ignoreSize = "True",
									name = "Label_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "5000",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 42,
										PositionY = 51,
									},
									width = "73",
									ZOrder = "1",
								},
								{
									controlID = "Image_vote_Panel_vote_2_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "06ebadff_527f_477b_b565_8fd152dce5e3",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "90",
									ignoreSize = "True",
									name = "Image_vote",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/activity/bingoGame/dice/003.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -65,
										PositionY = 68,
									},
									width = "90",
									ZOrder = "1",
								},
								{
									controlID = "Label_odds_num_Panel_vote_2_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "2e2f0344_7843_4455_b169_25f636cbf916",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_odds_num",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "赔率 x10",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionY = 86,
									},
									width = "99",
									ZOrder = "1",
								},
								{
									controlID = "Image_voteIcon_Panel_vote_2_Panel_root_Panel-bingoDiceView_Layer1_bingo_Game",
									UUID = "ecd0dc51_9db2_4776_9c21_b51fa53da74e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "Image_voteIcon",
									scaleX = "0.5",
									scaleY = "0.5",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/item/goods/500066.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 15,
										PositionY = 50,
									},
									width = "100",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-bingoDiceView_Layer1_bingo_Game",
					UUID = "ec92d0fa_d404_4ce9_854f_0bee0130b0a3",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = -442,
						TopPosition = 762,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_diceItem_Panel_prefab_Panel-bingoDiceView_Layer1_bingo_Game",
							UUID = "744c2d33_f759_46c5_9532_7f27e47e1160",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFFF4500;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "110",
							ignoreSize = "False",
							name = "Panel_diceItem",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -672,
								PositionY = 162,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "110",
							ZOrder = "1",
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/activity/bingoGame/bg.png",
			"ui/activity/bingoGame/dice/007.png",
			"ui/activity/bingoGame/dice/006.png",
			"ui/common/btn_back.png",
			"ui/common/res_bg.png",
			"ui/common/jiahao.png",
			"icon/system/005.png",
			"ui/activity/bingoGame/dice/004.png",
			"ui/activity/bingoGame/luckyPlate/007.png",
			"icon/item/goods/500066.png",
			"ui/activity/bingoGame/luckyPlate/006.png",
			"ui/activity/bingoGame/luckyPlate/005.png",
			"ui/activity/bingoGame/dice/005.png",
			"ui/activity/bingoGame/dice/003.png",
			"ui/activity/bingoGame/dice/008.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

