return {
    [4104153] = {
        offset = {
            y = 120,
            x = -74,
        },
        path = "effect/dating/ui_superKanban_10415/main_effect_10415",
        action = "animation3",
        isLoop = true,
        id = 4104153,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10415_base.png",
        Zorder = 0,
    },
    [4101091] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10109/effect_main_10109_1",
        action = "stand",
        isLoop = true,
        id = 4101091,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 3,
    },
    [4101093] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10109/effect_main_10109_3",
        action = "stand",
        isLoop = true,
        id = 4101093,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_shixiang_high_10109_middle.png",
        Zorder = 1,
    },
    [1014] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1014,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4101132] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10113/effect_shixiangkanban",
        action = "animation2",
        isLoop = true,
        id = 4101132,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1015] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1015,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4102131] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10213/effect_main_10213",
        action = "animation_down",
        isLoop = true,
        id = 4102131,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_zhezhi_high_10213_middle1.png",
        Zorder = 0,
    },
    [4102164] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10216/effect_main_10216",
        action = "effect_main_10216_liuxing",
        isLoop = true,
        id = 4102164,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [413001] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_13002/texiao",
        action = "down",
        isLoop = true,
        id = 413001,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1017] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1017,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411214] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11214/main_effect_11214",
        action = "beijing",
        isLoop = true,
        id = 411214,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1018] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1018,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4101131] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10113/effect_shixiangkanban",
        action = "animation",
        isLoop = true,
        id = 4101131,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1019] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1019,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4102161] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10216/effect_main_10216",
        action = "effect_main_10216_up",
        isLoop = true,
        id = 4102161,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4102163] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10216/effect_main_10216",
        action = "effect_main_10216_dpwn",
        isLoop = true,
        id = 4102163,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1020] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1020,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4104221] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10422/main_effect_10422",
        action = "main_effect_10422_down",
        isLoop = true,
        id = 4104221,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1022] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1022,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4101161] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10116/effect_main_10116",
        action = "playup",
        isLoop = true,
        id = 4101161,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410708] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10708/main_effect_10708",
        action = "animation",
        isLoop = true,
        id = 410708,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1024] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1024,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1025] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1025,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1026] = {
        offset = {
        },
        path = "",
        action = "zhuchang",
        isLoop = true,
        id = 1026,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1027] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1027,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1028] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1028,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1029] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1029,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1030] = {
        offset = {
        },
        path = "",
        action = "xunhuan",
        isLoop = true,
        id = 1030,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4101232] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10123/main_effect_10123",
        action = "animation3",
        isLoop = true,
        id = 4101232,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1031] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1031,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1032] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1032,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1033] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1033,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1034] = {
        offset = {
            y = 3,
            x = 0,
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1034,
        particle = "",
        lag = 0,
        scales = 0.99,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1035] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1035,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1036] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1036,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [412504] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12504/junai_kanban",
        action = "BG_hou",
        isLoop = true,
        id = 412504,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 5,
    },
    [1037] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1037,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4101231] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10123/main_effect_10123",
        action = "animation2",
        isLoop = true,
        id = 4101231,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4101233] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4101233,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10123_base.png",
        Zorder = 0,
    },
    [1039] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1039,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1040] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1040,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1041] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1041,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1042] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1042,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1043] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1043,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1044] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1044,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1046] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1046,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1049] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1049,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1050] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1050,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1051] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1051,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1052] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1052,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1053] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1053,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410213] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10213/effect_main_10213",
        action = "animation_up",
        isLoop = true,
        id = 410213,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1054] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1054,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1055] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1055,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1056] = {
        offset = {
            y = 0,
            x = 31,
        },
        path = "",
        action = "zhuchang",
        isLoop = true,
        id = 1056,
        particle = "",
        lag = 0,
        scales = 1.21,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1057] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1057,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1058] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1058,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1059] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1059,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1060] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1060,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1061] = {
        offset = {
            y = 0,
            x = 10,
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1061,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1062] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1062,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1063] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1063,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1064] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1064,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1065] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1065,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410219] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10219/effect_main_10219",
        action = "animation",
        isLoop = true,
        id = 410219,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1066] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1066,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4131014] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_13102/main_effect_13102",
        action = "waveOn_down",
        isLoop = true,
        id = 4131014,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1067] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1067,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1068] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1068,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1069] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1069,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1070] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1070,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1071] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1071,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410222] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10222/main_effect_10222",
        action = "down",
        isLoop = true,
        id = 410222,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 1,
    },
    [1072] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1072,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1073] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1073,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4131011] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4131011,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_13102_high_middle.png",
        Zorder = 0,
    },
    [1074] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1074,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4131015] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4131015,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_13102_high_middle.png",
        Zorder = 0,
    },
    [1075] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1075,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1076] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1076,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411502] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11502/skeleton",
        action = "animation",
        isLoop = true,
        id = 411502,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1077] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1077,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1078] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1078,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1079] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1079,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1080] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1080,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1081] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1081,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1082] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1082,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4129034] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12903/main_effect_12903",
        action = "animation4",
        isLoop = true,
        id = 4129034,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1083] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1083,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1084] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1084,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1085] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1085,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1086] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1086,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1087] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1087,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1088] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1088,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1089] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1089,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4129031] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12903/main_effect_12903",
        action = "animation2",
        isLoop = true,
        id = 4129031,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1090] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1090,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4129035] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12903/main_effect_12903",
        action = "animation5",
        isLoop = true,
        id = 4129035,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1091] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1091,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1092] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1092,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1093] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1093,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1094] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1094,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1095] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1095,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1096] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1096,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1097] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1097,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1098] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1098,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4127023] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12702/main_effect_12702",
        action = "main_effect_12702_02",
        isLoop = false,
        id = 4127023,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1099] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1099,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1100] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1100,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1101] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1101,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [413303] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_13303/main_effect_13303",
        action = "up",
        isLoop = true,
        id = 413303,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1102] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1102,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1103] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1103,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4126021] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12602/main_effect_12602_up",
        action = "main_effect_12602_up",
        isLoop = false,
        id = 4126021,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 2,
    },
    [1104] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1104,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410111] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10111/effect_main_10111",
        action = "animation",
        isLoop = true,
        id = 410111,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4125040] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4125040,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_12504_middle.png",
        Zorder = 6,
    },
    [4125042] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12504/junai_kanban",
        action = "texiao_hou",
        isLoop = false,
        id = 4125042,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 2,
    },
    [4125044] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4125044,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_12504_base.png",
        Zorder = 1,
    },
    [411901] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11901/main_effect_11901",
        action = "main_effect_11901",
        isLoop = true,
        id = 411901,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410113] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10113/effect_shixiangkanbanBG",
        action = "animation",
        isLoop = true,
        id = 410113,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1110] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1110,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1111] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1111,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1112] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1112,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4123022] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12302/main_effect_12302",
        action = "animation4",
        isLoop = true,
        id = 4123022,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4123024] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4123024,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_12302_middle.png",
        Zorder = 0,
    },
    [1114] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1114,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4125043] = {
        offset = {
            y = 46,
            x = -11,
        },
        path = "effect/dating/ui_superKanban_12504/junai_kanban",
        action = "texiao_qian",
        isLoop = false,
        id = 4125043,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 3,
    },
    [410116] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10116/effect_main_10116",
        action = "playbelow",
        isLoop = true,
        id = 410116,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1116] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1116,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1117] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1117,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4122022] = {
        offset = {
            y = -30,
            x = 15,
        },
        path = "effect/dating/ui_superKanban_12202/effect_main_12202",
        action = "animation2",
        isLoop = true,
        id = 4122022,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1119] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1119,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4124041] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12404/effect_main_12404",
        action = "effect_main_12404_down",
        isLoop = true,
        id = 4124041,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4123021] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12302/main_effect_12302",
        action = "animation2",
        isLoop = true,
        id = 4123021,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4123023] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12302/main_effect_12302",
        action = "animation5",
        isLoop = true,
        id = 4123023,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1121] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1121,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [412802] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12802/main_effect_12802",
        action = "animation",
        isLoop = true,
        id = 412802,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1122] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1122,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1123] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1123,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1124] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1124,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1125] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1125,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4122021] = {
        offset = {
            y = -30,
            x = 15,
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4122021,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_12202_middle.png",
        Zorder = 0,
    },
    [1126] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1126,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1127] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1127,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1128] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1128,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410123] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10123/main_effect_10123",
        action = "animation",
        isLoop = true,
        id = 410123,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1130] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1130,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410507] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10507/effect_main_10507",
        action = "animation",
        isLoop = true,
        id = 410507,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1131] = {
        offset = {
        },
        path = "effect/dating_scene/eff_yingzikongjian/out/yingzikongjian",
        action = "animation",
        isLoop = true,
        id = 1131,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410125] = {
        offset = {
            y = 13,
            x = 0,
        },
        path = "effect/dating/ui_superKanban_10125/main_effect_yanhua",
        action = "animation",
        isLoop = false,
        id = 410125,
        particle = "",
        lag = 1.3,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 1,
    },
    [410509] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10509/effect_main_10509",
        action = "animation",
        isLoop = true,
        id = 410509,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4118012] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11801/main_effect_11801qianjing",
        action = "animation",
        isLoop = true,
        id = 4118012,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410511] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10511/effect_main_10511",
        action = "down",
        isLoop = true,
        id = 410511,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4118022] = {
        offset = {
        },
        path = "effect/dating/ui_doubleKanban_11802/shuangrenkanban",
        action = "firework01_d",
        isLoop = true,
        id = 4118022,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_mikoto_kuroko_double_11802_middle2.png",
        Zorder = 0,
    },
    [412302] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12302/main_effect_12302",
        action = "animation",
        isLoop = true,
        id = 412302,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410514] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10514/main_effect_10514_bg",
        action = "animation",
        isLoop = true,
        id = 410514,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 1,
    },
    [4118011] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11801/main_effect_11801shuye",
        action = "animation",
        isLoop = true,
        id = 4118011,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4118021] = {
        offset = {
        },
        path = "effect/dating/ui_doubleKanban_11802/shuangrenkanban",
        action = "firework01_a",
        isLoop = true,
        id = 4118021,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_mikoto_kuroko_double_11802_middle3.png",
        Zorder = 0,
    },
    [4118023] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4118023,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411801] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11801/main_effect_11801yun",
        action = "animation",
        isLoop = true,
        id = 411801,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_11801_middle.png",
        Zorder = 0,
    },
    [411802] = {
        offset = {
        },
        path = "effect/dating/ui_doubleKanban_11802/shuangrenkanban",
        action = "firework01",
        isLoop = true,
        id = 411802,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_mikoto_kuroko_double_11802_middle1.png",
        Zorder = 0,
    },
    [412702] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12702/main_effect_12702",
        action = "main_effect_12702_di",
        isLoop = true,
        id = 412702,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 1,
    },
    [4111062] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11106/main_effect_11106",
        action = "main_effect_11106_zhong",
        isLoop = true,
        id = 4111062,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4113081] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4113081,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_qizui_high_11308_top1.png",
        Zorder = 1,
    },
    [4113083] = {
        offset = {
            y = -390,
            x = -120,
        },
        path = "effect/dating/ui_superKanban_11308/effect_main_11308",
        action = "animation1",
        isLoop = false,
        id = 4113083,
        particle = "",
        lag = 0.001,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 3,
    },
    [4110062] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11006/paopao1",
        action = "1",
        isLoop = true,
        id = 4110062,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4110064] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11006/paopao3",
        action = "3",
        isLoop = true,
        id = 4110064,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4111061] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11106/main_effect_11106",
        action = "main_effect_11106_qian",
        isLoop = true,
        id = 4111061,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410117] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10117/effect_main_10120",
        action = "animation",
        isLoop = true,
        id = 410117,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4112091] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4112091,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_wanyouli_high_11209_middle.png",
        Zorder = 0,
    },
    [4112124] = {
        offset = {
            y = 0,
            x = 15,
        },
        path = "effect/dating/ui_superKanban_11212/main_effect_11212_texiao",
        action = "animation",
        isLoop = false,
        id = 4112124,
        particle = "",
        lag = 0.05,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 5,
    },
    [412202] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12202/effect_main_12202",
        action = "animation",
        isLoop = true,
        id = 412202,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_12202_base.png",
        Zorder = 0,
    },
    [411308] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11308/effect_main_11308",
        action = "animation",
        isLoop = true,
        id = 411308,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4113152] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11315/main_effect_11315",
        action = "animation3",
        isLoop = true,
        id = 4113152,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4113154] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4113154,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_11315_base.png",
        Zorder = 0,
    },
    [4102221] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10222/main_effect_10222",
        action = "up",
        isLoop = true,
        id = 4102221,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 2,
    },
    [4110061] = {
        offset = {
            y = 0,
            x = 10,
        },
        path = "effect/dating/ui_superKanban_11006/meirenyubeijing14",
        action = "animation",
        isLoop = true,
        id = 4110061,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4110063] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11006/paopao2",
        action = "2",
        isLoop = true,
        id = 4110063,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4110065] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11006/paopao4",
        action = "4",
        isLoop = true,
        id = 4110065,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4112142] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11214/main_effect_11214",
        action = "zhong",
        isLoop = true,
        id = 4112142,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411010] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11010/main_effect_11010",
        action = "animation",
        isLoop = true,
        id = 411010,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410416] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10416/effects_hfkuangsankanban",
        action = "effects_hfkuangsankanban_down",
        isLoop = true,
        id = 410416,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4104161] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10416/effects_hfkuangsankanban",
        action = "effects_hfkuangsankanban_up ",
        isLoop = true,
        id = 4104161,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4101234] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10123/main_effect_10123",
        action = "animation4",
        isLoop = true,
        id = 4101234,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4112121] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11212/main_effect_11212_qianjing",
        action = "animation2",
        isLoop = true,
        id = 4112121,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 3,
    },
    [4112123] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11212/main_effect_11212_tiankong",
        action = "animation",
        isLoop = true,
        id = 4112123,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_wanyouli_high_11212.png",
        Zorder = 1,
    },
    [4126022] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12602/main_effect_12602_down1",
        action = "main_effect_12602_down1",
        isLoop = false,
        id = 4126022,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1120] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1120,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4113182] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4113182,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_qizui_high_11308_top2.png",
        Zorder = 2,
    },
    [4113153] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11315/main_effect_11315_luren",
        action = "animation",
        isLoop = true,
        id = 4113153,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [413101] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_13102/main_effect_13102",
        action = "waveOff_down",
        isLoop = true,
        id = 413101,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4110091] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11009/main_effect_11009",
        action = "animation2",
        isLoop = true,
        id = 4110091,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 4,
    },
    [4110093] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4110093,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_11009_base.png",
        Zorder = 1,
    },
    [4108082] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10808/main_effect_10808",
        action = "animation3",
        isLoop = true,
        id = 4108082,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10808_middle.png",
        Zorder = 0,
    },
    [4108084] = {
        offset = {
            y = 20,
            x = 127,
        },
        path = "effect/dating/ui_superKanban_10808/main_effect_10808_renwu",
        action = "animation",
        isLoop = true,
        id = 4108084,
        particle = "",
        lag = 0,
        scales = 0.26,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410119] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10119/hanfushixiangjangkanban",
        action = "animation",
        isLoop = true,
        id = 410119,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4112141] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11214/main_effect_11214",
        action = "qian",
        isLoop = true,
        id = 4112141,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4131017] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_13102/main_effect_13102",
        action = "waveOn_up",
        isLoop = true,
        id = 4131017,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4131013] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_13102/main_effect_13102",
        action = "waveOff_up",
        isLoop = true,
        id = 4131013,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4130011] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_13002/texiao",
        action = "up",
        isLoop = true,
        id = 4130011,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411315] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11315/main_effect_11315",
        action = "animation",
        isLoop = true,
        id = 411315,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4127022] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12702/main_effect_12702",
        action = "main_effect_12702_03",
        isLoop = false,
        id = 4127022,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 2,
    },
    [4127021] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12702/main_effect_12702",
        action = "main_effect_12702_01",
        isLoop = true,
        id = 4127021,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4104232] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10423/main_effect_10423",
        action = "main_effect_10423_qian",
        isLoop = true,
        id = 4104232,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4107082] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10708/main_effect_10708",
        action = "animation3",
        isLoop = true,
        id = 4107082,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4107084] = {
        offset = {
            y = -197,
            x = -398,
        },
        path = "effect/dating/ui_superKanban_10708/main_effect_10708_renwu",
        action = "animation",
        isLoop = true,
        id = 4107084,
        particle = "",
        lag = 0,
        scales = 0.25,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1107] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1107,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410607] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10607/main_effect_10607",
        action = "main_effect_10607_down",
        isLoop = true,
        id = 410607,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4108081] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10808/main_effect_10808",
        action = "animation2",
        isLoop = true,
        id = 4108081,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4108083] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4108083,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10808_base.png",
        Zorder = 0,
    },
    [4106072] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10607/main_effect_10607_yan",
        action = "animation",
        isLoop = true,
        id = 4106072,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4104231] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10423/main_effect_10423",
        action = "main_effect_10423_zhong",
        isLoop = true,
        id = 4104231,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410423] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10423/main_effect_10423",
        action = "main_effect_10423_hou",
        isLoop = true,
        id = 410423,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4129033] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4129033,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_12903_middle.png",
        Zorder = 0,
    },
    [4124042] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4124042,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_12404_base.png",
        Zorder = 0,
    },
    [1038] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1038,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410808] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10808/main_effect_10808",
        action = "animation",
        isLoop = true,
        id = 410808,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410409] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10409/effect_main_10409",
        action = "animation",
        isLoop = true,
        id = 410409,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_kuangsan_high_10409_middle.png",
        Zorder = 0,
    },
    [412404] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12404/effect_main_12404",
        action = "effect_main_12404_up",
        isLoop = true,
        id = 412404,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4107081] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10708/main_effect_10708",
        action = "animation2",
        isLoop = true,
        id = 4107081,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4107083] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4107083,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10708_base.png",
        Zorder = 0,
    },
    [410426] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10426/main_effect_10426",
        action = "animation",
        isLoop = true,
        id = 410426,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1105] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1105,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1005] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1005,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1106] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1106,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4106071] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10607/main_effect_10607",
        action = "main_effect_10607_up",
        isLoop = true,
        id = 4106071,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410414] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10414/effect_main_10414",
        action = "play",
        isLoop = true,
        id = 410414,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1002] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1002,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1108] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1108,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410415] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10415/main_effect_10415",
        action = "animation",
        isLoop = true,
        id = 410415,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411106] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11106/main_effect_11106",
        action = "main_effect_11106_hou",
        isLoop = true,
        id = 411106,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_11106_base.png",
        Zorder = 0,
    },
    [1109] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1109,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1003] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1003,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410422] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10422/main_effect_10422",
        action = "main_effect_10422_up",
        isLoop = true,
        id = 410422,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4125041] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12504/junai_kanban",
        action = "BG_qian",
        isLoop = true,
        id = 4125041,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 4,
    },
    [1008] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1008,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1004] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1004,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411311] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11311/effect_main_11313",
        action = "animation",
        isLoop = true,
        id = 411311,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [412602] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12602/main_effect_12602_down",
        action = "main_effect_12602_down",
        isLoop = true,
        id = 412602,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1113] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1113,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1001] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = false,
        id = 1001,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = false,
        speBg = "",
        Zorder = 0,
    },
    [4105112] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10511/effect_main_10511",
        action = "lizi_down",
        isLoop = true,
        id = 4105112,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2001] = {
        offset = {
            y = 320,
            x = -586,
        },
        path = "effect/dating_script/baozha/fight_baozha",
        action = "effects_baozha",
        isLoop = false,
        id = 2001,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1118] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1118,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2002] = {
        offset = {
        },
        path = "effect/dating/ui_dating_openEye/dating_effect_1",
        action = "dating_effect_1",
        isLoop = false,
        id = 2002,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = false,
        speBg = "",
        Zorder = 0,
    },
    [1115] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1115,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2003] = {
        offset = {
        },
        path = "effect/dating/ui_dating_openEye/dating_effect_1",
        action = "dating_effect_2",
        isLoop = false,
        id = 2003,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = false,
        speBg = "",
        Zorder = 0,
    },
    [1009] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1009,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2004] = {
        offset = {
        },
        path = "effect/dating/ui_dating_openEye/dating_effect_1",
        action = "dating_effect_3",
        isLoop = false,
        id = 2004,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4103113] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10311/main_effect_10311_qianjing",
        action = "animation3",
        isLoop = true,
        id = 4103113,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2005] = {
        offset = {
        },
        path = "effect/dating/ui_dating_openEye/dating_effect_1",
        action = "dating_effect_4",
        isLoop = false,
        id = 2005,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = false,
        speBg = "",
        Zorder = 0,
    },
    [4129032] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12903/main_effect_12903",
        action = "animation3",
        isLoop = false,
        id = 4129032,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2006] = {
        offset = {
        },
        path = "effect/dating/ui_dating_openEye/dating_effect_1",
        action = "dating_effect_5",
        isLoop = true,
        id = 2006,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = false,
        speBg = "",
        Zorder = 0,
    },
    [1007] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1007,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2007] = {
        offset = {
        },
        path = "effect/dating/ui_dating_blackThunder/dating_effect_2",
        action = "animation",
        isLoop = false,
        id = 2007,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [412903] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_12903/main_effect_12903",
        action = "animation",
        isLoop = true,
        id = 412903,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2008] = {
        offset = {
        },
        path = "effect/dating_script/leiyu/ZT_leiyu",
        action = "animation",
        isLoop = true,
        id = 2008,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4105113] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10511/effect_main_10511",
        action = "lizi_up",
        isLoop = true,
        id = 4105113,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [2009] = {
        offset = {
        },
        path = "effect/dating_dicuo/effects_jinpingguo",
        action = "animation",
        isLoop = false,
        id = 2009,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4102133] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4102133,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_zhezhi_high_10213_middle3.png",
        Zorder = 0,
    },
    [1006] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1006,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4113151] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11315/main_effect_11315",
        action = "animation2",
        isLoop = true,
        id = 4113151,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [410307] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10307/bg_ssn_high1",
        action = "animation",
        isLoop = true,
        id = 410307,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4103112] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10311/main_effect_10311_tiankong",
        action = "animation",
        isLoop = true,
        id = 4103112,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10311_base.png",
        Zorder = 0,
    },
    [410309] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10309/effect_hefusisinai",
        action = "effect_hefusisinai_xia",
        isLoop = true,
        id = 410309,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1012] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1012,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4110094] = {
        offset = {
            y = 10,
            x = -100,
        },
        path = "effect/dating/ui_superKanban_11009/bianshen/main_effect_11009bianshen",
        action = "animation",
        isLoop = false,
        id = 4110094,
        particle = "",
        lag = 0.001,
        scales = 0.7,
        isDelete = true,
        speBg = "",
        Zorder = 3,
    },
    [411009] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11009/main_effect_11009",
        action = "animation",
        isLoop = true,
        id = 411009,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 5,
    },
    [4103091] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10309/effect_hefusisinai",
        action = "effect_hefusisinai_shang",
        isLoop = true,
        id = 4103091,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1129] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 1129,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1016] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1016,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4105141] = {
        offset = {
            y = 3,
            x = 60,
        },
        path = "effect/dating/ui_superKanban_10514/main_effect_10514_trigger",
        action = "animation",
        isLoop = false,
        id = 4105141,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 3,
    },
    [410311] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10311/main_effect_10311_qianjing",
        action = "animation",
        isLoop = true,
        id = 410311,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1013] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1013,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4105142] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4105142,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10514_base.png",
        Zorder = 2,
    },
    [4101092] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10109/effect_main_10109_2",
        action = "stand",
        isLoop = true,
        id = 4101092,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 2,
    },
    [1010] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1010,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411209] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11209/effect_main_11209",
        action = "animation2",
        isLoop = true,
        id = 411209,
        particle = "effect/dating/ui_superKanban_11209/particle/partical_main_11209.plist",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4103111] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10311/main_effect_10311_qianjing",
        action = "animation2",
        isLoop = true,
        id = 4103111,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411207] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11207/effect_main_11207",
        action = "animation",
        isLoop = true,
        id = 411207,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [1011] = {
        offset = {
        },
        path = "",
        action = "animation",
        isLoop = true,
        id = 1011,
        particle = "",
        lag = 0,
        scales = 0,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [4110092] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11009/main_effect_11009",
        action = "animation3",
        isLoop = true,
        id = 4110092,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 2,
    },
    [4104152] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10415/main_effect_10415",
        action = "animation2",
        isLoop = true,
        id = 4104152,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
    [411212] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11212/main_effect_11212_qianjing",
        action = "animation3",
        isLoop = true,
        id = 411212,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 4,
    },
    [4102132] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4102132,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_zhezhi_high_10213_middle2.png",
        Zorder = 0,
    },
    [4101112] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10111/effect_main_10111",
        action = "animation ",
        isLoop = true,
        id = 4101112,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_shixiang_high_10111_top.png",
        Zorder = 0,
    },
    [4112122] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_11212/main_effect_11212_qianjing",
        action = "animation",
        isLoop = true,
        id = 4112122,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 2,
    },
    [4104151] = {
        offset = {
        },
        path = "",
        action = "",
        isLoop = true,
        id = 4104151,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "scene/bg/kanban/bg_10415_middle.png",
        Zorder = 0,
    },
    [4105111] = {
        offset = {
        },
        path = "effect/dating/ui_superKanban_10511/effect_main_10511",
        action = "up",
        isLoop = true,
        id = 4105111,
        particle = "",
        lag = 0,
        scales = 1,
        isDelete = true,
        speBg = "",
        Zorder = 0,
    },
}