local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-datingLetterView_Layer1_dating_Game",
			UUID = "7878c6f8_6863_4eb5_88f3_a3f79dde28ac",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_base_Panel-datingLetterView_Layer1_dating_Game",
					UUID = "10e41221_1b2d_4864_9dbe_3ed50ef8d54e",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "255",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFFFFFFF;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_base",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Relative",
						nType = "3"
					},
					width = "1386",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_bg_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
							UUID = "70db5939_d260_4922_b9eb_0dcd17c3c1da",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "400",
							ignoreSize = "False",
							name = "panel_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 368,
								PositionY = 120,
								relativeToName = "Panel_base",
								nType = 3,
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Relative",
								nType = "3"
							},
							width = "400",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_bg_panel_bg_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "a0f57a92_fa68_4566_8051_778ab10dee8e",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "640",
									ignoreSize = "True",
									name = "Image_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "scene/bg/bg_fuben.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 200,
										PositionY = 200,
										relativeToName = "Panel_base",
										nType = 3,
										nGravity = 6,
										nAlign = 5
									},
									width = "1386",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Image_dailyCityInfoView_1_Image_bg_panel_bg_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "421b10f5_928b_4097_b8b5_e919e945e259",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "572",
											ignoreSize = "True",
											name = "Image_dailyCityInfoView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/dating/newDating/1(13).png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 50,
												PositionY = -32,
											},
											visible = "False",
											width = "1036",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Panel_effect_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
							UUID = "ff7c0b5b_babe_4ed4_a3d0_64b83599ff4c",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "Panel_effect",
							sizepercentx = "100",
							sizepercenty = "100",
							sizeType = "1",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel_main",
								nType = 3,
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Relative",
								nType = "3"
							},
							width = "1386",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "zhuangsi_wjs_Panel_effect_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "f81d4fa5_a1fc_4a55_a92b_64e5ec46fab4",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "586",
									ignoreSize = "True",
									name = "zhuangsi_wjs",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/dating/1214Dating/main/010.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										relativeToName = "Panel_pageItem",
										nType = 3,
										nGravity = 4,
										nAlign = 7
									},
									width = "328",
									ZOrder = "1",
								},
								{
									controlID = "zhuangsi_yjs_Panel_effect_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "65ee7c7b_65ea_4a9d_8c70_14686bbf545f",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "586",
									ignoreSize = "True",
									name = "zhuangsi_yjs",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/dating/1214Dating/main/006.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										relativeToName = "Panel_pageItem",
										nType = 3,
										nGravity = 4,
										nAlign = 7
									},
									visible = "False",
									width = "328",
									ZOrder = "1",
								},
								{
									controlID = "PageView_datingLetter_Panel_effect_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "a4d97ba4_0a09_46b4_acdc_665fae9eefcb",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEPageView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "640",
									ignoreSize = "False",
									name = "PageView_datingLetter",
									sizepercentx = "100",
									sizepercenty = "100",
									sizeType = "1",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = 88,
										BottomPosition = 88,
										relativeToName = "Panel",
										nType = 3,
										nGravity = 6,
										nAlign = 8
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "1386",
									ZOrder = "1",
								},
								{
									controlID = "Panel_touch_Panel_effect_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "758c0acd_0d34_4754_a40f_f55c4434b0bf",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "500",
									ignoreSize = "False",
									name = "Panel_touch",
									sizepercentx = "100",
									sizepercenty = "100",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = 70,
										relativeToName = "Panel",
										nType = 3,
										nGravity = 6,
										nAlign = 5
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "1136",
									ZOrder = "100000",
								},
							},
						},
						{
							controlID = "Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
							UUID = "ecb7fd90_a09e_4bbf_9092_9f044d8a2f4c",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FF0000FF;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "Panel_main",
							sizepercentx = "100",
							sizepercenty = "100",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -125,
								relativeToName = "Panel_base",
								nType = 3,
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1386",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "page_down_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "e65174f6_1f61_47f1_a07e_a121476b91dc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "62",
									ignoreSize = "True",
									name = "page_down",
									normal = "ui/fairy_crystal/left.png",
									pressed = "ui/fairy_crystal/left.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 191,
										PositionY = 340,
										LeftPositon = 167,
										TopPosition = 269,
										relativeToName = "Panel_main",
									},
									UItype = "Button",
									width = "48",
									ZOrder = "1",
								},
								{
									controlID = "page_up_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "e3160f1d_ee58_4f89_b282_365225c080c8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "62",
									ignoreSize = "True",
									name = "page_up",
									normal = "ui/fairy_crystal/left.png",
									pressed = "ui/fairy_crystal/left.png",
									scaleX = "-1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 1206,
										PositionY = 340,
										LeftPositon = 1230,
										TopPosition = 269,
										relativeToName = "Panel_main",
									},
									UItype = "Button",
									width = "48",
									ZOrder = "1",
								},
								{
									controlID = "ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "8fa335d1_3c05_4a14_96d0_1fbab3a220b5",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "640",
									ignoreSize = "False",
									name = "ui_panel",
									sizepercentx = "100",
									sizepercenty = "100",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										relativeToName = "Panel_base",
										nGravity = 6,
										nAlign = 5
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "1386",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "point_bg_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "e606f975_aa5f_41f7_babd_1ccdc52cbe56",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "26",
											ignoreSize = "True",
											name = "point_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/dating/1214Dating/main/002.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 693,
												PositionY = 100,
												TopPosition = 527,
												relativeToName = "ui_panel",
												nGravity = 6,
												nAlign = 2
											},
											width = "270",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Panel_optionList_point_bg_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "95c67675_717a_4a50_a2d7_18940e9258b3",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													bgColorOpacity = "50",
													bIsOpenClipping = "False",
													classname = "MEPanel",
													colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
													DesignHeight = "640",
													DesignType = "0",
													DesignWidth = "960",
													dstBlendFunc = "771",
													height = "36",
													ignoreSize = "False",
													name = "Panel_optionList",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													touchAble = "False",
													UILayoutViewModel = 
													{
														
													},
													uipanelviewmodel = 
													{
														Layout="Absolute",
														nType = "0"
													},
													width = "251",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Image_datingLetterView_1_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "7c7cb68c_5a5c_496a_a258_a5093c9d995c",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "72",
											ignoreSize = "True",
											name = "Image_datingLetterView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/dating/1214Dating/day/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 693,
												PositionY = 46,
												BottomPosition = 10,
												relativeToName = "ui_panel",
												nGravity = 6,
												nAlign = 8
											},
											width = "1386",
											ZOrder = "1",
										},
										{
											controlID = "Image_favor_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "1ff9bba6_b436_469e_a919_927b70f92bc0",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "58",
											ignoreSize = "True",
											name = "Image_favor",
											normal = "ui/dating/1214Dating/main/003.png",
											pressed = "ui/dating/1214Dating/main/003.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 176,
												PositionY = 44,
												LeftPositon = 147,
												TopPosition = 567,
												relativeToName = "ui_panel",
											},
											UItype = "Button",
											width = "58",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_favorValue_Image_favor_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "400aa041_5d70_405c_8337_d2d37601ff39",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													ColorMixing = "#FFEF5F7D",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "30",
													ignoreSize = "True",
													name = "Label_favorValue",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "343",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 148,
														PositionY = -18,
													},
													width = "61",
													ZOrder = "1",
												},
												{
													controlID = "Label_favorTitle_Image_favor_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "91d6de2b_7117_4aa9_9c3e_8e34493ba671",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "22",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF8C8790",
														StrokeSize = 1,
													},
													height = "29",
													ignoreSize = "True",
													name = "Label_favorTitle",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Favor saat ini",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 97,
														PositionY = 12,
													},
													width = "113",
													ZOrder = "1",
												},
												{
													controlID = "Image_favorTip_Image_favor_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "1464e200_4306_4945_968d_8095999ff85b",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "30",
													ignoreSize = "True",
													name = "Image_favorTip",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/common/news_small.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 21,
														PositionY = 20,
													},
													width = "30",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Image_cost_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "56002635_aed0_4d37_98b8_21d9b0531d61",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "58",
											ignoreSize = "True",
											name = "Image_cost",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/newCity/build/25.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1017,
												PositionY = 46,
												RightPosition = 298,
												TopPosition = 565,
												relativeToName = "ui_panel",
												nGravity = 3,
												nAlign = 3
											},
											width = "141",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_costNum_Image_cost_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "6ec2650f_a433_4482_9a93_22a0f0f0ec02",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "28",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF8C8790",
														StrokeSize = 1,
													},
													height = "37",
													ignoreSize = "True",
													name = "Label_costNum",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "646",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 17,
														PositionY = -1,
													},
													width = "76",
													ZOrder = "1",
												},
												{
													controlID = "Image_costIcon_Image_cost_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "236830bd_98dd_494d_881c_d6da3c956031",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "64",
													ignoreSize = "True",
													name = "Image_costIcon",
													scaleX = "0.5",
													scaleY = "0.5",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "icon/item/goods/500024.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = -39,
													},
													width = "64",
													ZOrder = "1",
												},
												{
													controlID = "Label_cost_Image_cost_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "e2a67dfb_16d0_4cdb_bc94_6915b6c3dc3d",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "23",
													ignoreSize = "True",
													name = "Label_cost",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Biaya",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 19,
														PositionY = -13,
													},
													visible = "False",
													width = "43",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "btn_dating_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "8946bb6b_f314_4ab0_a94d_2c263e9f6430",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "58",
											ignoreSize = "True",
											name = "btn_dating",
											normal = "ui/common/button_big_n.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 1178,
												PositionY = 45,
												RightPosition = 141,
												TopPosition = 566,
												relativeToName = "ui_panel",
												nGravity = 3,
												nAlign = 3
											},
											UItype = "Button",
											width = "134",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "btn_label_btn_dating_ui_panel_Panel_main_Panel_base_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "2100cc65_5dcc_4281_bcf9_f6c8fb0fe798",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "27",
													ignoreSize = "True",
													name = "btn_label",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Kencan",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														
													},
													width = "99",
													ZOrder = "1",
												},
											},
										},
									},
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
					UUID = "99bd0dc5_0255_4861_8225_eda3f8363fae",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFDDA0DD;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "100",
					sizepercenty = "100",
					sizeType = "1",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = -34,
						PositionY = -807,
						LeftPositon = -34,
						TopPosition = 807,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Relative",
						nType = "3"
					},
					width = "1386",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
							UUID = "8cf2c7a6_11ec_4da6_8f5e_deeef2541a47",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "True",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "Panel_pageItem",
							sizepercentx = "100",
							sizepercenty = "100",
							sizeType = "1",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel_prefab",
								nType = 3,
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Relative",
								nType = "3"
							},
							width = "1386",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "f8c10d35_f636_4bba_86c6_bb9c5e526480",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "436",
									ignoreSize = "True",
									name = "cg_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/dating/1214Dating/main/005.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 568,
										PositionY = 341,
										TopPosition = 81,
										relativeToName = "Panel_pageItem",
										nType = 3,
										nGravity = 6,
										nAlign = 2
									},
									width = "898",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "cg_parent_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "033b2bce_bb3e_438e_856d_ebe983e48e98",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "True",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "435",
											ignoreSize = "False",
											name = "cg_parent",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -447,
												PositionY = -218,
												LeftPositon = 248,
												TopPosition = 85,
												relativeToName = "Panel_pageItem",
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "897",
											ZOrder = "1",
										},
										{
											controlID = "cg_mask_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "4ec05c5e_f4e6_4fa1_b08f_a1dbb808ae9b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "444",
											ignoreSize = "True",
											name = "cg_mask",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/dating/1214Dating/main/001.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												LeftPositon = 242,
												TopPosition = 77,
												relativeToName = "Panel_pageItem",
											},
											width = "906",
											ZOrder = "1",
										},
										{
											controlID = "Image_lock_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "7d4de1e4_44b8_4834_8cb4_1e291783c55d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "444",
											ignoreSize = "True",
											name = "Image_lock",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/dating/1214Dating/main/011.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												LeftPositon = 242,
												TopPosition = 77,
												relativeToName = "Panel_pageItem",
											},
											width = "906",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_lock_Image_lock_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "ab775e13_2e48_4ab2_ac6a_61c9c20d3718",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF8C8790",
														StrokeSize = 1,
													},
													height = "27",
													ignoreSize = "True",
													name = "Label_lock",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Syarat buka",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 395,
														PositionY = -125,
													},
													width = "85",
													ZOrder = "1",
												},
												{
													controlID = "Label_tiaojian1_Image_lock_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "356bb26f_d7bc_45ae_9e8c_8826647caab1",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "28",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF8C8790",
														StrokeSize = 1,
													},
													height = "37",
													ignoreSize = "True",
													name = "Label_tiaojian1",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Favor mencapai 1000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 434,
														PositionY = -158,
													},
													width = "231",
													ZOrder = "1",
												},
												{
													controlID = "Label_tiaojian2_Image_lock_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "7d111f27_36a7_40b0_b1c6_877e8065171b",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "28",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF8C8790",
														StrokeSize = 1,
													},
													height = "37",
													ignoreSize = "True",
													name = "Label_tiaojian2",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Favor mencapai 1000",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 434,
														PositionY = -194,
													},
													width = "231",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Image_huigu_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "ba527869_c9fd_4d3c_883a_1037ccfdbec7",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "68",
											ignoreSize = "True",
											name = "Image_huigu",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/dating/1214Dating/main/009.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 311,
												PositionY = -178,
												LeftPositon = 877,
												TopPosition = 443,
												relativeToName = "Panel_pageItem",
											},
											width = "256",
											ZOrder = "1",
										},
										{
											controlID = "title_bg_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "f68f6dbe_30f0_423d_8cf8_83f63f7606e9",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "62",
											ignoreSize = "True",
											name = "title_bg",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/dating/1214Dating/main/004.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -364,
												PositionY = 189,
												LeftPositon = 239,
												TopPosition = 78,
												relativeToName = "Panel_pageItem",
											},
											width = "180",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_chapterTitle_title_bg_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "46e89f5f_2db4_4cd8_8e9f_de61a8d3c4d8",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/fangzheng_zhunyuan.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "14",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "16",
													ignoreSize = "True",
													name = "Label_chapterTitle",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Chapter",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = -40,
														PositionY = 10,
													},
													width = "51",
													ZOrder = "1",
												},
												{
													controlID = "Label_chapter_title_bg_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "25584cd1_db26_49cc_b574_da25a506ab62",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_chapter",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Chapter 1",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 29,
														PositionY = 11,
													},
													width = "65",
													ZOrder = "1",
												},
												{
													controlID = "Label_mainName_title_bg_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
													UUID = "24d43c2b_06a7_43b7_9576_57575a1e6614",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "Label_mainName",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "Nickname Nickname Chapter",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionY = -13,
													},
													width = "123",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Panel_reward_cg_bg_Panel_pageItem_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
											UUID = "bfffe0a9_5550_4eba_afca_20a2b5e26fc4",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "0",
											ignoreSize = "False",
											name = "Panel_reward",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 365,
												PositionY = 154,
												LeftPositon = 974,
												TopPosition = -666,
												relativeToName = "Panel_main",
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "0",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "Image_option_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
							UUID = "89ea4236_5823_4603_be1f_280e751b9783",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "30",
							ignoreSize = "False",
							name = "Image_option",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 65,
								PositionY = 142,
								LeftPositon = 50,
								TopPosition = 483,
								relativeToName = "Panel_prefab",
								nType = 3,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "30",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_normal_Image_option_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "fa739846_bc23_48bf_9352_7061578f6137",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "Image_normal",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/dating/newDating/01(1).png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "38",
									ZOrder = "1",
								},
								{
									controlID = "Image_select_Image_option_Panel_prefab_Panel-datingLetterView_Layer1_dating_Game",
									UUID = "56b64478_f63a_4393_8d6f_997ed1459387",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "38",
									ignoreSize = "True",
									name = "Image_select",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/dating/newDating/01(2).png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "38",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"scene/bg/bg_fuben.png",
			"ui/dating/newDating/1(13).png",
			"ui/dating/1214Dating/main/010.png",
			"ui/dating/1214Dating/main/006.png",
			"ui/fairy_crystal/left.png",
			"ui/dating/1214Dating/main/002.png",
			"ui/dating/1214Dating/day/001.png",
			"ui/dating/1214Dating/main/003.png",
			"ui/common/news_small.png",
			"ui/newCity/build/25.png",
			"icon/item/goods/500024.png",
			"ui/common/button_big_n.png",
			"ui/dating/1214Dating/main/005.png",
			"ui/dating/1214Dating/main/001.png",
			"ui/dating/1214Dating/main/011.png",
			"ui/dating/1214Dating/main/009.png",
			"ui/dating/1214Dating/main/004.png",
			"ui/dating/newDating/01(1).png",
			"ui/dating/newDating/01(2).png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

