local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-valentineGiftView_Layer1_valentine_Game",
			UUID = "5414e856_c9b6_4bac_b420_ea88e9169544",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "100",
			sizepercenty = "100",
			sizeType = "1",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1136",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
					UUID = "ec75edf5_026a_4866_8077_ab76a4d0f1c7",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_root",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 568,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
							UUID = "2b27af9e_29a7_41dd_9b57_eb217433b403",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "499",
							ignoreSize = "False",
							name = "Image_content",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui/common/pop_ui/pop_bg_01.png",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -1,
								PositionY = -1,
							},
							width = "378",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_valentineGiftView_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "d81b705a_9d13_4748_98cc_c441eb07b0bc",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "480",
									ignoreSize = "True",
									name = "Image_valentineGiftView_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/valentine/new/gave/014.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "360",
									ZOrder = "1",
								},
								{
									controlID = "Label_title_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "7c28aa00_5dc5_4d35_ba8b_e5e455b771b4",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FF8D293D",
									fontName = "font/MFLiHei_Noncommercial.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "28",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "35",
									ignoreSize = "True",
									name = "Label_title",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "巧克力赠送",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -176,
										PositionY = 217,
									},
									width = "144",
									ZOrder = "1",
								},
								{
									controlID = "Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "a92dfe41_cd70_4ea6_90cc_c912d3ebea39",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "96",
									ignoreSize = "False",
									name = "Panel_item_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 143,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "352",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_goods_Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "60f1ad75_5d52_4d6a_b5cd_23b996d3c188",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "80",
											ignoreSize = "False",
											name = "Panel_goods",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -119,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "80",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "5f7795bb_7776_4b4a_b51a_1ffd6d282ee4",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFCA697E",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "道具名字",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -6,
												PositionY = 21,
											},
											width = "106",
											ZOrder = "1",
										},
										{
											controlID = "Image_count_Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "5f2548b8_c30e_4912_991d_ba7974704f6a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_count",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/valentine/task/011.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 47,
												PositionY = -20,
											},
											width = "214",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_count_Image_count_Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
													UUID = "bc7747fb_61f0_4416_bd9a_f863915429fd",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF49557F",
														StrokeSize = 2,
													},
													height = "34",
													ignoreSize = "True",
													name = "Label_count",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "75",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 50,
														PositionY = -2,
													},
													width = "42",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_add_Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "976e70a5_3155_43d9_9965_6962f2d17200",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_add",
											normal = "ui/common/mini_pop/12.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 134,
												PositionY = -19,
											},
											UItype = "Button",
											width = "44",
											ZOrder = "1",
										},
										{
											controlID = "Button_sub_Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "a84b0024_a2d0_4cf6_ba87_eee6907c0a98",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_sub",
											normal = "ui/common/mini_pop/11.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -42,
												PositionY = -19,
											},
											UItype = "Button",
											width = "44",
											ZOrder = "1",
										},
										{
											controlID = "Image_valentineGiftView_1_Panel_item_1_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "262e232d_e28d_4af5_9f76_c61d2654db6f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "2",
											ignoreSize = "True",
											name = "Image_valentineGiftView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/valentine/new/gave/016.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -49,
											},
											width = "320",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "85750244_fb15_416b_ae8e_2dd787588b78",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "96",
									ignoreSize = "False",
									name = "Panel_item_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 41,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "352",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_goods_Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "b6264bb5_67d1_4aac_9f38_51cffa655899",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "80",
											ignoreSize = "False",
											name = "Panel_goods",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -119,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "80",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "c6ffd52a_d126_45b1_ada8_e04b517b51d2",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFCA697E",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "道具名字",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -6,
												PositionY = 21,
											},
											width = "106",
											ZOrder = "1",
										},
										{
											controlID = "Image_count_Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "fe6cb90f_64dc_4197_9977_97fcadb5b524",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_count",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/valentine/task/011.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 47,
												PositionY = -20,
											},
											width = "214",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_count_Image_count_Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
													UUID = "1af2656e_6b8c_49e4_8fbd_6955e5235993",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF49557F",
														StrokeSize = 2,
													},
													height = "34",
													ignoreSize = "True",
													name = "Label_count",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "75",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 50,
														PositionY = -2,
													},
													width = "42",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_add_Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "5f7f5ef5_f32a_433c_83c0_633e19b9eb34",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_add",
											normal = "ui/common/mini_pop/12.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 135,
												PositionY = -20,
											},
											UItype = "Button",
											width = "44",
											ZOrder = "1",
										},
										{
											controlID = "Button_sub_Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "1ee1578b_5495_46fd_9750_eaafbd8ea16a",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_sub",
											normal = "ui/common/mini_pop/11.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -42,
												PositionY = -20,
											},
											UItype = "Button",
											width = "44",
											ZOrder = "1",
										},
										{
											controlID = "Image_valentineGiftView_1_Panel_item_2_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "507b1b84_1899_4f6e_8c44_728697c7575f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "2",
											ignoreSize = "True",
											name = "Image_valentineGiftView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/valentine/new/gave/016.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -49,
											},
											width = "320",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "f032aaab_6998_4ab3_8847_b5c6b53704e4",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "False",
									classname = "MEPanel",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
									DesignHeight = "640",
									DesignType = "0",
									DesignWidth = "960",
									dstBlendFunc = "771",
									height = "96",
									ignoreSize = "False",
									name = "Panel_item_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -61,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "352",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Panel_goods_Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "c982d8a5_b3a3_4165_b087_795cb09854eb",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "80",
											ignoreSize = "False",
											name = "Panel_goods",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -119,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "80",
											ZOrder = "1",
										},
										{
											controlID = "Label_name_Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "625233f7_593d_40ed_9a0c_0e5f97428db1",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFCA697E",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "32",
											ignoreSize = "True",
											name = "Label_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "道具名字",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -6,
												PositionY = 21,
											},
											width = "106",
											ZOrder = "1",
										},
										{
											controlID = "Image_count_Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "06be992c_6700_4719_8302_6be7d73a1273",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "38",
											ignoreSize = "True",
											name = "Image_count",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/valentine/task/011.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = 47,
												PositionY = -20,
											},
											width = "214",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "Label_count_Image_count_Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
													UUID = "f9c1d121_8d46_417a_8766_f37ab1902a43",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "24",
													fontStroke = 
													{
														IsStroke = true,
														StrokeColor = "#FF49557F",
														StrokeSize = 2,
													},
													height = "34",
													ignoreSize = "True",
													name = "Label_count",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "75",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 50,
														PositionY = -2,
													},
													width = "42",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "Button_add_Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "68153262_b1ee_4ebc_b26a_95b3ed9ee16f",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_add",
											normal = "ui/common/mini_pop/12.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 135,
												PositionY = -20,
											},
											UItype = "Button",
											width = "44",
											ZOrder = "1",
										},
										{
											controlID = "Button_sub_Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "9a18f13f_0df9_4e45_8411_6fed8fbaa223",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "44",
											ignoreSize = "True",
											name = "Button_sub",
											normal = "ui/common/mini_pop/11.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -42,
												PositionY = -20,
											},
											UItype = "Button",
											width = "44",
											ZOrder = "1",
										},
										{
											controlID = "Image_valentineGiftView_1_Panel_item_3_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "bff8565e_8d66_4315_afdc_f01717502f62",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEImage",
											dstBlendFunc = "771",
											height = "2",
											ignoreSize = "True",
											name = "Image_valentineGiftView_1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											texturePath = "ui/valentine/task/010.png",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionY = -49,
											},
											visible = "False",
											width = "320",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Image_tips_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "a0c226ca_45e6_4a56_b50d_5761ed235a5f",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "44",
									ignoreSize = "True",
									name = "Image_tips",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/valentine/new/gave/015.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -144,
									},
									width = "336",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_desc_Image_tips_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "55a2e7cd_51d8_497c_bccb_8e1b9dba1de9",
											anchorPoint = "False",
											anchorPointX = "1",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "25",
											ignoreSize = "True",
											name = "Label_desc",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "默契值增加",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -6,
												PositionY = 2,
											},
											width = "112",
											ZOrder = "1",
										},
										{
											controlID = "Label_num_Image_tips_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "3f68ea9d_953d_4325_8fea_d8cd6cd07ef4",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/MFLiHei_Noncommercial.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "22",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_num",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "45664",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 10,
												PositionY = 2,
											},
											width = "99",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_gift_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "a5f9c374_7753_4cec_acf3_6703142463c2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "54",
									ignoreSize = "True",
									name = "Button_gift",
									normal = "ui/common/button_middle_n.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -200,
									},
									UItype = "Button",
									width = "124",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "Label_gift_Button_gift_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
											UUID = "ff5e8733_9560_4fb1_94b5_2089752e487b",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "font/fangzheng_zhunyuan.ttf",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "24",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "27",
											ignoreSize = "True",
											name = "Label_gift",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "赠送",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												
											},
											width = "51",
											ZOrder = "1",
										},
									},
								},
								{
									controlID = "Button_close_Image_content_Panel_root_Panel-valentineGiftView_Layer1_valentine_Game",
									UUID = "7d2c9e60_c342_4080_bc5b_16b72d28424d",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "60",
									ignoreSize = "True",
									name = "Button_close",
									normal = "ui/common/pop_ui/pop_btn_02.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 154,
										PositionY = 220,
									},
									UItype = "Button",
									width = "60",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "Panel_prefab_Panel-valentineGiftView_Layer1_valentine_Game",
					UUID = "2f51b16f_a197_4ae2_bae3_4ca76bfb3c3a",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_prefab",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 5,
						PositionY = -716,
						LeftPositon = 5,
						TopPosition = 716,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "1136",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/common/pop_ui/pop_bg_01.png",
			"ui/valentine/new/gave/014.png",
			"ui/valentine/task/011.png",
			"ui/common/mini_pop/12.png",
			"ui/common/mini_pop/11.png",
			"ui/valentine/new/gave/016.png",
			"ui/valentine/task/010.png",
			"ui/valentine/new/gave/015.png",
			"ui/common/button_middle_n.png",
			"ui/common/pop_ui/pop_btn_02.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

