local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-danmuFrame_Layer1_common_Game",
			UUID = "7bbd682d_8504_4e9b_9fd5_b5605bd6eada",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				
			},
			uipanelviewmodel = 
			{
				Layout="Absolute",
				nType = "0"
			},
			width = "1386",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "panel_model_Panel-danmuFrame_Layer1_common_Game",
					UUID = "800aa0b0_29ce_4f26_87ad_50a6c233aecc",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "panel_model",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 13,
						PositionY = -1420,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "danmu_itemType_1_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "908e45ee_16d9_4c8e_9077_c6a0a37ddf77",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FF57ABE5",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF30354A",
								StrokeSize = 2,
							},
							height = "31",
							ignoreSize = "True",
							name = "danmu_itemType_1",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								
							},
							width = "97",
							ZOrder = "1",
						},
						{
							controlID = "danmu_itemType_2_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "d864562d_ba8d_4053_b7b1_15b94b3d1eca",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFF6FEFF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF30354A",
								StrokeSize = 2,
							},
							height = "31",
							ignoreSize = "True",
							name = "danmu_itemType_2",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = 40,
							},
							width = "97",
							ZOrder = "1",
						},
						{
							controlID = "danmu_itemType_3_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "dbad3e93_3daa_4b09_87f4_cae3e802f065",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFD3870",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "24",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FFFFFFFF",
								StrokeSize = 2,
							},
							height = "31",
							ignoreSize = "True",
							name = "danmu_itemType_3",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -34,
							},
							width = "97",
							ZOrder = "1",
						},
						{
							controlID = "danmu_itemType_4_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "a811c723_3bbd_4a8c_898a_2cb59f2c54ac",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFF9DB47",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "30",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF594017",
								StrokeSize = 2,
							},
							height = "38",
							ignoreSize = "True",
							name = "danmu_itemType_4",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -80,
							},
							width = "123",
							ZOrder = "1",
						},
						{
							controlID = "danmu_itemType_5_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "e4a5f8fd_f51c_4686_9857_630822826169",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFF6FEFF",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "28",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF30354A",
								StrokeSize = 2,
							},
							height = "36",
							ignoreSize = "True",
							name = "danmu_itemType_5",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -111,
							},
							width = "115",
							ZOrder = "1",
						},
						{
							controlID = "danmu_itemType_6_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "e95cb90f_35ef_49b7_9de6_308bd823972f",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFF9DB47",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "30",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF594017",
								StrokeSize = 2,
							},
							height = "38",
							ignoreSize = "True",
							name = "danmu_itemType_6",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -147,
							},
							width = "123",
							ZOrder = "1",
						},
						{
							controlID = "danmu_itemType_7_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "a1b9aaa1_77ef_401d_8f61_dd8eb0330e7f",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFCF19C",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "30",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF86221D",
								StrokeSize = 2,
							},
							height = "38",
							ignoreSize = "True",
							name = "danmu_itemType_7",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -177,
							},
							width = "123",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_frame_danmu_itemType_7_panel_model_Panel-danmuFrame_Layer1_common_Game",
									UUID = "6d9db80b_27d9_4dab_9ef2_ebd49c86fe31",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "40",
									ignoreSize = "False",
									name = "Image_frame",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/2000.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "128",
									ZOrder = "-1",
								},
							},
						},
						{
							controlID = "danmu_itemType_8_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "b2bb24ed_416a_4bdb_b9d6_837a332a9498",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFD3870",
							fontName = "font/fangzheng_zhunyuan.ttf",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "30",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FFFFFFFF",
								StrokeSize = 2,
							},
							height = "38",
							ignoreSize = "True",
							name = "danmu_itemType_8",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionY = -212,
							},
							width = "123",
							ZOrder = "1",
						},
						{
							controlID = "danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "e974b24f_dd91_4502_8418_79c7b9431674",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "46",
							ignoreSize = "False",
							name = "danmu_itemType_9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -13,
								PositionY = -286,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "297",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "bg_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
									UUID = "d957b08e_c8a2_4668_a68c_5a833376730d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "54",
									ignoreSize = "False",
									name = "bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/evaluation/009.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "300",
									ZOrder = "1",
								},
								{
									controlID = "bg1_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
									UUID = "34b1ea01_3670_452c_a021_f884cc083092",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "34",
									ignoreSize = "True",
									name = "bg1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/evaluation/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 293,
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "unprise_bg1_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
											UUID = "f98d737f_818f_4f79_9883_b1a9e27f3ce7",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "400",
											ignoreSize = "False",
											name = "unprise",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -293,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "400",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "upNum_unprise_bg1_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "cfeb264e_2663_48ea_9d33_f5a6a65b0390",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF25293E",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "upNum",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "3065",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 253,
													},
													width = "70",
													ZOrder = "1",
												},
												{
													controlID = "Image_danmuFrame_3_unprise_bg1_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "27fca5e5_ca3c_4d26_acde_d19013cd188f",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_danmuFrame_3",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/evaluation/004.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 273,
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "prised_bg1_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
											UUID = "296f7f43_aebe_48a6_a6cf_2acf8fb8bfd8",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "400",
											ignoreSize = "False",
											name = "prised",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -293,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											visible = "False",
											width = "400",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "upNum_prised_bg1_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "5eb3b2a0_8e0f_4649_9fdc_4c44ecf9bc83",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "upNum",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "3065",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 253,
													},
													width = "70",
													ZOrder = "1",
												},
												{
													controlID = "Image_danmuFrame_3_prised_bg1_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "a829ab77_fa7f_460e_b594_e0f170d67867",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_danmuFrame_3",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/evaluation/003.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 273,
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Label_content_danmu_itemType_9_panel_model_Panel-danmuFrame_Layer1_common_Game",
									UUID = "e330ac3a_a30d_43d7_af4e_b2bf86f624f4",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF363D71",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_content",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "TextLable",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 11,
									},
									width = "89",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
							UUID = "c8fbda02_32f3_45b1_a504_f98e8d479fa6",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "40",
							ignoreSize = "False",
							name = "danmu_itemType_10",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -13,
								PositionY = -342,
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "295",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "bg_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
									UUID = "a3749b91_ed2b_4b01_a83b_2ab68b2aeec1",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "54",
									ignoreSize = "False",
									name = "bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/evaluation/010.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "300",
									ZOrder = "1",
								},
								{
									controlID = "bg1_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
									UUID = "d6b5188f_8e92_4715_8eb1_2a5a52589a7c",
									anchorPoint = "False",
									anchorPointX = "1",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "34",
									ignoreSize = "True",
									name = "bg1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui/fairy/evaluation/008.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 293,
									},
									width = "150",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "prised_bg1_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
											UUID = "023e5cfd_428c_465f_8d26_826ff1b9e58d",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "10",
											ignoreSize = "False",
											name = "prised",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -293,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											width = "10",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "upNum_prised_bg1_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "e430840f_0b37_481e_a796_d692aef316e8",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FFFFFFFF",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "upNum",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "3065",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 253,
													},
													width = "70",
													ZOrder = "1",
												},
												{
													controlID = "Image_danmuFrame_3_prised_bg1_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "6ee42a7b_1ef2_4923_9f21_00bdf6d391db",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_danmuFrame_3",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/evaluation/003.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 273,
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
										{
											controlID = "unprise_bg1_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
											UUID = "5ce650ee_40c8_41ee_876c_4ff79e7e8423",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0",
											backGroundScale9Enable = "False",
											bgColorOpacity = "50",
											bIsOpenClipping = "False",
											classname = "MEPanel",
											colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
											DesignHeight = "640",
											DesignType = "0",
											DesignWidth = "960",
											dstBlendFunc = "771",
											height = "10",
											ignoreSize = "False",
											name = "unprise",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "False",
											UILayoutViewModel = 
											{
												PositionX = -293,
											},
											uipanelviewmodel = 
											{
												Layout="Absolute",
												nType = "0"
											},
											visible = "False",
											width = "10",
											ZOrder = "1",
											components = 
											{
												
												{
													controlID = "upNum_unprise_bg1_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "31685512_f568_4eaa_ab88_6edca515ad69",
													anchorPoint = "False",
													anchorPointX = "1",
													anchorPointY = "0.5",
													classname = "MELabel",
													compPath = "luacomponents.common.MEIconLabel",
													dstBlendFunc = "771",
													FontColor = "#FF25293E",
													fontName = "font/MFLiHei_Noncommercial.ttf",
													fontShadow = 
													{
														IsShadow = false,
														ShadowColor = "#FFFFFFFF",
														ShadowAlpha = 255,
														OffsetX = 0,
														OffsetY = 0,
													},
													fontSize = "20",
													fontStroke = 
													{
														IsStroke = false,
														StrokeColor = "#FFE6E6E6",
														StrokeSize = 1,
													},
													height = "25",
													ignoreSize = "True",
													name = "upNum",
													nTextAlign = "1",
													nTextHAlign = "1",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "770",
													text = "3065",
													touchAble = "False",
													touchScaleEnable = "False",
													UILayoutViewModel = 
													{
														PositionX = 253,
													},
													width = "70",
													ZOrder = "1",
												},
												{
													controlID = "Image_danmuFrame_3_unprise_bg1_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
													UUID = "ef261e59_88e9_441d_b314_d7ce44c59474",
													anchorPoint = "False",
													anchorPointX = "0.5",
													anchorPointY = "0.5",
													backGroundScale9Enable = "False",
													classname = "MEImage",
													dstBlendFunc = "771",
													height = "40",
													ignoreSize = "True",
													name = "Image_danmuFrame_3",
													sizepercentx = "0",
													sizepercenty = "0",
													sizeType = "0",
													srcBlendFunc = "1",
													texturePath = "ui/fairy/evaluation/004.png",
													touchAble = "False",
													UILayoutViewModel = 
													{
														PositionX = 273,
													},
													width = "40",
													ZOrder = "1",
												},
											},
										},
									},
								},
								{
									controlID = "Label_content_danmu_itemType_10_panel_model_Panel-danmuFrame_Layer1_common_Game",
									UUID = "d3354ef6_1e35_42eb_965a_62c451c1fde1",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "font/fangzheng_zhunyuan.ttf",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "22",
									fontStroke = 
									{
										IsStroke = true,
										StrokeColor = "#FF363D71",
										StrokeSize = 1,
									},
									height = "27",
									ignoreSize = "True",
									name = "Label_content",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "TextLable",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 11,
									},
									width = "89",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui/2000.png",
			"ui/fairy/evaluation/009.png",
			"ui/fairy/evaluation/008.png",
			"ui/fairy/evaluation/004.png",
			"ui/fairy/evaluation/003.png",
			"ui/fairy/evaluation/010.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

